multiple banck nodes & remove patch
assemblee-virtuelle/semapps pull request #1068
Opened 2022-10-26 05:19 UTC by simonLouvet

2022-10-26 05:29 UTC, simonLouvet commented
@srosset81 j'ai une exception au tests . le service registry d'activity pub semble necessiter le PATCH
![image](https://user-images.githubusercontent.com/5068825/197942540-b327a5d0-0877-4d92-aeba-dca9c5206801.png)

2022-10-26 13:06 UTC, nikoPLP requested changes

2022-10-26 13:06 UTC, nikoPLP commented on src/middleware/packages/middlewares/index.js
> +  throw new MoleculerError(JSON.stringify(msg), 403, 'ACCESS_DENIED', {
merci de ne pas reintroduire le JSON.stringify(msg) ici en premier argument pour MoleculerError. Ca fait planter le middleware qaund il y a des characteres speciaux. la string ici doit etre courte et simple, selon les specs HTTP. pour cette raison nous avons introduit un object en 4eme argumet, qui contient le `text` entier de l'erreur.

Idem pour la ligne 40 ci dessous. mettre un 'Internal Server Error' en premier argument

2022-10-26 13:19 UTC, srosset81 requested changes
Désolé mais pour moi c'est clairement insatisfaisant.

- Tout ce que tu as fait sur la méthode PUT, c'est supprimer l'appel à la fonction `mapBlankNodesOnVars`. Je comprend qu'elle posait problème (tu verras dans l'historique qu'elle a été refactorée plusieurs fois) Mais cette fonction a été créée pour éviter que deux triples qui ont la même valeur n'aient le même nom de variable. Et donc en la supprimant, ça crée les exceptions que tu relèves en commentaire. Si j'ai poussé pour utiliser canonize/normalize, c'est pour avoir un code clean, avec des noms de variables uniques. (Quant à l'idée d'hacker le code de Fuseki pour que ça passe, je suis clairement contre)
- Pour le DELETE, il me semble pas que c'était dans le périmètre de cette PR. Si tu dis que ça lève des exceptions, alors mieux vaut ne rien changer. De toute façon l'action delete appelle `deleteOrphanBlankNodes` qui fait bien le job (c'est plus long, mais au moins il n'y a pas de bugs)
- Une recherche du mot "patch" sur le dossier /src/middleware montre qu'il y a encore un certain nombre d'appels à l'action patch (outre l'action PATCH sur le container, qui doit rester bien entendu). Cela concerne le service activitypub, mais aussi webid et aileurs. Pas compliqué à remplacer avec un GET + PUT. Une PR est censé rendre un résultat qui marche.
- Le premier prettier que tu as fait n'a pas pris en compte le paramètre `--print-width 120`. Du coup il y a beaucoup plus de retours à la ligne qu'avant, et on ne peut pas revenir dessus (prettier assume que si on a mis un retour à la ligne, c'est qu'on préférait ça). Ca rend aussi la lecture de la PR plus ardue. Attention à toujours lancer prettier depuis le dossier /src/middleware (yarn run prettier).

Temps de review: 1h45

2022-10-26 13:30 UTC, nikoPLP commented
> Désolé mais pour moi c'est clairement insatisfaisant.
> 
>     * Tout ce que tu as fait sur la méthode PUT, c'est supprimer l'appel à la fonction `mapBlankNodesOnVars`. Je comprend qu'elle posait problème (tu verras dans l'historique qu'elle a été refactorée plusieurs fois) Mais cette fonction a été créée pour éviter que deux triples qui ont la même valeur n'aient le même nom de variable. Et donc en la supprimant, ça crée les exceptions que tu relèves en commentaire. Si j'ai poussé pour utiliser canonize/normalize, c'est pour avoir un code clean, avec des noms de variables uniques. (Quant à l'idée d'hacker le code de Fuseki pour que ça passe, je suis clairement contre)
> 
>     * Pour le DELETE, il ne me semble pas que c'était dans le périmètre de cette PR. Si tu dis que ça lève des exceptions, alors mieux vaut ne rien changer. De toute façon l'action delete appelle `deleteOrphanBlankNodes` qui fait bien le job (c'est plus long, mais au moins il n'y a pas de bugs)
> 
>     * Une recherche du mot "patch" sur le dossier /src/middleware montre qu'il y a encore un certain nombre d'appels à l'action patch (outre l'action PATCH sur le container, qui doit rester bien entendu). Cela concerne le service activitypub, mais aussi webid et aileurs. Pas compliqué à remplacer avec un GET + PUT. Une PR est censé rendre un résultat qui marche.
> 
> 
> > Note: Le premier prettier que tu as fait n'a pas pris en compte le paramètre `--print-width 120`. Du coup il y a beaucoup plus de retours à la ligne qu'avant, et on ne peut pas revenir dessus (prettier assume que si on a mis un retour à la ligne, c'est qu'on préférait ça). Ca rend aussi la lecture de la PR plus ardue. Attention à toujours lancer prettier depuis le dossier /src/middleware (yarn run prettier).
> 
> Temps de review: 1h45

Je pense qu'en effet les erreurs de Fuseki (peut etre liée au systeme des permissions webacl, ca reste a prouver) sont due a des ?variable identiques... et la canonicalization va resoudre ce probleme

2022-10-26 14:58 UTC, simonLouvet commented on src/middleware/packages/middlewares/index.js
> +  throw new MoleculerError(JSON.stringify(msg), 403, 'ACCESS_DENIED', {
ok, je corrige

2022-10-26 15:11 UTC, simonLouvet commented
> > Désolé mais pour moi c'est clairement insatisfaisant.
> > ```
> > * Tout ce que tu as fait sur la méthode PUT, c'est supprimer l'appel à la fonction `mapBlankNodesOnVars`. Je comprend qu'elle posait problème (tu verras dans l'historique qu'elle a été refactorée plusieurs fois) Mais cette fonction a été créée pour éviter que deux triples qui ont la même valeur n'aient le même nom de variable. Et donc en la supprimant, ça crée les exceptions que tu relèves en commentaire. Si j'ai poussé pour utiliser canonize/normalize, c'est pour avoir un code clean, avec des noms de variables uniques. (Quant à l'idée d'hacker le code de Fuseki pour que ça passe, je suis clairement contre)
> > 
> > * Pour le DELETE, il ne me semble pas que c'était dans le périmètre de cette PR. Si tu dis que ça lève des exceptions, alors mieux vaut ne rien changer. De toute façon l'action delete appelle `deleteOrphanBlankNodes` qui fait bien le job (c'est plus long, mais au moins il n'y a pas de bugs)
> > 
> > * Une recherche du mot "patch" sur le dossier /src/middleware montre qu'il y a encore un certain nombre d'appels à l'action patch (outre l'action PATCH sur le container, qui doit rester bien entendu). Cela concerne le service activitypub, mais aussi webid et aileurs. Pas compliqué à remplacer avec un GET + PUT. Une PR est censé rendre un résultat qui marche.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > > Note: Le premier prettier que tu as fait n'a pas pris en compte le paramètre `--print-width 120`. Du coup il y a beaucoup plus de retours à la ligne qu'avant, et on ne peut pas revenir dessus (prettier assume que si on a mis un retour à la ligne, c'est qu'on préférait ça). Ca rend aussi la lecture de la PR plus ardue. Attention à toujours lancer prettier depuis le dossier /src/middleware (yarn run prettier).
> > 
> > 
> > Temps de review: 1h45
> 
> Je pense qu'en effet les erreurs de Fuseki (peut etre liée au systeme des permissions webacl, ca reste a prouver) sont due a des ?variable identiques... et la canonicalization va resoudre ce probleme

Apres beaucoup de test et de vérifications, ce n'est pas lié à un nom de ?variable identique. Dans le code livré, les ?variables sont bien différentes meme si la valeur dans le blancknode est identique. Il n'est pas possible pour jenna de supprimer un blanck node sur deux identique en base. Donc la canonisation ne résoudra pas ce problème.

2022-10-26 15:38 UTC, simonLouvet commented
> Désolé mais pour moi c'est clairement insatisfaisant.
> 
> * Tout ce que tu as fait sur la méthode PUT, c'est supprimer l'appel à la fonction `mapBlankNodesOnVars`. Je comprend qu'elle posait problème (tu verras dans l'historique qu'elle a été refactorée plusieurs fois) Mais cette fonction a été créée pour éviter que deux triples qui ont la même valeur n'aient le même nom de variable. Et donc en la supprimant, ça crée les exceptions que tu relèves en commentaire. Si j'ai poussé pour utiliser canonize/normalize, c'est pour avoir un code clean, avec des noms de variables uniques. (Quant à l'idée d'hacker le code de Fuseki pour que ça passe, je suis clairement contre)
La méthode utilisée, en exploitant le nom de variable fourni par rdf-parse, garantie des nom de variable différentes pour les banck node. Ce n'est pas cela qui produit les exception. ce qui produit les exceptions c'est lors d'un delete d'un blank node si un autre parfaitement identique existe et c'est lié a jenna qui supprime les 2 blank node identique pluto que un seul meme si les variable de la query sont parfaitement gérés
> * Pour le DELETE, il ne me semble pas que c'était dans le périmètre de cette PR. Si tu dis que ça lève des exceptions, alors mieux vaut ne rien changer. De toute façon l'action delete appelle `deleteOrphanBlankNodes` qui fait bien le job (c'est plus long, mais au moins il n'y a pas de bugs)

Ok je remet le DELETE comme il était. cela permettra de supprimer un sujet "verolé"

> * Une recherche du mot "patch" sur le dossier /src/middleware montre qu'il y a encore un certain nombre d'appels à l'action patch (outre l'action PATCH sur le container, qui doit rester bien entendu). Cela concerne le service activitypub, mais aussi webid et aileurs. Pas compliqué à remplacer avec un GET + PUT. Une PR est censé rendre un résultat qui marche.

Oui je suis d'accord, je peux faire le menage sur les partie qui utilisent PATCH.

> > Note: Le premier prettier que tu as fait n'a pas pris en compte le paramètre `--print-width 120`. Du coup il y a beaucoup plus de retours à la ligne qu'avant, et on ne peut pas revenir dessus (prettier assume que si on a mis un retour à la ligne, c'est qu'on préférait ça). Ca rend aussi la lecture de la PR plus ardue. Attention à toujours lancer prettier depuis le dossier /src/middleware (yarn run prettier).

J'ai fait le prettier normal 'yarn run prettier' à la racine du middleware

> Temps de review: 1h45

2022-10-26 15:57 UTC, nikoPLP commented
> Apres beaucoup de test et de vérifications, ce n'est pas lié à un nom de ?variable identique. Dans le code livré, les ?variables sont bien différentes meme si la valeur dans le blancknode est identique. Il n'est pas possible pour jenna de supprimer un blanck node sur deux identique en base. Donc la canonisation ne résoudra pas ce problème.

oui c était a craindre. je veux bien regarder coté Jena ce qui se passe. c'est quoi le message d'erreur exact qur tu obtiens de Fuseki?

2022-10-26 16:14 UTC, nikoPLP commented
> Apres beaucoup de test et de vérifications, ce n'est pas lié à un nom de ?variable identique. Dans le code livré, les ?variables sont bien différentes meme si la valeur dans le blancknode est identique. Il n'est pas possible pour jenna de supprimer un blanck node sur deux identique en base. Donc la canonisation ne résoudra pas ce problème.

Pourrais tu me donner au exemple aussi de blanknodes identiques associés plusieurs fois a une meme resource, dans semapps ? ca m'intrigue

2022-10-27 01:22 UTC, simonLouvet commented
> > Apres beaucoup de test et de vérifications, ce n'est pas lié à un nom de ?variable identique. Dans le code livré, les ?variables sont bien différentes meme si la valeur dans le blancknode est identique. Il n'est pas possible pour jenna de supprimer un blanck node sur deux identique en base. Donc la canonisation ne résoudra pas ce problème.
> 
> Pourrais tu me donner au exemple aussi de blanknodes identiques associés plusieurs fois a une meme resource, dans semapps ? ca m'intrigue

Je ne connais pas projet dans lequel c'est arrivé mais c'est une possibilité qui peut apparaître et que j'avais inclue dans mes test (manuels). Je documenterai un cas dans cette PR.

2022-10-27 04:09 UTC, simonLouvet commented
Exemple de requête qui provoque l'exeption si deux blank node identique sur le meme sujet & predicat
```
DELETE {
	?df_6_0 <http://virtual-assembly.org/ontologies/pair#label> '''Nantes''' .
	<http://localhost:3000/organizations/635a02b8b33298f1c058ec9a> <http://virtual-assembly.org/ontologies/pair#hasLocation> ?df_6_0 .
	?df_6_1 <http://virtual-assembly.org/ontologies/pair#label> '''Nantes''' .
	<http://localhost:3000/organizations/635a02b8b33298f1c058ec9a> <http://virtual-assembly.org/ontologies/pair#hasLocation> ?df_6_1 .
}
INSERT {
	<http://localhost:3000/organizations/635a02b8b33298f1c058ec9a> <http://virtual-assembly.org/ontologies/pair#hasLocation> ?df_7_0 .
	?df_7_0 <http://virtual-assembly.org/ontologies/pair#label> '''Compiegne''' .
}
WHERE {
	?df_6_0 <http://virtual-assembly.org/ontologies/pair#label> '''Nantes''' .
	<http://localhost:3000/organizations/635a02b8b33298f1c058ec9a> <http://virtual-assembly.org/ontologies/pair#hasLocation> ?df_6_0 .
	?df_6_1 <http://virtual-assembly.org/ontologies/pair#label> '''Nantes''' .
	<http://localhost:3000/organizations/635a02b8b33298f1c058ec9a> <http://virtual-assembly.org/ontologies/pair#hasLocation> ?df_6_1 .
	BIND (BNODE() AS ?df_7_0) .
}
```
exception :
![image](https://user-images.githubusercontent.com/5068825/198188963-60bd89f6-e968-4a25-8604-0858af814a2e.png)

état de la base de donnée : 
```
{
	"@context": "http://localhost:3000/context.json",
	"type": "pair:Organization",
	"pair:label": "test upadte  orga",
	"pair:hasLocation": [
		{
			"pair:label": "Nantes"
		},
				{
			"pair:label": "Nantes"
		}
	]
}
```
requête curl de PUT
```
curl --request PUT \
  --url http://localhost:3000/organizations/635a02b8b33298f1c058ec9a \
  --header 'Content-Type: application/json' \
  --header 'accept: application/ld+json' \
  --data '{
	"@context": "http://localhost:3000/context.json",
	"type": "pair:Organization",
	"pair:label": "test upadte  orga",
	"pair:hasLocation": [{
      "pair:label": "Compiegne"
    }]
}'
```

2022-10-27 04:24 UTC, simonLouvet commented
@srosset81 j'ai suivi tout ce que nous avions convenu par téléphone. J'ai tenté de supprimer complètement l'ation patch mais je me suis heurté à des complications pour les collections activitypub et j'ai fait marche arrière. L'api http et les méthodes courantes (controledContainer, adapter...) n'exposent/n'utilisent plus la méthode patch mais je l'ai laissé pour activitypub. Il reste un test qui ne passe pas chez moi (activitypub/follow.test) mais j'ai le même résultat sur la branche next avec les même erreurs donc ce n'est pas lié à cette PR.

@nikoPLP j'ai documenté le bug

2022-10-27 08:58 UTC, nikoPLP commented
> @nikoPLP j'ai documenté le bug

merci beaucoup ! je vais regarder ca!

2022-10-27 09:02 UTC, nikoPLP approved these changes
je laisse Seb voir avec toi pour la review en general. de mon coté, mon commentaire a été pris en compte

2022-10-27 09:31 UTC, srosset81 commented
@simonLouvet Si je regarde la requête SPARQL, ça ne m'étonne pas qu'il y ait une erreur de type "Triple permission violation" (donc au niveau de la surcouche WebACL)

```sparql
DELETE {
	?df_6_0 <http://virtual-assembly.org/ontologies/pair#label> '''Nantes''' .
	<http://localhost:3000/organizations/635a02b8b33298f1c058ec9a> <http://virtual-assembly.org/ontologies/pair#hasLocation> ?df_6_0 .
	?df_6_1 <http://virtual-assembly.org/ontologies/pair#label> '''Nantes''' .
	<http://localhost:3000/organizations/635a02b8b33298f1c058ec9a> <http://virtual-assembly.org/ontologies/pair#hasLocation> ?df_6_1 .
}
INSERT {
	<http://localhost:3000/organizations/635a02b8b33298f1c058ec9a> <http://virtual-assembly.org/ontologies/pair#hasLocation> ?df_7_0 .
	?df_7_0 <http://virtual-assembly.org/ontologies/pair#label> '''Compiegne''' .
}
WHERE {
	?df_6_0 <http://virtual-assembly.org/ontologies/pair#label> '''Nantes''' .
	<http://localhost:3000/organizations/635a02b8b33298f1c058ec9a> <http://virtual-assembly.org/ontologies/pair#hasLocation> ?df_6_0 .
	?df_6_1 <http://virtual-assembly.org/ontologies/pair#label> '''Nantes''' .
	<http://localhost:3000/organizations/635a02b8b33298f1c058ec9a> <http://virtual-assembly.org/ontologies/pair#hasLocation> ?df_6_1 .
	BIND (BNODE() AS ?df_7_0) .
}
```

Si dans la partie DELETE on efface `?df_6_0 <http://virtual-assembly.org/ontologies/pair#label> '''Nantes'''` avant `<http://localhost:3000/organizations/635a02b8b33298f1c058ec9a> <http://virtual-assembly.org/ontologies/pair#hasLocation> ?df_6_0`, c'est justement pour éviter ce type d'erreur de violation. Car si on faisait le contraire, la surcouche WebACL ne saurait plus à quelle ressource le premier triplet (`?df_6_0 <http://virtual-assembly.org/ontologies/pair#label> '''Nantes'''`) est rattaché. 

On fait l'inverse dans la partie INSERT pour la même raison (d'abord on rattache à la ressource, ensuite on ajoute le triplet).

Dans le cas de cette requête ci-dessus, lorsqu'on arrive au troisième triplet (`?df_6_1 <http://virtual-assembly.org/ontologies/pair#label> '''Nantes'''`), celui-ci n'est plus rattaché à aucune ressource (elle a été effacée par le triplet précédent), donc on a obligatoirement une violation des WebACL.

Le quatrième triplet (`<http://localhost:3000/organizations/635a02b8b33298f1c058ec9a> <http://virtual-assembly.org/ontologies/pair#hasLocation> ?df_6_1`) par contre ne pose pas de problème. Il ne sert à rien, mais c'est pas un problème pour Fuseki, ni pour la surchouche WebACL.

Il y a donc effectivemnet deux solutions:

- On pourrait faire évoluer Fuseki pour qu'il considère les blank nodes orphelins comme des triplets qui peuvent être effacés par n'importe qui, mais je crois que @nikoPLP y voyait un risque de sécurité (à moins que ce soit compliqué techniquement d'identifier un blank node ?). Une fois qu'un blank node est orphelin, il ne peut être supprimé que par une requête avec `webId: system`. De mon point de vue, un blank node orphelin n'a absolument aucune utilité. N'étant rattaché à rien du tout, il ne peut pas apparaître sur le serveur LDP, même si on peut le retrouver avec une requête SPARQL adéquate. Donc on s'en fout un peu si quelqu'un l'efface, c'est comme un déchet.

- L'autre alternative serait d'adapter la requête SPARQL pour qu'elle identifie ce type de "doublon" et du coup n'inclue pas les triplets 3 et 4. Pas besoin d'introduire un discriminant par contre: en comparant les triples on peut voir qu'ils sont identiques (seul le nom de la variable change).

2022-10-27 09:50 UTC, nikoPLP commented
> (elle a été effacée par le triplet précédent)

Seb, on est bien d'accord sur tout ce que tu as ecrit, sauf cette petite remarque.

Je voulais regarder dans Jena pourquoi le tripler 3 ne passe pas (on est bien d'accord que c'est celui la qui ne passe pas, meme si le mesage d'erreur n'est pas clair a 100%)

Car Jena devrait comprendre que le triplet 2 qui est effacé, concerne seulement ?df_6_0
Hors il semble que Jena efface le triplet 2 ET le triplet 4, au moment ou il efface le tripelt 2. C'est peut etre un bug de Jena !
car Simon a raison de dire que ?df_6_0 et ?df_6_1 sont bien differents, et donc la requete indiquée ci-dessus par Simon devrait passer tres bien, et les WEBACL devraient passer aussi. 
J'ai toujours du mal a comprendre pourquoi Jena confond ?df_6_1 avec ?df_6_0 au niveau du triplet 2.

2022-10-27 09:54 UTC, nikoPLP commented
La reponse est peut etre dans cette question SO : https://stackoverflow.com/questions/59977208/how-to-delete-duplicate-blank-nodes

ou on voit un `filter(?q != ?s)`
qui serait chez nous un `filter(?df_6_0 != ?df_6_1)` a rajouter a la fin de la requete.
Car il semble que le probleme vienne du WHERE, qui matche les deux blanknodes avec la variable ?df_6_0 !!!

2022-10-27 09:57 UTC, srosset81 commented
@nikoPLP Il faut se rappeler que `?df_6_0` est simplement un nom de variable, c'est pas un nom de blank node. Du coup c'est pas du tout étonnant que Fuseki efface les 2 triplets, c'est parfaitement cohérent avec la spec SPARQL.

2022-10-27 10:11 UTC, nikoPLP commented
C'est ca . Et c'est pour ca que le filter != est indispensable si on veut effacer les triplets un par un, ou alors il faut revoir entierement la requete, et ne PAS mettre les triples/variables en double, car c'est inutile et meme incorrecte, et ca fait planter a cause des webacls.

2022-10-27 18:28 UTC, srosset81 commented
J'ai compris pourquoi remplacer le PATCH par le PUT échouait pour ActivityPub: pour les acteurs (et parfois les objets), des collections (p.ex. followers, following...) sont ajoutées après création. Or si on fait un PATCH, ces collections ne sont jamais touchées. Par contre si on get un GET + PUT avant que les collections soient créées, cela a un effet potentiellement destructeur sur ces collections.

On peut vérifier ça à chaque opération GET+PUT mais c'est quand même source de bugs. Idéalement il faudrait que je trouve un moyen pour que l'on attende que les collections soient créées avant de terminer la création de l'acteur ou de l'objet. C'est possible avec des "controlled containers", mais là les containers ne sont pas forcément contrôllés... donc il va peut-être falloir refactorer le ActivityPubRegistryService qui gère tout ça. :-/

2022-10-27 21:42 UTC, simonLouvet commented
> J'ai compris pourquoi remplacer le PATCH par GET+PUT échouait pour ActivityPub: pour les acteurs (et parfois les objets), des collections (p.ex. followers, following...) sont ajoutées après création. Or si on fait un PATCH, ces collections ne sont jamais écrasées car PATCH est non-destructif. Par contre si on get un GET+PUT avant que les collections soient créées, cela a un effet potentiellement destructeur sur ces collections.
> 
> On peut vérifier que les collections sont créées avant chaque opération GET+PUT mais c'est quand même source de bugs. Idéalement il faudrait que je trouve un moyen pour que l'on attende que les collections soient créées avant de terminer la création de l'acteur ou de l'objet. C'est possible avec des "controlled containers", mais là les containers ne sont pas forcément contrôllés... donc il va peut-être falloir refactorer le ActivityPubRegistryService qui gère tout ça. :-/

Je pense que on peut laisser le patch en méthode "interne" pour le moment. Il n'est pas exposé, on sait que on veut s'en débarrasser à terme mais on peut le tolérer ne temps d'un refactoring progressif.

2022-10-27 21:50 UTC, simonLouvet commented
> filter(?df_6_0 != ?df_6_1)

J'ai testé et effectivement ça fonctionne. Tres bien vue et merci @nikoPLP !! ca sort définitivement le besoin de discriminant de mon spectre des possibles.
Je pense faire une méthode qui génère un where d'exclusion sur toutes les variable de blanknode (ou uniquement ceux identique mais cela me semble de la complexité inutile) qui garantira que ce bug ne puisse plus advenir.
Encore merci pour tes recherches qui résolvent le problème avec beaucoup d’élégance.

2022-10-28 18:40 UTC, simonLouvet commented
@nikoPLP mes essais d'hier étaient positif mais j'ai du me tromper dans sa mise ne place.
![image](https://user-images.githubusercontent.com/5068825/198708765-a5de5f1b-9c06-4409-98a3-0850c99048f7.png)

La solution de différencier les variables dans le where ne permet pas à notre fuseki d'éviter l'erreur. Peut être a essayer sur un fuseki sans notre surcouche?

2022-10-28 18:45 UTC, simonLouvet commented
> @simonLouvet Si je regarde la requête SPARQL, ça ne m'étonne pas qu'il y ait une erreur de type "Triple permission violation" (donc au niveau de la surcouche WebACL)
> 
> ```sparql
> DELETE {
> 	?df_6_0 <http://virtual-assembly.org/ontologies/pair#label> '''Nantes''' .
> 	<http://localhost:3000/organizations/635a02b8b33298f1c058ec9a> <http://virtual-assembly.org/ontologies/pair#hasLocation> ?df_6_0 .
> 	?df_6_1 <http://virtual-assembly.org/ontologies/pair#label> '''Nantes''' .
> 	<http://localhost:3000/organizations/635a02b8b33298f1c058ec9a> <http://virtual-assembly.org/ontologies/pair#hasLocation> ?df_6_1 .
> }
> INSERT {
> 	<http://localhost:3000/organizations/635a02b8b33298f1c058ec9a> <http://virtual-assembly.org/ontologies/pair#hasLocation> ?df_7_0 .
> 	?df_7_0 <http://virtual-assembly.org/ontologies/pair#label> '''Compiegne''' .
> }
> WHERE {
> 	?df_6_0 <http://virtual-assembly.org/ontologies/pair#label> '''Nantes''' .
> 	<http://localhost:3000/organizations/635a02b8b33298f1c058ec9a> <http://virtual-assembly.org/ontologies/pair#hasLocation> ?df_6_0 .
> 	?df_6_1 <http://virtual-assembly.org/ontologies/pair#label> '''Nantes''' .
> 	<http://localhost:3000/organizations/635a02b8b33298f1c058ec9a> <http://virtual-assembly.org/ontologies/pair#hasLocation> ?df_6_1 .
> 	BIND (BNODE() AS ?df_7_0) .
> }
> ```
> 
> Si dans la partie DELETE on efface le triplet 1 (`?df_6_0 <http://virtual-assembly.org/ontologies/pair#label> '''Nantes'''`) avant le triplet 2 (`<http://localhost:3000/organizations/635a02b8b33298f1c058ec9a> <http://virtual-assembly.org/ontologies/pair#hasLocation> ?df_6_0`), c'est justement pour éviter ce type d'erreur de violation. Car si on faisait le contraire, la surcouche WebACL ne saurait plus à quelle ressource le triplet 1 (`?df_6_0 <http://virtual-assembly.org/ontologies/pair#label> '''Nantes'''`) est rattaché.
> 
> On fait l'inverse dans la partie INSERT pour la même raison (d'abord on rattache à la ressource, ensuite on ajoute le triplet).
> 
> Dans le cas de cette requête ci-dessus, lorsqu'on arrive au triplet 3 (`?df_6_1 <http://virtual-assembly.org/ontologies/pair#label> '''Nantes'''`), celui-ci n'est plus rattaché à aucune ressource (elle a été effacée par le triplet précédent), donc on a obligatoirement une violation des WebACL.
> 
> Le triplet 4 (`<http://localhost:3000/organizations/635a02b8b33298f1c058ec9a> <http://virtual-assembly.org/ontologies/pair#hasLocation> ?df_6_1`) par contre ne pose pas de problème. Il ne sert à rien, mais c'est pas un problème pour Fuseki, ni pour la surchouche WebACL.
> 
> Il y a donc effectivemnet deux solutions:
> 
> * On pourrait faire évoluer Fuseki pour qu'il considère les blank nodes orphelins comme des triplets qui peuvent être effacés par n'importe qui, mais je crois que @nikoPLP y voyait un risque de sécurité (à moins que ce soit compliqué techniquement d'identifier un blank node orphelin ?). Actuellement, un blank node orphelin ne peut être supprimé que par une requête avec `webId: system`. De mon point de vue, un blank node orphelin n'a absolument aucune utilité: c'est un déchet. N'étant rattaché à rien du tout, il ne peut pas apparaître sur le serveur LDP, même si on peut le retrouver avec une requête SPARQL adéquate. Donc on s'en fout un peu si quelqu'un l'efface (ça fait du nettoyage !)

L'objectif pour moi est de différencier les blank nodes "identique" plutot que de supprimer les 2 quand on veut en supprimer un. Je n'ai pas compris pourquoi tu parles de droits d’accès aux blank node orphelin

> * L'autre alternative serait d'adapter la requête SPARQL pour qu'elle identifie ce type de "doublon" et du coup n'inclue pas les triplets 3 et 4. Pas besoin d'introduire un discriminant par contre: en comparant les triples on peut voir qu'ils sont identiques (seul le nom de la variable change).

J'ai essayé la solution de niko mais le résultat est le même malheureusement

2022-10-28 18:47 UTC, simonLouvet commented
@nikoPLP et @srosset81 je suis pret à sortir la 0.4 en ayant identifier/documenté ce bug.
Si on arrive pas à faire ce que l'ont veut avec jenna en différenciant les blank node je ne voie toujours pas d'autre solution que un discriminant persisté ou de faire un patch sur jenna.

2022-11-15 14:44 UTC, srosset81 commented
@simonLouvet Pour info j'ai restauré l'API PATCH afin de pouvoir faire le refacto prévu sur une autre branche. Merci de faire un `git pull` avant de finaliser ton travail.

2022-11-17 01:49 UTC, simonLouvet commented
@srosset81 j'ai ajouté la gestion des blank node qui ont strictement la même valeur y compris les cas complexe avec blank nodes imbriqués. Une batteries de test pour tester tous les cas a également été ajouté pour le POST et le PUT. j'ai laissé `mapBlankNodesOnVars`par ce qu'il est utilisé dans le patch que tu as remis.

2022-11-21 10:57 UTC, srosset81 requested changes
Merci ! J'avoue ne pas avoir tout compris à la méthode removeDuplicatedVariables mais comme il y a une batterie de tests, cela me semble solide.
Juste quelques mini-correctifs ci-dessous.

2022-11-21 10:57 UTC, srosset81 commented on src/middleware/packages/ldp/services/resource/methods.js
> +  async removeDuplicatedVariables(triples) {
Je crois que, ni cette méthode, ni buildJsonVariable n'ont besoin d'être async.

2022-11-21 10:57 UTC, srosset81 commented on src/middleware/packages/ldp/services/resource/actions/put.js
> +        newTriples = await this.removeDuplicatedVariables(newTriples);
Dans des cas complexes comme ça, je trouve bien de mettre un lien vers l'issue (même fermée) afin qu'on puisse se souvenir plus tard de quoi il s'agissait précisément.

2022-11-21 10:57 UTC, srosset81 commented on src/middleware/packages/ldp/services/resource/actions/put.js
> +        let triplesToAdd = this.getTriplesDifference(newTriples, oldTriples).reverse();
triplesToAdd peut rester une constante.

2022-11-22 19:44 UTC, simonLouvet commented on src/middleware/packages/ldp/services/resource/methods.js
> +  async removeDuplicatedVariables(triples) {
exact, cela venait des essais precedents

2022-11-22 20:51 UTC, simonLouvet commented
@srosset81 review pris en compte

2022-11-23 07:54 UTC, srosset81 approved these changes

2022-11-23 08:21 UTC, merged