101 slug
assemblee-virtuelle/semapps pull request #111
Opened 2020-01-21 10:52 UTC by simonLouvet

Slug header supported in LDP Post

2020-01-21 15:51 UTC, srosset81 commented
@simonLouvet Comme évoqué dans l'issue https://github.com/assemblee-virtuelle/semapps/issues/101 il faut gérer les cas où le slug existe déjà. Sinon tu vas te trouver à ajouter des informations à double si le même slug est passé deux fois.

Trois solutions:
- On incrémente avec un numéro (`simonLouvet` -> `simonLouvet2`)
- On refuse le slug et on renvoie une erreur
- On ignore le slug et on utilise un UUID

Je serai plutôt favorable à la première solution, qui est user-friendly

2020-01-22 11:39 UTC, simonLouvet commented
L’incrément va vraiment être relou à gérer. Il faudrait persister un compteur car trouver le dernier incrément dans les triplet va être consommateur de ressource et vraiment "crade". Je te propose une alternative, si le slug existe, on lui rajoute un uuid après.
(simonLouvet -> simonLouvet563463652)

2020-01-22 11:50 UTC, srosset81 commented
`simonLouvet563463652` c'est ultra lourd et illisible.
Pas besoin de persister un compter, avec une simple boucle c'est fait. D'abord `simonLouvet` puis `simonLouvet2` puis `simonLouvet3`, etc.  On devrait pas avoir des dizaines d'entités avec le même slug, donc au pire il fera une ou deux requêtes supplémentaires.

2020-01-22 11:58 UTC, simonLouvet commented
ca veut quand meme dire une requête sparql avec regex etc...

2020-01-24 00:16 UTC, simonLouvet commented
@srosset81 incrémentation implémentée

2020-01-24 14:29 UTC, srosset81 requested changes

2020-01-24 14:29 UTC, srosset81 commented on src/middleware/packages/ldp/index.js
> +
A enlever

2020-01-24 14:29 UTC, srosset81 commented on src/middleware/packages/ldp/service.js
> +      const requiereId = this.generateId(typeURL, slug);
Tu veux dire `requiredId` ? Je comprends pas ce nommage. Peut-être `generatedId` ?

2020-01-24 14:29 UTC, srosset81 commented on src/middleware/packages/ldp/service.js
> +            FILTER regex(str(?uri), "^${requiereId}")
:+1:

2020-01-24 14:29 UTC, srosset81 commented on src/middleware/packages/ldp/service.js
> +      body['@id'] = requiereId.concat(counter > 0 ? counter.toString() : '');
Pour éviter de surcharger cette fonction, je proposerais de créer une méthode. Par exemple `findUnusedUri` ?

2020-02-01 18:47 UTC, srosset81 approved these changes

2020-02-01 18:48 UTC, merged