DELETE and INSERT AFTER instead both same time
assemblee-virtuelle/semapps pull request #118
Opened 2020-01-24 13:07 UTC by simonLouvet

resolve #115

2020-01-24 14:44 UTC, srosset81 requested changes
Ton correctif marche mais il crée malheureusement un autre problème.

Si je POST une note comme ça:
```
{
 "@context": "https://www.w3.org/ns/activitystreams",
 "type": "Note",
 "name": "Hello World"
}
```
Puis que je la PATCH en changeant le nom + en ajoutant une propriété:
```
{
 "@context": "https://www.w3.org/ns/activitystreams",
 "type": "Note",
 "name": "Hello World 2",
  "url": "http://test.com"
}
```
J'obtiens ça en GET:
```
{
  "@id": "http://localhost:3000/ldp/as:Note/c4006940",
  "@type": "as:Note",
  "name": [
    "Hello World 2",
    "Hello World"
  ],
  "url": "http://test.com",
}
```
Donc l'URL est bien enregistré mais le nom est enregistré en double.

2020-01-24 14:46 UTC, srosset81 commented
Oops il ne fallait peut-être pas reviewer ? J'ai pas fait attention au label `not ready`

2020-01-27 21:48 UTC, simonLouvet commented
C'etait not ready mais ta review me rend bien service, je n'avais pas vu cet effet de bord. Merci @srosset81

2020-01-28 14:39 UTC, srosset81 approved these changes
Marche nickel ! :+1:

2020-01-28 14:39 UTC, merged