Key Management Refactoring
assemblee-virtuelle/semapps pull request #1247
Opened 2024-05-02 17:16 UTC by Laurin-W

## Controlled Container Dereference Mixin
This is a mixin for controlled containers. You can add it and specify a `dereferencePlan`. Properties specified in the dereference plan are resolved and attached to the object requested by a `get` action. We use this, to dereference keys in the webId resource which are now just stored as triples in the form `<webId> <sec:publicKey> <public key URI>`.

## Key Services
The old `keypair` service remains for now but after migration (which needs to be done manually), the service actions redirect to the new key service. Before migration, the new key service is not usable.
The new service stores keys in a `/key` container and public keys in a `/public-key` container. This makes pod export easier, allows authorized clients to manage keys, and to do client-side signing.

The new service supports both RSA and ed25519 keys.

---
I created documentation for the services (see the `.md` files).

- [x] Semapps unit tests are running through,
- [ ] though for some reasons, I can't run unit tests on APods right now (branch independent), so I couldn't check yet.

---
Since there are quite a lot of code changes and dev capacity issues, unit test coverage is good and I did a self-review already, I think focusing review on the new keys and key-container services, as well as the dereference mixing, would be okay.

If someone could independently review the documentation, that would be awesome :)

2024-05-02 17:27 UTC, Laurin-W commented on src/middleware/packages/webacl/services/resource/actions/addRights.js
>        }
I commented that out since it did have no effect. How should we go about this?

2024-05-07 12:55 UTC, srosset81 requested changes
Thanks a lot for the extensive work ! Here's an initial review, without testing yet. I will complete it later on.
The developer experience for the migration seems very good, but I would suggest that on a future version of SemApps (maybe 1.0.0) we drop all this migration code, to make it lighter.
In the PR description could you please add:
- The migration instructions
- List the breaking changes, including the changes to the WebIdService
Thanks a lot !

2024-05-07 12:55 UTC, srosset81 commented on src/middleware/packages/crypto/keys/key-service.js
> +  name: 'keys',
We need some consistency on naming. The file name is `key-service.js`, the name of the object is `KeyService`, but the name of the service is `keys`. I would suggest to use a plural everywhere, except for the container name.

2024-05-07 12:55 UTC, srosset81 commented on src/middleware/packages/crypto/keys/key-service.js
> +        );
Hmm if you called `keys.container.list` without `webId: 'system'`, you wouldn't need this right ?

2024-05-07 12:55 UTC, srosset81 commented on src/middleware/packages/crypto/utils.js
> +};
In the `ldp` package, this same function is called `arrayOf`. To avoid confusion, I would use the same name.

2024-05-07 12:55 UTC, srosset81 commented on src/middleware/packages/crypto/keys/keys-container.js
> +    }),
To improve security and prevent mistakes, we could throw an error if `webId` is "anon" or "system".

2024-05-07 12:55 UTC, srosset81 commented on src/middleware/packages/crypto/keys/public-keys-container.js
> +      delete: 'keys.public-container.delete'
PUT and PATCH should call the `keys.public-container.forbidden` action.
For `delete`, it is not necessary to indicate the action name.

2024-05-07 12:55 UTC, srosset81 commented on src/middleware/packages/crypto/keys/public-keys-container.js
> +    },
You should use the `resourceUri` as the param name, as this is the param that will be used by the `LdpApiService`. For consistency, it's generally better to keep the same param names for all services using the ControlledContainerMixin.
(For information, you could have used a "after hook" instead.)

2024-05-07 12:55 UTC, srosset81 commented on src/middleware/packages/crypto/signature/keypair.js
> +        }
The `getWebIdKeys` already create a key if it is not present, so I don't think it's necessary.
But maybe this mistake shows that either (1) `getWebIdKeys` should not create a key if not present or (2) it should be renamed to `getOrCreateWebIdKeys` to clarify what it does.

2024-05-07 12:55 UTC, srosset81 commented on src/middleware/packages/crypto/keys/migration-service.js
> +        });
Note: updating directly the triple store would usually require to delete the Redis cache for the webId, but since you are attaching the new public key just after this, it is not necessary.

2024-05-07 12:55 UTC, srosset81 commented on src/middleware/packages/crypto/signature/service.js
> +      // const [{ privateKeyPem }] = await ctx.call('keys.getWebIdKeys', { webId: actorUri, keyType: KEY_TYPES.RSA });
Remove this line ?

2024-05-07 12:55 UTC, srosset81 commented on src/middleware/packages/webid/service.js
> +    acceptedTypes: Object.values(FULL_ACTOR_TYPES),
According to the specs, the WebID is only required to be a `foaf:Person`. I would not mix this with the ActivityStreams ontology since this service is independant from the ActivityPubService.

2024-05-07 12:55 UTC, srosset81 commented on src/middleware/packages/webid/service.js
> +    path: '/',
I would rather use `/foaf/person` as the default path.

2024-05-07 12:55 UTC, srosset81 commented on src/middleware/packages/pod/service.js
> +          async create(ctx) {
Isn't the action called `createWebId` ?

2024-05-07 12:55 UTC, srosset81 commented on src/middleware/packages/webacl/services/resource/actions/addRights.js
>        }
I think it can be removed. We shouldn't throw errors if a resource is created without any permission. Niko forbid this because in "regular" SemApps instance, a resource without any permission cannot be created. But in ActivityPods, the user has full rights on all the resources so it's not a problem.

2024-05-07 12:55 UTC, srosset81 commented on src/middleware/packages/webid/service.js
>          });
FYI if you use `this.actions.post` instead of calling `ldp.container.post`, the containerUri will be automatically guessed from the path (using the `ldp.registry.getUri` action).

2024-05-07 12:55 UTC, srosset81 commented on src/middleware/packages/crypto/keys/migration-service.js
> +      ctx.broker.logger.info('=== Keys migration completed ===');
```suggestion
      this.logger.info('=== Keys migration completed ===');
```

2024-05-07 12:55 UTC, srosset81 commented on src/middleware/packages/crypto/keys/migration-service.js
> +    settingsDataset: 'settings',
This setting is not used

2024-05-07 12:55 UTC, srosset81 commented on src/middleware/packages/crypto/keys/key-service.js
> +    settingsDataset: 'settings',
The settingsDataset setting is not used

2024-05-07 15:17 UTC, Laurin-W commented on src/middleware/packages/crypto/keys/public-keys-container.js
> +    },
Do you think it should be named `resourceUri` through all of the key service?

2024-05-07 15:21 UTC, Laurin-W commented on src/middleware/packages/crypto/signature/keypair.js
> +        }
Thanks, I'll rename it to `getOrCreateWebIdKeys`. I think that it improves dev experience to not having to check, if those keys exist :)

2024-05-07 16:09 UTC, Laurin-W commented on src/middleware/packages/crypto/keys/key-service.js
> +        );
Thanks, I think I was having a hanger there :)

2024-05-08 08:18 UTC, srosset81 commented on src/middleware/packages/crypto/keys/public-keys-container.js
> +    },
No, not necessarily. Only the actions that are defined by the ControlledContainerMixin and that are overwritten by the service, like the delete action above. What the action does can change, but the params should be the same.

2024-05-08 10:31 UTC, Laurin-W commented on src/middleware/packages/webid/service.js
> +    acceptedTypes: Object.values(FULL_ACTOR_TYPES),
I had removed that and forgot to add that to the pod service -- caused me a looot of time to debug issues with "post to inbox failed - inbox not found" errors (I don't quite understand how that relates though..).

2024-06-10 13:16 UTC, srosset81 approved these changes
Tested again the key migration, works great now !
I'll let you merge.

2024-06-11 08:26 UTC, merged