SPARQL EndPoint init
assemblee-virtuelle/semapps pull request #134
Opened 2020-02-03 23:43 UTC by simonLouvet

resolve #47 

usage :

GET http://host:port/sparql?query=CONSTRUCT { ?s ?p ?o} WHERE { ?s ?p ?o }

OU

GET http://host:port/sparql
body
CONSTRUCT { ?s ?p ?o} WHERE { ?s ?p ?o }

Usage basique supporté mais sans doute plusieurs usages avec des dysfonctionnements

2020-02-04 17:15 UTC, srosset81 requested changes

2020-02-04 17:15 UTC, srosset81 commented on src/middleware/boilerplates/runner/createServices.js
> +  console.log('SparqlEndpointService', SparqlEndpointService);
console.log

2020-02-04 17:15 UTC, srosset81 commented on src/middleware/packages/sparqlEndPoint/service.js
> +              `,
Pour une requête SparQL définie par l'utilisateur, est-ce vraiment pertinent de prédéfinir les préfixes ? Il y a des risques de conflits il me semble, et l'utilisateur ne saura pas pourquoi sa requête a échoué.
En plus les ontologies sont définies au niveau du middleware, mais un frontend n'aura pas moyen de savoir quelles ontologies ont été définie.

2020-02-04 17:15 UTC, srosset81 commented on src/middleware/packages/sparqlEndPoint/routes.js
> +    const data = await getData;
Comment ce n'est pas une fonction mais une promesse, peut-être l'appeler `getDataPromise` ?
Là je trouve que ça porte à confusion.
Sinon créer une fonction qui retourne la promesse.

2020-02-05 08:32 UTC, simonLouvet commented on src/middleware/packages/sparqlEndPoint/service.js
> +              `,
je suis d'accord, pas de prefix prédéfinis, c'est au client de les fournir

2020-02-05 08:32 UTC, simonLouvet commented on src/middleware/packages/sparqlEndPoint/routes.js
> +    const data = await getData;
ok

2020-02-05 09:53 UTC, srosset81 approved these changes

2020-02-05 18:55 UTC, nikoPLP approved these changes

2020-02-05 20:24 UTC, merged