SPARQL front search
assemblee-virtuelle/semapps pull request #159
Opened 2020-02-21 03:50 UTC by simonLouvet

j'ai remplacé les container par des requettes SPARQL.

2020-02-26 15:35 UTC, simonLouvet commented
@srosset81 je n'ai pas réussi à passer la requête sparql en GET même avec encodeUri.

2020-02-26 17:40 UTC, srosset81 requested changes
Problèmes généraux:
-La recherche retourne un résultat sans aucune donnée visible s'il y a plus qu'un résultat (par exemple en mettant `http` si plusieurs ressources ont une adresse web).
![Capture d’écran de 2020-02-26 18-30-51](https://user-images.githubusercontent.com/17931931/75371106-76e96e80-58c6-11ea-9697-ff73bc69ed1b.png)
L'endpoint SPARQL ne retourne pas tous les résultats (notamment pas le label)
![Capture d’écran de 2020-02-26 18-35-18](https://user-images.githubusercontent.com/17931931/75371314-d182ca80-58c6-11ea-8ecd-79979a28ad53.png)
- Lorsqu'on change de page (Projects -> Utilisateurs), il faut soit réinitialiser le moteur de recherche, soit afficher des résultats en fonction de ce qui est dans l'input. A priori je serai plutôt pour la première solution.
- Pas mal d'autres problèmes restent ci-dessous. Je ne sais pas trop quoi te dire, il faut bien comprendre ce qui se passe et faire les choses méthodiquement.

2020-02-26 17:40 UTC, srosset81 commented on src/frontend/src/api/reducer.js
> +    );
Cela peut être simplifié comme ça:
```
return (
      (type === 'graph' && data['@graph']) ||
      data['@type'] === type ||
      data['type'] === type ||
      (Array.isArray(data['@type']) && data['@type'].includes(type)) ||
      (Array.isArray(data['type']) && data['type'].includes(type))
    );
```

2020-02-26 17:40 UTC, srosset81 commented on src/frontend/src/pages/ResourcesListPage.js
> +  }, [type]);
:+1: 
C'est effectivement la bonne manière de gérer un changement de props.

2020-02-26 17:40 UTC, srosset81 commented on src/frontend/src/pages/ResourcesListPage.js
> +        {resourceConfig && !resourceConfig.readOnly && (
`resourceConfig` devrait toujours être un objet valide, si ce n'est pas le cas tu as un problème.
A mon avis il manque une valeur par défaut du typeState:
```
const [typeState, setTypeState] = useState(type);
```

2020-02-26 17:40 UTC, srosset81 commented on src/frontend/src/pages/ResourcesListPage.js
> +  }, [type]);
Par contre une fois que tu utilises useEffect, ça devient inutile d'enregistrer un `typeState`, à chaque rendu du composant, la valeur du props `type` sera toujours la bonne (tu peux vérifier en mettant un `console.log(type)` tout en haut de la fonction)

2020-02-26 17:40 UTC, srosset81 commented on src/middleware/packages/sparql-endpoint/service.js
> +        accept: ctx.params.accept || ctx.meta.headers.accept
Il faudrait supprimer la méthode `getAcceptHeader` si tu ne l'utilises plus.

2020-02-26 17:40 UTC, srosset81 commented on src/frontend/src/api/useQuery.js
> +  });
Pour moi ce code est incompréhensible.
A comparer avec la version originale...

2020-02-26 17:40 UTC, srosset81 commented on src/frontend/src/pages/ResourcesListPage.js
> +  const validType = type === typeState;
Pour moi ce `validType` ressemble furieusement à un "hack" :-)
Si tu ne l'utilises pas, tu as une erreur, mais c'est parce que la donnée retournée par Redux (`data`), en changeant de page, correspond à celles de l'ancienne page. Il faut gérer ça mieux...

2020-02-26 17:40 UTC, srosset81 commented on src/frontend/src/api/reducer.js
> +            data: action.onlyArray ? [action.data['@id']] : action.data,
Si SPARQL ne retourne qu'une seule valeur, il y a moyen d'enregistrer les données correctement simplement en analysant ces données, quitte à remplacer `action.uri` (ci-dessus) par l'ID de la ressource...

2020-02-26 22:18 UTC, simonLouvet commented on src/frontend/src/api/reducer.js
> +    );
++

2020-02-26 22:20 UTC, simonLouvet commented on src/frontend/src/api/reducer.js
> +            data: action.onlyArray ? [action.data['@id']] : action.data,
Peux tu être plus précis stp. Analyser ces données ou? action.uri dans ce cas est l'API sparql, je ne voie pas le rapport.

2020-02-26 22:23 UTC, simonLouvet commented on src/middleware/packages/sparql-endpoint/service.js
> +        accept: ctx.params.accept || ctx.meta.headers.accept
++

2020-02-26 22:32 UTC, simonLouvet commented
> * Pas mal d'autres problèmes restent ci-dessous. Je ne sais pas trop quoi te dire, il faut bien comprendre ce qui se passe et faire les choses méthodiquement.

Je te demande d'éviter ce genre de commentaire stp. J'y ai passé plus de 20H à essayer de trouver une solution qui marche avec le plus de méthode possible, le plus minimaliste possible et en refusant la solution de repartir sans les mécaniques (useQuery) que tu as réalisés  pour mutualiser un maximum. Si j'en suis arrivé à ces solutions c'est que je n'ai pas trouvé de solutions plus simples. Je vais continué à tenter de simplifier. J'ai vu le bug de réinitialisation du input au changement de page. Je l'ai laissé passé à tort. j'avais pas vu le bug (http+label) qui ne s'était pas produit lors des tests.

2020-02-26 22:58 UTC, simonLouvet commented on src/frontend/src/pages/ResourcesListPage.js
> +  }, [type]);
Le problème c'est que ```type``` contient le nouveaux type mais que les data contiennent les datas de du composant avant son changement de props. Il est donc nécessaire de conserver le type de l'écran d'avant pour que le resourcePreview qui va être appelé avant le useEffect avec les données de l'écran d'avant soit bien appelé avec le bon type pour ne pas planter. Le useEffect met à jour le body et le typeState ce qui va forcer le useQuery  à recalculer les données et le rendu utilisera alors le useState modifié avec les données modifiées. Je n'ai pas trouvé d'autre solutions avec des heures de recherches et d'essais divers. Si tu as mieux propose sur une autre branche.

2020-02-26 22:59 UTC, simonLouvet commented on src/frontend/src/pages/ResourcesListPage.js
> +        {resourceConfig && !resourceConfig.readOnly && (
++

2020-02-26 22:59 UTC, simonLouvet commented on src/frontend/src/pages/ResourcesListPage.js
> +  const validType = type === typeState;
++

2020-02-26 23:00 UTC, simonLouvet commented on src/frontend/src/api/useQuery.js
> +  });
je vais essayé de le simplifier/commenter

2020-02-26 23:01 UTC, simonLouvet commented
> * Lorsqu'on change de page (Projects -> Utilisateurs), il faut soit réinitialiser le moteur de recherche, soit afficher des résultats en fonction de ce qui est dans l'input. A priori je serai plutôt pour la première solution.

++ première solution

2020-02-26 23:02 UTC, simonLouvet commented
> -La recherche retourne un résultat sans aucune donnée visible s'il y a plus qu'un résultat (par exemple en mettant `http` si plusieurs ressources ont une adresse web).
> ![Capture d’écran de 2020-02-26 18-30-51](https://user-images.githubusercontent.com/17931931/75371106-76e96e80-58c6-11ea-9697-ff73bc69ed1b.png)
> L'endpoint SPARQL ne retourne pas tous les résultats (notamment pas le label)
> ![Capture d’écran de 2020-02-26 18-35-18](https://user-images.githubusercontent.com/17931931/75371314-d182ca80-58c6-11ea-8ecd-79979a28ad53.png)

Je vais regardé ce bug que n'avais pas encore eu

2020-02-27 08:33 UTC, srosset81 commented on src/frontend/src/api/reducer.js
> +            data: action.onlyArray ? [action.data['@id']] : action.data,
Tu pourrais comparer `action.uri` et `action.data['@id']` et, s'ils sont différents, en déduire qu'il s'agit d'un résultat SPARQL ? Il faudrait bien commenter ça pour qu'on puisse comprendre de quoi il s'agit. L'avantage serait de ne pas contraindre à passer un paramètre qui a peu de sens.

2020-02-27 08:36 UTC, srosset81 commented on src/frontend/src/pages/ResourcesListPage.js
> +  }, [type]);
J'ai compris que c'était un "hack" de ce genre, mais il y a d'autres solutions, je peux le dire. Après pour proposer une solution expliquée, il faudrait que je me plonge là-dedans...

2020-02-27 08:44 UTC, srosset81 commented
> > * Pas mal d'autres problèmes restent ci-dessous. Je ne sais pas trop quoi te dire, il faut bien comprendre ce qui se passe et faire les choses méthodiquement.
> 
> Je te demande d'éviter ce genre de commentaire stp. J'y ai passé plus de 20H à essayer de trouver une solution qui marche avec le plus de méthode possible, le plus minimaliste possible et en refusant la solution de repartir sans les mécaniques (useQuery) que tu as réalisés pour mutualiser un maximum. Si j'en suis arrivé à ces solutions c'est que je n'ai pas trouvé de solutions plus simples. Je vais continué à tenter de simplifier. J'ai vu le bug de réinitialisation du input au changement de page. Je l'ai laissé passé à tort. j'avais pas vu le bug (http+label) qui ne s'était pas produit lors des tests.

Mon commentaire était un conseil, pas une critique, je te l'assure.
Personnellement, si j'avais su que tu passerais 20 heures là-dessus, j'aurais proposé qu'on fasse les choses différemment. Il faudra qu'on en reparle. Cette story était sans doute trop compliquée pour quelqu'un qui débute dans React...
En tout cas, si le code n'est pas clair, s'il contient des "hacks", il n'est pas acceptable pour moi et je suis obligé d'encourager à plus de rigueur. J'ai passé presque 1h30 sur le review, à essayer de comprendre ce que tu as fait, à analyser les problèmes et à trouver des suggestions utiles. Mais il y a des limites et, à partir d'un moment, tout ce que je peux dire c'est "Essaie de faire mieux", sans critique ni jugement.

2020-02-27 08:50 UTC, simonLouvet commented on src/frontend/src/api/reducer.js
> +            data: action.onlyArray ? [action.data['@id']] : action.data,
je voie mieux, je regarde

2020-02-27 14:29 UTC, simonLouvet commented
> > -La recherche retourne un résultat sans aucune donnée visible s'il y a plus qu'un résultat (par exemple en mettant `http` si plusieurs ressources ont une adresse web).
> > ![Capture d’écran de 2020-02-26 18-30-51](https://user-images.githubusercontent.com/17931931/75371106-76e96e80-58c6-11ea-9697-ff73bc69ed1b.png)
> > L'endpoint SPARQL ne retourne pas tous les résultats (notamment pas le label)
> > ![Capture d’écran de 2020-02-26 18-35-18](https://user-images.githubusercontent.com/17931931/75371314-d182ca80-58c6-11ea-8ecd-79979a28ad53.png)
> 
> Je vais regardé ce bug que n'avais pas encore eu

résolu

2020-02-27 14:30 UTC, simonLouvet commented
> > -La recherche retourne un résultat sans aucune donnée visible s'il y a plus qu'un résultat (par exemple en mettant `http` si plusieurs ressources ont une adresse web).
> > ![Capture d’écran de 2020-02-26 18-30-51](https://user-images.githubusercontent.com/17931931/75371106-76e96e80-58c6-11ea-9697-ff73bc69ed1b.png)
> > L'endpoint SPARQL ne retourne pas tous les résultats (notamment pas le label)
> > ![Capture d’écran de 2020-02-26 18-35-18](https://user-images.githubusercontent.com/17931931/75371314-d182ca80-58c6-11ea-8ecd-79979a28ad53.png)
> 
> Je vais regardé ce bug que n'avais pas encore eu

résolu

2020-02-27 14:30 UTC, simonLouvet commented
> > * Lorsqu'on change de page (Projects -> Utilisateurs), il faut soit réinitialiser le moteur de recherche, soit afficher des résultats en fonction de ce qui est dans l'input. A priori je serai plutôt pour la première solution.
> 
> ++ première solution

résolu

2020-02-27 14:30 UTC, simonLouvet commented
> > -La recherche retourne un résultat sans aucune donnée visible s'il y a plus qu'un résultat (par exemple en mettant `http` si plusieurs ressources ont une adresse web).
> > ![Capture d’écran de 2020-02-26 18-30-51](https://user-images.githubusercontent.com/17931931/75371106-76e96e80-58c6-11ea-9697-ff73bc69ed1b.png)
> > L'endpoint SPARQL ne retourne pas tous les résultats (notamment pas le label)
> > ![Capture d’écran de 2020-02-26 18-35-18](https://user-images.githubusercontent.com/17931931/75371314-d182ca80-58c6-11ea-8ecd-79979a28ad53.png)
> 
> Je vais regardé ce bug que n'avais pas encore eu

résolu

> > * Lorsqu'on change de page (Projects -> Utilisateurs), il faut soit réinitialiser le moteur de recherche, soit afficher des résultats en fonction de ce qui est dans l'input. A priori je serai plutôt pour la première solution.
> 
> ++ première solution

résolu

2020-02-27 15:52 UTC, simonLouvet commented on src/frontend/src/api/reducer.js
> +            data: action.onlyArray ? [action.data['@id']] : action.data,
++ ca fonctionne bien mais par contre c'est un peut obscure comme comparaison pour de la maintenance.

2020-02-27 15:53 UTC, simonLouvet commented on src/frontend/src/api/useQuery.js
> +  });
pas trouvé mieux mais commentaire

2020-03-03 09:24 UTC, srosset81 approved these changes

2020-03-03 09:25 UTC, merged