126 ldp test integration
assemblee-virtuelle/semapps pull request #187
Opened 2020-03-18 18:16 UTC by simonLouvet

resolve #126

2020-03-18 18:28 UTC, simonLouvet commented
@srosset81 & @nikoPLP J'ai commencé deux type de test d'intégration
une série haut niveau (express+api+ldp+triplestore);
une série bas niveau (ldp+triplestore);

J'ai fait cela en s’étant entretenu avec seb avant pour se mettre d'accord. La série haut niveau n'a pas vocation à être exhaustive mais vérifier que tout est bien branché pour répondre à des requêtes http. La série bas niveau à vocation à être exhaustive pour répondre à tous les cas de figure.

preneur de vos retours pour continuer mais je peux faire sans.

2020-03-19 08:53 UTC, srosset81 commented
@simonLouvet Cela me semble bien, rien à redire pour le moment ! :-)

2020-03-23 20:36 UTC, simonLouvet commented
les couches LDP ne supportent pas encore le POSt et PATCH avec des data en TRIPLE  ou ou TURTLE. issues à créer

2020-03-24 08:18 UTC, srosset81 requested changes
Top ! Quelques petites corrections et suggestions mineurs ci-dessous.

2020-03-24 08:18 UTC, srosset81 commented on src/middleware/tests/ldp/ldp.test.js
> +    });
Est-ce que la variable `meta` est nécessaire ?

2020-03-24 08:18 UTC, srosset81 commented on src/middleware/tests/ldp/ldp.test.js
> +    });
`Projects` -> `projects`

2020-03-24 08:18 UTC, srosset81 commented on src/middleware/tests/ldp/ldp.test.js
> +    console.log(MIME_TYPES);
console.log

2020-03-24 08:18 UTC, srosset81 commented on src/middleware/tests/ldp/ldp.test.js
> +    let regex = new RegExp(`<${projet1['@id']}>`);
La variable `regex` n'est pas utilisée.

2020-03-24 08:18 UTC, srosset81 commented on src/middleware/tests/ldp/ldp.test.js
> +        accept: 'applicaiton/ld+json',
`applicaiton` -> `application`
... ou plutôt utiliser la constante MIME_TYPES :-)
Il y a 3-4 autres endroits où tu pourrais utiliser les MIME_TYPES.

2020-03-24 08:18 UTC, srosset81 commented on src/middleware/tests/ldp/ldp.test.js
> +        accept: 'applicaiton/ld+json',
Bizarre d'ailleurs que les tests ont passé avec cette erreur...

2020-03-24 08:18 UTC, srosset81 commented on src/middleware/tests/ldp/ldp_api.test.js
> +      baseUrl: CONFIG.HOME_URL + 'ldp/',
Si tu mets un `baseUrl` avec la valeur `/ldp/`, je pense que tu pourras éviter de faire `projet1['@id'].replace(CONFIG.HOME_URL, '/')` non ?

2020-03-24 08:35 UTC, simonLouvet commented on src/middleware/tests/ldp/ldp.test.js
> +    });
non, elle me servait avant pour récupérer le ctx. je la vire.

2020-03-24 08:35 UTC, simonLouvet commented on src/middleware/tests/ldp/ldp.test.js
> +    });
ok

2020-03-24 09:27 UTC, simonLouvet commented on src/middleware/tests/ldp/ldp.test.js
> +    let regex = new RegExp(`<${projet1['@id']}>`);
++

2020-03-24 09:27 UTC, simonLouvet commented on src/middleware/tests/ldp/ldp_api.test.js
> +      baseUrl: CONFIG.HOME_URL + 'ldp/',
non par ce qu'il y  a le slug. le replace c'est juste pour le supertest qui prend l'url relative et non l'url absolue

2020-03-24 09:27 UTC, simonLouvet commented on src/middleware/tests/ldp/ldp.test.js
> +        accept: 'applicaiton/ld+json',
par ce que les type sont testé sur une couche plus base que la détection de l’existence (404)

2020-03-24 09:50 UTC, srosset81 approved these changes

2020-03-24 09:53 UTC, merged