webId called ldp with bad prameters
assemblee-virtuelle/semapps pull request #190
Opened 2020-03-20 13:33 UTC by simonLouvet

resolve #185

2020-03-20 14:58 UTC, simonLouvet commented
@srosset81 il y a un test sur activitypub qui ne passe pas. Je suppose que cela vient des nouveaux paramètre du ldp post (uri+slug). Tu regardes?

2020-03-20 16:49 UTC, srosset81 commented
@simonLouvet C'est bon, j'ai fixé sur `master` et mergé sur ta branche.

2020-03-20 16:59 UTC, simonLouvet commented
@srosset81 parfait, il ne reste plus que ta review pour merge ce bugfix

2020-03-20 17:06 UTC, srosset81 requested changes

2020-03-20 17:06 UTC, srosset81 commented on src/middleware/tests/webId/webId.test.js
> +    }
Le mieux serait d'effacer toutes les données du triple store dans le `beforeAll`.
Il y a une action `triplestore.dropAll` qui permet de faire ça facilement.

2020-03-20 22:35 UTC, simonLouvet commented on src/middleware/tests/webId/webId.test.js
> +    }
ok

2020-03-21 15:27 UTC, simonLouvet commented
@srosset81 j'ai suivi ta préco

2020-03-24 08:01 UTC, srosset81 approved these changes

2020-03-24 08:01 UTC, merged

2020-03-24 08:19 UTC, srosset81 commented
@simonLouvet Désolé j'ai mergé ta PR, alors j'aurai dû te laisser le faire !

2020-03-24 08:33 UTC, simonLouvet commented
@srosset81 : pas de soucis, on va s'y faire à nos process :-)