Docs / How to document
assemblee-virtuelle/semapps pull request #227
Opened 2020-04-14 15:41 UTC by srosset81

Je remets ici le travail de Guillaume, qui avait été accidentellement mergé sur master.

Les commentaires de Gabriel sont toujours visibles ici: https://github.com/assemblee-virtuelle/semapps/pull/204

@GuillaumeAV et @ReX-AV-Gab je vous laisse vous coordonner pour finaliser cette PR, notamment en ajoutant un lien dans la sidebar. Une fois que ce sera fait, vous pourrez me mettre comme reviewer.

2020-04-17 14:38 UTC, GuillaumeAV requested changes

2020-04-17 14:38 UTC, GuillaumeAV commented on website/docs/participate/documentation.md
> +
## Schéma général
- Tant qu'il n'y a pas eu de décision / consentement du cercle documentation : **On renseigne une issue**
- Si le contenu de ce qu'on veut publier est à l'état d'ébauche ou au stade de brouillon : **On renseigne une issue**
- Lorsque notre proposition de contribution a obtenu l'aval du groupe documentation, et qu'elle nous semble aboutie, on pousse une pull request.

2020-04-17 14:38 UTC, GuillaumeAV commented on website/docs/participate/documentation.md
> +  title: [le titre de votre page]
title: [le titre-de-votre-page]

2020-05-13 14:09 UTC, GuillaumeAV approved these changes
Ok pour moi !

2020-05-13 14:11 UTC, GuillaumeAV commented
Yop ! 
@srosset81 je viens d'approuver la PR et Gab qui est au tel avec moi, l'approuve aussi, tu merges du coup ? La bise !

2020-05-13 16:50 UTC, srosset81 reviewed
Comme j'ai créé cette PR, je ne peux pas la reviewer mais voici mes commentaires.
Remarque générale: n'avez-vous pas décidé entre temps d'écrire toute la doc externe en anglais ?

2020-05-13 16:50 UTC, srosset81 commented on website/docs/participate/documentation.md
> +- Nous utilisons https://docusaurus.io/ pour documenter le projet SemApps. Docusaurus permet de générer une documentation à partir de Github :
https://v2.docusaurus.io ... et je mettrai des jolis liens

2020-05-13 16:50 UTC, srosset81 commented on website/docs/participate/documentation.md
> +- Aujourd'hui le docusaurus de SemApps est hébergé sur https://website-3rr9j6b6k.now.sh/ ;
La version temporaire est plutôt http://doc.semapps.org/

2020-05-13 16:50 UTC, srosset81 commented on website/docs/participate/documentation.md
> +  - On y trouve les pages apparaissant dans la sidebar
dans **les** sidebars, car on peut définir plusieurs sidebars.

2020-05-13 16:50 UTC, srosset81 commented on website/docs/participate/documentation.md
> +- Lorsque notre proposition de contribution nous semble aboutie, **on sollicite ue review**.
Une review. Et au dessus: **a** obtenu.
(Merci de relire attentivement une PR avant de la soumettre à review, cela facilite le travail)

2020-05-13 16:50 UTC, srosset81 commented on website/docs/participate/documentation.md
> +NB : Lorsque que le fichier a été créé par un autre et en fonction du contexte, vous pouvez soit éditer la page, soit cliquer sur les signes "+" à gauche du texte pour ajouter des commentaires ...
Ajouter un commentaire en cliquant sur le signe "+" à gauche de la ligne est pertinent surtout pour des reviews, je ne sais pas si je le mettrai ici.

2020-05-13 16:50 UTC, srosset81 commented on website/docs/participate/documentation.md
> +  title: [le-titre-de-votre-page]
Le titre de la page peut avoir des espaces. C'est le nom du fichier `.md` qui ne doit pas avoir d'espaces, et être plutôt en minuscules.

2020-05-19 14:09 UTC, merged