bootstrap in docker
assemblee-virtuelle/semapps pull request #258
Opened 2020-05-04 22:28 UTC by simonLouvet

2020-05-05 08:03 UTC, srosset81 commented
@srosset81 Des informations sur le but de cette PR ? Elle est terminée ? Elle est en lien avec https://github.com/assemblee-virtuelle/semapps/issues/257 et les problèmes soulevés dans https://github.com/assemblee-virtuelle/semapps/pull/253 ? Merci de mettre des titres clairs, avec si possible une description.

2020-05-05 08:45 UTC, simonLouvet commented
> @simonLouvet Des informations sur le but de cette PR ? Elle est terminée ? Elle est en lien avec #257 et les problèmes soulevés dans #253 ? Merci de mettre des titres clairs, avec une description lorsque le titre ne suffit pas à expliquer tout ce qui est fait (et le français est autorisé !)

done, dsl

2020-05-05 12:54 UTC, srosset81 requested changes

2020-05-05 12:54 UTC, srosset81 commented on src/frontend/Dockerfile.dev
> +RUN npm bootstrap
Il manque le `run` (qui ne peut être omis que pour la commande start): `npm run bootstrap`
Cela ne va être lancé qu'au moment du build, pas pratique pour un Docker de dev. Je mettrai plutôt ça dans la commande de lancement (`command: npm run bootstrap && npm start --prefix ./${FRONTEND}`)

2020-05-05 12:54 UTC, srosset81 commented on src/frontend/packages/react-admin/package.json
> +  "version": "0.1.1",
Pourquoi avoir publié le package ?
Il n'était pas prêt, il faut ajouter un build pour que le code soit transpilé. Le packages NPM ne marchent que s'ils sont transpilés. On passe à côté de ça avec le bootstrap de Lerna mais c'est inutilisable en dehors de la config Lerna. J'aurai dû le préciser.

2020-05-05 13:02 UTC, simonLouvet commented on src/frontend/Dockerfile.dev
> +RUN npm bootstrap
++

2020-05-05 13:03 UTC, simonLouvet commented on src/frontend/packages/react-admin/package.json
> +  "version": "0.1.1",
par ce que j'en ai besoin pour dfc et 'autres projets.

2020-05-05 13:07 UTC, simonLouvet commented on src/frontend/packages/react-admin/package.json
> +  "version": "0.1.1",
Je me suis posé la même question pour la publication et puis je me suis dit que ce packet n'est destiné qu'a fonctionner avec le react-admin et que nous pouvons spécifier qu'il est à utiliser avec react-app-rewired. Totalement prêt à transpiler avant de publier? Est ce que cela bloque la PR?

2020-05-05 13:56 UTC, srosset81 commented on src/frontend/packages/react-admin/package.json
> +  "version": "0.1.1",
Non c'est pas bloquant :-) Je suis en train de voir pour faire ça maintenant.
Le build est nécessaire pour des packages NPM publiés. On passe par react-app-rewired pour le développement, afin de pouvoir coder sans avoir besoin de builder à chaque fois.

2020-05-08 17:53 UTC, simonLouvet commented
obsolete avec les nouvelles versions de front

2020-05-08 17:53 UTC, closed without merging