246 refactoring sparql endpoint + web
assemblee-virtuelle/semapps pull request #271
Opened 2020-05-16 01:55 UTC by simonLouvet

resolve #246 

mise en commun des middlware à exécuter avant les actions pour sparqlendpoint et webid en repartant de la logique appliqué à LDP

2020-05-18 13:30 UTC, srosset81 requested changes

2020-05-18 13:30 UTC, srosset81 commented on src/middleware/boilerplates/runner/services/ldp.service.js
> +    defaultAccept: 'application/ld+json',
Est-ce qu'on veut que le format par défaut soit du JSON-LD ? Je pensais que pour un serveur LDP, c'était plutôt turtle.

2020-05-18 13:30 UTC, srosset81 commented on src/middleware/packages/middlewares/index.js
>  };
Je trouve le code moins lisible et il est plus long. Quel intérêt de ce refacto ?

2020-05-18 13:30 UTC, srosset81 commented on src/middleware/packages/middlewares/index.js
>      if (req.$params.body) {
Tu as changé la variable pour `req.$ctx.meta.body` alors il faut adapter ici.
Perso je ne comprends pas pourquoi un `body` devrait entrer dans les `meta`...

2020-05-18 13:30 UTC, srosset81 commented on src/middleware/packages/middlewares/package.json
> +  "description": "Express Middlware for SemApps",
Middl**e**ware**s**

2020-05-18 13:30 UTC, srosset81 commented on src/middleware/packages/sparql-endpoint/getRoutes.js
> +        'POST /': [...middlewares, 'sparqlEndpoint.query']
Je croyais qu'en GET ça ne marchait pas ?

2020-05-18 13:30 UTC, srosset81 commented on src/middleware/packages/webid/getRoutes.js
> +        'GET usersss': [...middlewares, 'webid.list']
Trop de SSSsss dans `usersss`

2020-05-18 18:21 UTC, simonLouvet commented on src/middleware/packages/sparql-endpoint/getRoutes.js
> +        'POST /': [...middlewares, 'sparqlEndpoint.query']
si à condition qu'il n'y ai pas de '#' dans la query ce qui arrive très souvent si  prefix sont utilisés

2020-05-18 18:21 UTC, simonLouvet commented on src/middleware/packages/webid/getRoutes.js
> +        'GET usersss': [...middlewares, 'webid.list']
dsl, coquille de debugage

2020-05-18 18:21 UTC, simonLouvet commented on src/middleware/packages/middlewares/package.json
> +  "description": "Express Middlware for SemApps",
++

2020-05-18 18:23 UTC, simonLouvet commented on src/middleware/packages/middlewares/index.js
>  };
par ce que ca fonctionnait pas tout simplement pas : le next était appelé avant que le 'end' de data se soit produit. C'est peut être un cas qui ne se produit qu'avec le contenus bruts comme les request sparql.

2020-05-18 18:24 UTC, simonLouvet commented on src/middleware/boilerplates/runner/services/ldp.service.js
> +    defaultAccept: 'application/ld+json',
Bonne question aucun arbitrage n'a vraiment été fait sur le sujet.

2020-05-18 22:44 UTC, merged

2020-05-19 06:14 UTC, srosset81 commented on src/middleware/packages/sparql-endpoint/getRoutes.js
> +        'POST /': [...middlewares, 'sparqlEndpoint.query']
Du coup je proposerai de le supprimer, ça n'a pas vraiment d'intérêt.