wip
assemblee-virtuelle/semapps pull request #274
Opened 2020-05-16 05:05 UTC by simonLouvet

resolve #251 

@srosset81  : J'ai commencé le template dms. Ca à fonctionné pour  moi (dms lancé et branché à semapps). J'ai rien changé au code (PAIR) est ce que on fait des modifs?

Pour générer (en étant dans le répertoire frontend) : ```npx create-react-app ldms --template file:cra-template-ldms/```

Si c'est ok, il reste plus qu'a publier pour que ce Template soit accessible.

une bonne doc : https://medium.com/@alexgrischuk/how-to-create-custom-create-react-app-cra-templates-73a5196edeb

2020-05-18 13:13 UTC, srosset81 requested changes
@simonLouvet C'est difficile pour moi de reviewer si je ne sais pas où tu en es.
Il me semble qu'on avait dit qu'on gardait juste un type de ressource, par exemple un `foaf:Person`, qui irait dans un container `/resources` (le container par défaut). Dans une logique de template, je ne pense pas qu'il faut avoir autant de choses.

2020-05-18 13:13 UTC, srosset81 commented on src/frontend/cra-template-ldms/template/src/App.css
> +}
Tu peux supprimer ce fichier CSS qui n'est pas utilisé.

2020-05-18 13:14 UTC, srosset81 commented on src/frontend/cra-template-ldms/template/src/App.css
> +}
Il y a un autre fichier CSS inutilisé.

2020-05-18 14:27 UTC, srosset81 commented
@simonLouvet J'ai pas compris pourquoi tu as utilisé le terme `ldms` alors que partout dans le code on parle de `dms`. Je trouve `ldms` trop long, et si on veut changer le nom, il faudrait en discuter.

2020-05-19 09:10 UTC, simonLouvet commented
> @simonLouvet J'ai pas compris pourquoi tu as utilisé le terme `ldms` alors que partout dans le code on parle de `dms`. Je trouve `ldms` trop long, et si on veut changer le nom, il faudrait en discuter.

c'était essentiellement pour lancer la conversation à ce sujet :-). @GuillaumeAV a utilisé ldms dans plusieurs documentation (linked data management system) pour l'inclure dans écosystème du linked data. Je trouvais cela assez pertinent. pas de soucis pour revenir à dms.

2020-05-20 11:10 UTC, srosset81 commented on src/frontend/dms/package.json
> +    "@semapps/react-admin": "^0.1.3",
J'ai publié une nouvelle version de ce package ce matin (c'est sur master), je pense que tu dois passer à 0.1.4.
Par ailleurs, c'est mieux d'éviter de mettre le `^` car pour l'instant on a beaucoup de breaking changes à chaque mise à jour, et ça pourrait facilement casser le code.

2020-05-20 13:40 UTC, simonLouvet commented on src/frontend/dms/package.json
> +    "@semapps/react-admin": "^0.1.3",
ok

2020-05-20 14:22 UTC, merged