Create Code social (version résumée FR).md
assemblee-virtuelle/semapps pull request #442
Opened 2020-12-01 15:08 UTC by ValentineMathieu

Voici la PR associée à l'issue #440 

Pour la version détaillée du code social : PR ; Issue #441

2020-12-01 18:07 UTC, J9rem commented
Merci @ValentineMathieu de me proposer la revue.
étant arrivé récemment et n'ayant pas participé à la première rédaction de ce code social, il m'est difficile de faire une revue.
Comme je fais partie de l'équipe, il me paraît important de faire cette revue.
Avons-nous prévu un moment de présentation oral du contexte de cette ré-écriture ?
Ou peut-être ai-je raté ce moment ? Dans ce cas, je veux bien le lien vers le compte-rendu de la réunion de clarification sur le contexte de cette ré-écriture.

Merci d'avance et pour le travail associé.

2020-12-01 20:41 UTC, bouviermullerp commented
@J9rem un peu de contexte alors : 
Lors du lancement de SemApps il y un an et des brouettes, on avait choisi de tester YesWiki pour documenter le projet. Nous avons été plusieurs a y publier beaucoup d'informations, en mode publication libre. D'ailleurs, grâce aux doigts de fée de @srosset81 tu pourras trouver l'intégralité de ce qu'on avait écrit [ici](http://semappsoop.cluster028.hosting.ovh.net/?PagePrincipale)
Après quelques mois d'utilisation, on s'est rendu compte que l'outil ne collait pas à nos pratiques, et Seb a proposé docusaurus.
Nous n'avons migré toute la doc, car c'est trop dense et pas vraiment user friendly. L'intention est de s'inspirer de ce qu'il y avait pour ajouter des informations au docusaurus. 
Autre élément de contexte, se doter d'un code social est normalement une nécessité pour être un projet de l'AV.
Le code social que Valentine propose ici est basé sur une première proposition martyr à laquelle Guillaume et moi avions pas mal contribué si je me souviens bien, mais n'a jamais été validée formellement par l'ensemble de l'équipe (souci de temps, densité de l'information). De plus, nos pratiques, notre projet ont évolué, donc c'est sacrément obsolète.
J'espère que c'est plus clair, ravi de s'appeler s'il reste des questions en suspend.

2020-12-02 08:06 UTC, J9rem commented
Merci @bouviermullerp je comprends mieux pourquoi ça tombe comme un cheveu sur la soupe pour moi car je ne connaissais pas l'existence du YesWiki.

Il reste qu'avant même de commencer la relecture de ce "code social", je suis dans le besoin d'une "écoute du centre" qui se formaliserait par un tour de parole sur cette thématique lors d'une des réunions où il y a toute l'équipe (y compris @ValentineMathieu ).

C'est dommage de ne pas avoir aborder le sujet en réunion Gouvernance mercredi dernier.

2020-12-02 09:00 UTC, srosset81 commented
Ajoutons le point à l'ODJ de vendredi ?

2020-12-02 09:11 UTC, J9rem commented
Nickel, je verrai même une réunion dédiée.

2020-12-02 11:26 UTC, bouviermullerp commented
Comme vous préférez - réunion dédié ça peut être bien, en fait tout dépend de quoi on souhaite parler, ordre du jour. - si c'est seulement un tour de parole d'écoute au centre dont tu as besoin Jeremy, alors on peut surement le placer Vendredi - et organiser une réunion dédié si c'est pertinent
De la où je parle, la rédaction/mise à jour ne nécessite pas une grosse mobilisation car il s'agit de rendre visible/lisible nos pratiques actuelles, et éventuellement celles vers lesquelles ou souhaite tendre. J'aimerai être vigilant à ce que ça ne soit pas trop énergivore si possible - en tout cas respecter les besoins de chacun.

2020-12-02 11:34 UTC, J9rem commented
totalement ok avec une solution pas trop énergivore

2020-12-02 11:40 UTC, J9rem commented
Juste que je pose un point de vigilance, sur le fait que personnellement j'accorde de l'importance à un code social et je trouve que sa rédaction n'est pas une action légère. La gouvernance autour de sa rédaction aussi. Et en général, chose importante = temps à y consacrer.

2020-12-02 18:12 UTC, bouviermullerp commented
Mhhh :) d'ac - je n'ai aucune objection à ce que tu proposeras autour du code social - à priori :). A ce stade, je trouve que c'est un sujet aussi important que l'application que l'on développe et dont la méthode de co-production est github. Je suis très très favorable à essayer de co-écrire/valider le code social via github, c'est assez démocratique pour moi et c'est homogène avec nos pratiques.

2020-12-04 17:40 UTC, J9rem commented
Bon, il se trouve que nous n'avons pas eu l'espace pour en parler lors du la réunion revue de sprint de ce vendredi et a priori nous n'aurons pas plus l'espace à la réunion revue de sprint du 16/12.

Tout d'abord, je suis très content que @ValentineMathieu se propose de remettre à jour le contenu de ce texte.Toutefois, je trouve peu agréable de devoir corriger à froid, sans contexte des lignes qu'elles pourraient écrire, surtout qu'elle est dans le projet que depuis pas longtemps, ne lui permettant pas de connaître tout l'historique.
C'est pour ceci que je ne suis pas favorable à une relecture brut sur le canal "froid" qu'est Github de ce que va proposer @ValentineMathieu afin d'éviter de lui envoyer des messages qu'elles pourraient prendre comme négatifs alors qu'ils ne concernent que le contenu.

Enfin, je pose ici en conscience les liges suivantes car je vois que nous n'aurons pas des échanges d'équipe sur le sujet de suite et je ne peux me permettre de garder ce que je perçois.
C'est une perception et donc je serai reconnaissant à chacun de me guider vers le bon document qui me permettrait d'obtenir l'information qu'il me manque.

A priori, je ne vois pas la trace de la décision d'écrire un code social pour le projet SemApps sachant qu'il y en a déjà un pour l'Assemblée virtuelle. Si la décision a été prise avant mon arrivée dans l'équipe, je la suivrais mais si elle n'a pas été prise alors je préfère dire que je ne suis pas favorable car pour le moment nous n'en avons pas besoin dans l'immédiat (vu que nous avons celle de l'Assemblée virtuelle).

Ensuite, @bouviermullerp j'ai un autre point de vue sur la démocratie sur Github.
Github n'est qu'un outil de traçabilité de modification de code. Il ne définit en rien le processus de prise de décision des modifications.
A priori, nous n'avons pas écrit de processus de prise de décision concernant la présente PR (qui a le droit de faire des proposition ? comment gérons-nous les propositions contradictoires ? Qui a le pouvoir ou non de trancher en cas de désaccord non solvable ? etc)
A priori aussi (je répète je peux me tromper), nous  n'avons aucun rôle qui définit l'engagement d'être référent de la rédaction du code social et le cas échant d'être la personne tout indiquée pour animer la prise de décision associée.

Donc désolé, dans l'état actuel dont j'ai connaissance de nos décisions, je ne trouve pas Github démocratique pour la rédaction de ce code social.
(attention : je ne prends aucunement position concernant la démocratie de GitHub pour la rédaction du code d'un logiciel ou du contenu d'une page d'un site vitrine. Évitons donc les débats sur GitHub à cause de raccourcis de pensée, merci).

Donc, **je propose qu'avant de relire le présent code social, nous ayons un document, que nous pourrions rédiger avec Github, sur la prise de décision autour de ce code social et l'intention de cette PR et du code social associé (destination, valeur, diffusion, etc)**
Que pensez-vous de cette proposition ? @assemblee-virtuelle/semapps 

NB : n'ayant pas prévu l'arrivée de tel débat dans cette période, je ne me suis pas libéré suffisamment de temps pour la rédaction d'une proposition de prise de décision autour du code social. Et je suis désolé du bruit que ça occasionne car je m'en serai aussi passé, mais je n'arrive pas à rester observateur de cette PR sans réaction.

Pour rappel, je ne suis nullement en froid avec @ValentineMathieu qui de fait se retrouve malgré elle dans cette discussion.

2020-12-04 17:47 UTC, J9rem commented on Code social (version résumée FR).md
> +La modification de ce code social se fait sur la base du consentement lorsqu'un des membres du projet en fait la demande.
Je suis embêté car pour moi la prise de décision par consentement demande un tour de parole de clarification, une présentation de la proposition par le porteur de projet et un cadre de confiance pour les échanges.
J'identifie difficilement l'ensemble de ces éléments réunis au sein de cette PR en utilisant GitHub comme unique support.

2020-12-04 18:58 UTC, ReX-AV-Gab commented on Code social (version résumée FR).md
> +La modification de ce code social se fait sur la base du consentement lorsqu'un des membres du projet en fait la demande.
Avant de répondre à Jérémy, je serais heureux que l'on prenne le temps d'examiner ce que sa réaction révèle de notre fonctionnement, donc de faire de sa réaction une belle pépite quand bien même il aurait pris le risque de s'exposer et quand bien même il aurait sa part de responsabilité. Je vous en remercie sincèrement par avance.

2020-12-06 18:57 UTC, bouviermullerp commented on Code social (version résumée FR).md
> +La modification de ce code social se fait sur la base du consentement lorsqu'un des membres du projet en fait la demande.
Ce que tu illustres Jeremy est un processus qui permet de faciliter une décision par consentement, n'est ce pas ? La prise de décision par consentement ne nécessite pas - irrémédiablement - un tour de clarif + présentation.
Consentir, c'est ne pas être d'accord, mais accepter une décision. Pouvoir faire avec, n'est ce pas ? 
Je réponds de manière moins spécifique sur un autre fil.

2020-12-06 19:06 UTC, bouviermullerp commented
@J9rem merci d'avoir pris le temps et le soin de mettre en lumière ce que tu observes.
Je trouve que ce sujet met en lumière moultes questions intéressantes et complexes.
En guise d'introduction (et de conclusion) - je n'ai certainement pas la même perception des enjeux qui se cachent derrière le code social (posture peut être plus freestyle) mais votre attention à ce chapitre me donne de la joie et je suis heureux d'élever mon niveau d'attention, j'y consent, et je l'accepte ;)

Ce sujet m'invite à me demander : 
- Qui à la main pour accepter/refuser des PR ? Je crois qu'on n'est pas si au clair dans notre gouvernance. Il y a un rôle qualité de code mais qui n'a pas le rôle explicite de valide ou refuser les PR ?
- Quel relation entretenons nous avec le code social - en harmonie avec la remarque de Gabriel.

Nous n'avons pas demandé à @ValentineMathieu la méthode qu'elle souhaite utiliser. Peut être un qui pro quo d'ailleurs, Valentine tu as demandé la revue de cette issue, mais est-ce que tu considérais qu'elle était prête à être revue ? 
Car ce document ne reflète plus la réalité, est-ce que tu comptais faire quelques modifs ?

2020-12-07 07:12 UTC, bouviermullerp commented
@ValentineMathieu je retire cette carte du KanBan car on a décidé de ne pas mettre les PR dans le KanBan ;)

2020-12-07 09:11 UTC, srosset81 commented
> * Qui à la main pour accepter/refuser des PR ? Je crois qu'on n'est pas si au clair dans notre gouvernance. Il y a un rôle qualité de code mais qui n'a pas le rôle explicite de valide ou refuser les PR ?

C'est dans le périmètre du rôle Communication, qui est responsable du site web, sauf pour la partie documentation technique.

> * Quel relation entretenons nous avec le code social - en harmonie avec la remarque de Gabriel.

Je crois que nous avons décidé d'en parler lors de la prochaine réunion gouvernance.

2020-12-07 09:57 UTC, J9rem requested changes
merci @ValentineMathieu d'avoir fait ce gros premier travail de rédaction.
merci aussi d'avoir proposé à la validation cette PR.

Ne prends pas les remarques pour toi, elles sont destinées à faire évoluer le document.

2020-12-07 09:57 UTC, J9rem commented on Code social (version résumée FR).md
> +Le Code Social du projet a pour objectif de le décrire de manière exhaustive et systémique.
Si j'ai bien suivi, ce document a pour vocation à être publié sur le site internet.
Je suppose que parmi les potentiels lecteurs, plusieurs auront comme moi une interrogation sur ce qu'est un code social.
Est-ce qu'il ne serait pas plus judicieux d'ajouter un paragraphe d'introduction sur la définition d'un code social, si possible avec un lien vers une page en expliquant les détails ?

Même si ci-dessous, il y a déjà un paragraphe concernant le contexte du projet SemApss, même si ce que je vais propose alourdi le paragraphe d'introduction, je me sentirais plus à l'aise d'avoir une introduction de quelques lignes expliquant le contexte de rédaction et de validation du présent document. La transparence me semblera servie.

2020-12-07 09:57 UTC, J9rem commented on Code social (version résumée FR).md
> +### Le cercle d'or
Est-ce que le cercle d'or correspond aux membres actifs qui participent aux réunions de "sprint review" ?
ou aussi à tous ceux qui sont sur la canal SemApps Team ?
Si la définition du cercle d'or est donnée dans l'éventuel lien vers la définition du code social, alors ce sera plus clair.
Sinon, j'indiquerais bien une phrase ici pour le définir.

Pourquoi le choix du mot `or` ?

2020-12-07 09:57 UTC, J9rem commented on Code social (version résumée FR).md
> +Le collectif qui contribue au Code Social est un groupe de personnes physiques membres de l'Assemblée Virtuelle.
Je trouve que c'est une définition encore un peu vague qui risque d'être encore trop floue pour un lecteur extérieur ou un nouveau.
Peut-être qu'un lien vers une page de description de l'Assemblée virtuelle serait utile ? car elle apparaît ici sans vraiment que nous sachions ce que sait.

2020-12-07 09:57 UTC, J9rem commented on Code social (version résumée FR).md
> +La modification de ce code social se fait sur la base du consentement lorsqu'un des membres du projet en fait la demande.
```suggestion
La modification de ce code social se fait par [prise de décision par gestion par consentement](http://universite-du-nous.org/wp-content/uploads/2013/09/gpc-2017-v0.1.pdf) lorsqu'un des membres du projet en fait la demande.
```

2020-12-07 09:57 UTC, J9rem commented on Code social (version résumée FR).md
> +Plus d'informations sur le modèle Social et Humain (lien à ajouter)
ne pas oublier d'ajouter le lien

2020-12-07 09:57 UTC, J9rem commented on Code social (version résumée FR).md
> +Plus d'informations sur la gouvernance (lien à ajouter)
ne pas oublier d'ajouter le lien

2020-12-07 09:57 UTC, J9rem commented on Code social (version résumée FR).md
> +- Les pensées et mouvements coopérativistes, libertaires, personnalistes ainsi que les notions d’autonomie, de liberté, de fraternité et de solidarité qu’ils ont incarné au cours des siècles derniers
Est-il possible de clarifier cette phrase ?
Je la trouve longue est chargée de nombreuses notions abstraites à tel point que je n'en comprends plus le sens.

2020-12-07 09:57 UTC, J9rem commented on Code social (version résumée FR).md
> +- Les pensées et dynamiques qui se sont développées autour de la démocratie directe, de la démocratie liquide, de l’empowerment, de la souveraineté ‒ qu’elle soit individuelle ou collective ‒ de la c
Idem, cette phrase est un peu longue contient un peu trop de notions abstraites. Est-il possible de la découper en deux ou trois phrases pour la rendre plus compréhensible ?

Qu'est-ce que `empowerment `?
Qu'elle est la définition de `souveraineté` ?
Même si ça ne reste que des sources d'inspiration, il n'apparait pas clairement qu'il est possible de faire de la gouvernance partagée et de la gestion par consentement tout en respectant la souveraineté.
Ce flou peut compliquer la compréhension de l'ensemble du document.
Nous pourrions retirer le mot `souveraineté`, mais il représente peut-être une chose importante pour certains ou certaines.
Nous pourrions donner davantage d'explications, mais ça risque de surcharger le document.

2020-12-07 09:57 UTC, J9rem commented on Code social (version résumée FR).md
> +- Les nouvelles formes d’économie, collaboratives, circulaires, numériques, agiles, fablabs, DIY, DIWO, Hackerspaces.
Ces notions sont encore en peu connues, est-il possible d'ajouter des liens vers les présentations de chacunes d'entre elles ?

2020-12-07 09:57 UTC, J9rem commented on Code social (version résumée FR).md
> +- Le jeu, l’élan vital, l’hédonisme, l’épicurisme, le Spinozisme (la puissance d’action et la joie), la révolution du sourire et toutes les choses de la vie qui procurent aux êtres sensibles que nous
Je ne comprends pas cette phrase. Est-il possible de la découper ?
Qu'elle est son intention ?

2020-12-07 09:57 UTC, J9rem commented on Code social (version résumée FR).md
> +- La communication bienveillante, et de manière générale les bienfaits d’une meilleure connaissance de soi pour se donner la capacité de développer des relations sociales harmonieuses avec les autres
Alors il est possible d'être bienveillant avec quelqu'un sans être en harmonie.
Nous pouvons mettre en avant `des relations sociales harmonieuses avec les autres`.
Je trouve que c'est un objectif un peu fort. La bienveillance est déjà assez compliquée à maintenir. Ajouter l'objectif d'harmonie me semble ambitieux.

2020-12-07 09:57 UTC, J9rem commented on Code social (version résumée FR).md
> +# Modèle économique
Dans cette partie, il n'est pas fait mention de la façon de rétribuer les contributeurs.
Est-ce uniquement des bénévoles ? Des bénévoles et des prestataires ?
Peut-être est-ce formulé mais je trouve alors que la formulation n'est pas assez claire ?

2020-12-07 12:30 UTC, ValentineMathieu commented
@J9rem Tout d'abord merci pour tout ces retours, et je m'excuse pour ma réponse tardive, la discussion a filé pendant mes jours OFF du coup j'ai pas mal d'informations à assimiler ! Je vais essayer de réagir à vos retours de la manière la plus synthétique possible. 

* Alors dans un premier temps : ne vous inquiétez pas, je ne me sens pas personnellement atteinte par les critiques, et le fait que certains soient quelque peu réticents au lancement de ce chantier. Je vous remercie de vous en soucier ;)

* Petite contextualisation : En tant que responsable onboarding (aux côtés de Gabriel), j'avais déjà ouvert une issue #416 il y a quelques temps à propos de l'ajout du code social au site vitrine. Je voyais qu'il manquait et je considérais que c'était un élément essentiel à l'accueil des nouveaux contributeurs (en partie). Je vous passe les détails, mais au fil d'une discussion avec Pierre, je comprends qu'il avait déjà entrepris un travail d'écriture d'un code social propre à Semapps, alors que je pensais qu'il n'y avait que celui de l'AV. Nous avons donc communément pensé que c'était une bonne idée de revaloriser cette matière froide perdue dans le yeswiki, et de l'utiliser comme "point de départ" de cette réécriture. J'ai choisi de me lancer sur ce projet, car je pense qu'il n'est peut être pas prioritaire pour tous, mais important pour définir et visibiliser le fonctionnement de la team SemApps.

* @bouviermullerp : À propos de méthode, j'avais eu l'idée d'ouvrir 2 PR (une pour la version résumée, une pour la détaillée) dans la volonté d'inclure chaque membre de l'équipe dans l'écriture de code social, étant donné que je n'ai également pas les compétences ni le recul pour m'en charger seule. J'ai mis la team semapps en reviewers premièrement dans un soucis de partage de mon travail et de contribution de chacun, et deuxièmement dans le but d'être relue après d'importantes modifications (d'où le fait que j'avais précisé dans le kanban que c'était en progrès, même si ca ne se voit plus maintenant). 

* En résumé : Dans un premier temps, je pensais mutualiser vos retours afin de progressivement reformuler et modifier ce code social, à ma manière, et à la votre. Dans un second temps, je comptais annoncer une relecture finale de ce code social, afin de peaufiner et d'apporter les dernières modifications nécessaires.

Alors j'espère avoir répondu à vos questions et avoir éclairci la situation. Je ne sais pas si ma démarche est la meilleure même si je la pense intéressante, je ne suis pas encore une as de la gouvernance partagée, ce pour quoi je reste en tout cas ouverte à vos propositions et vos doutes :) 

N'hésitez pas à me poser des questions

Merci à tous !

2021-01-18 15:14 UTC, ValentineMathieu commented on Code social (version résumée FR).md
> +Le Code Social du projet a pour objectif de le décrire de manière exhaustive et systémique.
J'ai fais un paragraphe d'intro pour expliquer ce qu'est un code social, en m'inspirant de quelques liens sur internet et de ma compréhension de ce texte :) Vous êtes libres d'apporter vos modifs/commentaires si besoin

2022-06-21 15:27 UTC, srosset81 commented
Je ferme cette proposition qui est en sommeil depuis 1 année et demi, et qui n'a jamais eu une adhésion de l'équipe.

2022-06-21 15:27 UTC, closed without merging