relation réifiées grace à la configuration disassembly du container et au ArrayInput+SimpleFormIterator de react-admin
assemblee-virtuelle/semapps pull request #582
Opened 2021-02-17 06:42 UTC by simonLouvet

resolve #551

2021-02-17 23:31 UTC, srosset81 commented on src/middleware/boilerplates/pair-ldp-server/containers.js
> +    path: '/membershipRole',
Le nom des containers sont au pluriel.
De plus ce serait mieux d'utiliser `/membership-roles` car c'est le format qu'on utilise pour les slugs.

2021-02-17 23:36 UTC, srosset81 commented on src/middleware/boilerplates/pair-ldp-server/containers.js
> +    disassembly: [{ path: 'pair:organizationOfMembership', container: CONFIG.HOME_URL + '/membershipAssociations' }]
Ca me semble bien compliqué comme paramètre, et générateur de bugs.
Tu as essayé avec les blank nodes ? Tu es sûr que ça ne marche pas ? Les blank nodes seraient idéal pour ne pas avoir à s'embêter avec des IDs et des containers.

2021-03-02 10:30 UTC, simonLouvet commented
Ajout de la notion de forceArray pour que le dataAdapter transforme les objet en tableau pour les realtion 1-n.

2021-03-02 10:31 UTC, simonLouvet commented
définition de l'emplacement des data fuseky pour le dev afin de pouvoir facilement les consulter / supprimer

2021-03-02 16:27 UTC, srosset81 requested changes
Problèmes généraux:

- Le lien inverse n'est pas créé. Si on regarde juste l'élément MembershipAssociation, on ne peut pas retrouver l'organisation à laquelle il est lié.

![Capture d’écran de 2021-03-02 17-08-30](https://user-images.githubusercontent.com/17931931/109677434-f1a03600-7b79-11eb-80b9-cfe81bc4ce83.png)

- Je trouve que devoir ajouter deux "hacks" pour gérer un nouvel input (forceArray et dissassembly), ça fait beaucoup, mais bon si ça marche on peut rester sur ça pour le moment et voir dans le futur pour les enlever.

- Beaucoup de commentaires, mais beaucoup concernent des choses qui sortent du scope de cette PR. Pour faciliter les reviews ce serait mieux d'éviter.

2021-03-02 16:27 UTC, srosset81 commented on src/middleware/packages/ldp/services/resource/actions/get.js
> +        throw new MoleculerError('Not found', 404, 'NOT_FOUND');
C'était bien pratique de savoir ce qui n'est pas trouvé, je l'avais ajouté car les messages d'erreurs prêtaient à confusion.
Pourquoi ce changement ?

2021-03-02 16:27 UTC, srosset81 commented on src/middleware/boilerplates/pair-ldp-server/containers.js
> +    disassembly: [{ path: 'pair:organizationOfMembership', container: CONFIG.HOME_URL + 'membership-associations' }]
Pourquoi `pair:organizationOfMembership` c'est un "path" ? J'aurai dit plutôt un type...

2021-03-02 16:27 UTC, srosset81 commented on src/middleware/boilerplates/pair-ldp-server/.env
> +SEMAPPS_OIDC_CLIENT_ID=4461746120466f6f6420436f6e736f727469756d
Toujours préférer l'usage des .env.local... et on peut partir de l'idée que ces données sont compromises car il y a des bots qui se promènent sur les repo à la recherche de ce type d'informations.

2021-03-02 16:27 UTC, srosset81 commented on src/frontend/boilerplates/archipelago/src/resources/Concept/MembershipRole/RoleShow.js
> +export default RoleShow;
A mon avis c'est inutile de faire des pages Show lorsqu'il n'y a rien à afficher.

2021-03-02 16:27 UTC, srosset81 commented on src/frontend/boilerplates/archipelago/src/resources/Agent/Actor/Organization/OrganizationEdit.js
> +          <ReferenceInput label="role" reference="MembershipRole" source="pair:membershipRole">
Les labels doivent être mis dans les fichiers index.js de chaque type de ressource, au niveau des `translations`.

2021-03-02 16:27 UTC, srosset81 commented on src/frontend/boilerplates/archipelago/src/resources/Agent/Actor/Organization/OrganizationEdit.js
> +          <ReferenceInput label="role" reference="MembershipRole" source="pair:membershipRole">
Et je mettrai cet input plus bas, au niveau des relations (en enlevant la relation `pair:affiliates`?)

2021-03-02 16:27 UTC, srosset81 commented on .gitignore
> +data/
Enlever

2021-03-02 16:27 UTC, srosset81 commented on src/frontend/packages/semantic-data-provider/src/inputs/ReificationArrayInput.js
> +  });
Il faut mettre les makeStyles en dehors de la classe.

2021-03-02 16:27 UTC, srosset81 commented on src/frontend/boilerplates/archipelago/src/resources/Agent/Actor/Organization/OrganizationEdit.js
> +            <AutocompleteInput optionText="pair:lastName" allowEmpty />
Pourquoi allowEmpty ? Par ailleurs, ce serait mieux d'afficher le nom et prénom
```
optionText={record => record && `${record['pair:firstName']} ${record['pair:lastName']}`}
```

2021-03-02 16:27 UTC, srosset81 commented on src/frontend/packages/semantic-data-provider/src/inputs/ReificationArrayInput.js
> +  });
Par ailleurs il y a plein de warning au sujet de ces classes
![Capture d’écran de 2021-03-02 17-14-25](https://user-images.githubusercontent.com/17931931/109678313-c8cc7080-7b7a-11eb-95d7-540cd34f5574.png)

2021-03-02 16:27 UTC, srosset81 commented on src/middleware/packages/connector/index.js
> +  // CasConnector: require('./CasConnector'),
Peut-être ouvrir une issue s'il y a un problème ?

2021-03-02 16:27 UTC, srosset81 commented on src/middleware/packages/ldp/services/resource/actions/delete.js
> +              console.log('disassemblyValue', disassemblyValue);
console.log

2021-03-02 16:27 UTC, srosset81 commented on src/middleware/packages/ldp/services/resource/actions/put.js
>        });
Mauvaise idée. `ldp.resource.delete` a pour résultat d'envoyer un event `ldp.resource.deleted`, ce qui peut créer des problèmes.

2021-03-02 16:27 UTC, srosset81 commented on src/middleware/packages/ldp/services/resource/actions/put.js
>          });
Même remarque que plus haut.

2021-03-02 16:27 UTC, srosset81 commented on src/middleware/packages/ldp/services/resource/actions/post.js
> +        for (disassemblyItem of disassembly) {
Il manque un `let` devant `disassemblyItem`

2021-03-02 16:27 UTC, srosset81 commented on src/middleware/packages/ldp/services/resource/actions/post.js
> +      const insertedUri = await ctx.call('triplestore.insert', {
`insertedUri` est utilisé nulle part. Et de toute façon l'action ne retourne rien...

2021-03-02 16:27 UTC, srosset81 commented on src/middleware/packages/ldp/services/resource/actions/put.js
> -      );
`ldp.resource.post` ne renvoie que l'URI, pas les données complètes. Alors il ne faut pas supprimer ça...

2021-03-02 16:27 UTC, srosset81 commented on src/middleware/tests/activitypub/object.test.js
> +    ).rejects.toThrow('Not found');
?

2021-03-02 16:46 UTC, simonLouvet commented on src/middleware/packages/ldp/services/resource/actions/get.js
> +        throw new MoleculerError('Not found', 404, 'NOT_FOUND');
Pour que les tests passent. Je suis d'accord que garder la différence est utile. Je modifie les tests.

2021-03-02 16:47 UTC, simonLouvet commented on src/middleware/boilerplates/pair-ldp-server/containers.js
> +    disassembly: [{ path: 'pair:organizationOfMembership', container: CONFIG.HOME_URL + 'membership-associations' }]
c'est le predicate dans la même logique que dereference. Cela pourrait être un path séparé par des "/" par ex.

2021-03-02 16:48 UTC, simonLouvet commented on src/middleware/boilerplates/pair-ldp-server/.env
> +SEMAPPS_OIDC_CLIENT_ID=4461746120466f6f6420436f6e736f727469756d
ce n'est pas grave que ces données soient compromises, l'identifiant OIDC de l'appli et le issuer n'ont rien de secret. ok pour les enlever

2021-03-02 16:48 UTC, simonLouvet commented on src/frontend/boilerplates/archipelago/src/resources/Concept/MembershipRole/RoleShow.js
> +export default RoleShow;
exact

2021-03-02 16:49 UTC, simonLouvet commented on src/frontend/boilerplates/archipelago/src/resources/Agent/Actor/Organization/OrganizationEdit.js
> +          <ReferenceInput label="role" reference="MembershipRole" source="pair:membershipRole">
ok

2021-03-02 16:51 UTC, simonLouvet commented on src/middleware/packages/ldp/services/resource/actions/put.js
>          });
j'ai pas compris à quoi tu fais reference

2021-03-02 16:51 UTC, simonLouvet commented on src/middleware/packages/ldp/services/resource/actions/post.js
> +        for (disassemblyItem of disassembly) {
++

2021-03-02 16:52 UTC, simonLouvet commented on src/middleware/packages/ldp/services/resource/actions/put.js
> -      );
je regarde

2021-03-02 16:55 UTC, srosset81 commented on src/middleware/packages/ldp/services/resource/actions/put.js
>          });
A ton appel à `ldp.resource.delete` dans la même action.
C'est tous les changements dans cette action qui sont problématiques grosso modo.

2021-03-02 16:59 UTC, simonLouvet reviewed
> Problèmes généraux:
> 
> * Le lien inverse n'est pas créé. Si on regarde juste l'élément MembershipAssociation, on ne peut pas retrouver l'organisation à laquelle il est lié.
> 
> ![Capture d’écran de 2021-03-02 17-08-30](https://user-images.githubusercontent.com/17931931/109677434-f1a03600-7b79-11eb-80b9-cfe81bc4ce83.png)
> 
> * Je trouve que devoir ajouter deux "hacks" pour gérer un nouvel input (forceArray et dissassembly), ça fait beaucoup, mais bon si ça marche on peut rester sur ça pour le moment et voir dans le futur pour les enlever.
> * Beaucoup de commentaires, mais une partie concernent des choses qui sortent du scope de cette PR. Pour faciliter les reviews ce serait mieux de s'en tenir à ce que la PR doit faire.

le lien inverse n'est pas créé par ce que l'ontologie OWL ne mentionne pas les lien inverses.

Tu appelles les mécanises implémentés des hack mais pour moi c'est de la configuration de comportement qui sont à implémenter dans les composants de front-data (middleware) ou back-data (dataAdapter) plutôt que les composant  front-view.

J'ai du mal a identifier ce que j'ai fait qui sort de la PR si ce n'st les textes d'erreur que j'ai modifier pour que les tests passent.

2021-03-02 17:24 UTC, simonLouvet commented on src/middleware/packages/ldp/services/resource/actions/put.js
>        });
Ok je comprends mais j'ai utilisé cela pour mutualiser le comportement du disassembly dans le delete et le post. le delete supprime également les relation disassembly pour éviter les orphelins et le post permet de mutualiser le code de création de sujet désassemblé. Je voie bien une solution mais c'est un peut lourd... créer une troisième action style ldp.post_subject et ldp.delete_subject qui serait appelé par ldp.post et ldp.delete. Les émissions de message moleculer serait fait par ldp.post et ldp.get et pas ldp.post_subject et ldp.delete_subject. Qu'est ce que tu en pense?

2021-03-02 17:31 UTC, simonLouvet commented on src/frontend/packages/semantic-data-provider/src/inputs/ReificationArrayInput.js
> +  });
ok pour les makestyles.

2021-03-02 17:31 UTC, simonLouvet commented on src/frontend/packages/semantic-data-provider/src/inputs/ReificationArrayInput.js
> +  });
Concernant ces warning, j'avoue que je je suis incompétents. je ne comprends pas vraiment quel est le probleme et comment le résoudre. Tu peux m'aider sur cette partie?

2021-03-02 17:36 UTC, simonLouvet commented on .gitignore
> +data/
ok

2021-03-02 17:39 UTC, srosset81 commented on src/middleware/packages/ldp/services/resource/actions/put.js
>        });
Créer une action en plus rendrait le code illisible à mon avis...
Il y a des problèmes de fond: les actions PUT et PATCH ne devraient pas effacer les données. Il y a une [issue](https://github.com/assemblee-virtuelle/semapps/issues/430) sur le sujet qui doit être traitée en priorité.
En attendant, je trouve que le plus simple serait de mettre tout ce qui est autour du "dissassembly" dans un fichier (et des fonctions) à part, et de faire les appels au bons endroits. Comme ça il n'y aura pas trop de duplication de code, et on garde des noms d'actions clairs.

2021-03-02 17:45 UTC, srosset81 commented
> le lien inverse n'est pas créé par ce que l'ontologie OWL ne mentionne pas les lien inverses.

Ah OK c'est ça ! :-) Tant mieux.

> Tu appelles les mécanises implémentés des hack mais pour moi c'est de la configuration de comportement qui sont à implémenter dans les composants de front-data (middleware) ou back-data (dataAdapter) plutôt que les composant front-view.

Question de langage ? Un hack pour moi c'est un truc qu'on fait pour contourner un problème qu'on n'arrive pas à régler de manière simple. Les options `disassembly` et `forceArray` sont source d'erreurs et d'incompréhension pour quelqu'un qui débarquerait sur le projet.

> J'ai du mal a identifier ce que j'ai fait qui sort de la PR si ce n'st les textes d'erreur que j'ai modifier pour que les tests passent.

Je parlais des modifications sur `ldp.resource.post` et `ldp.resource.delete`. Mais je comprend maintenant pourquoi tu as fait ça, même si ça a cassé pas mal de code...

2021-03-02 17:50 UTC, simonLouvet commented on src/frontend/packages/semantic-data-provider/src/inputs/ReificationArrayInput.js
> +  });
@srosset81 est ce que tu pourra regarder le problème des key quand le reste de tes commentaires sera taité?

2021-03-02 18:11 UTC, srosset81 commented on src/frontend/packages/semantic-data-provider/src/inputs/ReificationArrayInput.js
> +  });
Il me semble que le message d'erreur est clair: tu passes des classes qui ne sont pas acceptées par les composants.
Plutôt que passer toutes les classes, tu peux ne passer que `className` ou faire `classes={{ classes.class1, classes.class2 }}`

2021-03-03 15:39 UTC, simonLouvet commented on src/frontend/boilerplates/archipelago/src/resources/Agent/Actor/Organization/OrganizationEdit.js
> +            <AutocompleteInput optionText="pair:lastName" allowEmpty />
++

2021-03-07 15:19 UTC, simonLouvet commented on src/middleware/packages/ldp/services/resource/actions/put.js
> -      );
vu et ok, par contre le post possède la data complète car il fait un get pour faire le ctx.emit('ldp.resource.created'). Dommage de ne pas exploiter cela. @srosset81

2021-03-08 11:20 UTC, simonLouvet commented
doc at https://website-git-551-semapps.vercel.app/docs/others/reifiedRelation

2021-03-08 11:42 UTC, simonLouvet commented on src/middleware/packages/connector/index.js
> +  // CasConnector: require('./CasConnector'),
#638

2021-03-09 08:59 UTC, srosset81 approved these changes

2021-03-09 10:05 UTC, merged