Ldp service & Doker compose
assemblee-virtuelle/semapps pull request #59
Opened 2019-12-08 16:21 UTC by simonLouvet

LDP service initialisation whith complex SPARQL request test
Doker + Doker Compose + make file : start whith one commande ; make start at the root of project

2019-12-08 16:36 UTC, simonLouvet commented
GET http://localhost:8080/activities pour recupérer les activités
POST http://localhost:3000/outbox pour créer une activité
{
 "@context": "https://www.w3.org/ns/activitystreams",
 "type": "Note",
 "name": "Hello World",
 "content": "Voilà mon premier message, très content de faire partie du fedivers !",
 "published": "2019-05-28T12:12:12Z"
}

2019-12-08 21:44 UTC, srosset81 requested changes
C'est une grosse PR, du coup désolé pour le gros review.
Merci de toujours penser à lancer prettier (`npm run prettier` dans le dossier SolidMiddleware) avant de soumettre une PR, cela facilite la lecture.

2019-12-08 21:44 UTC, srosset81 commented on sources/SolidMiddleware/packages/LDP/index.js
> +      let result =  await this.getTriples(`
Pourquoi ne pas appeler l'action `triplestore.query` qui fait exactement la même chose ?
Je n'ai pas de problème à ce que j'ai fait soit amélioré ! ;-)

2019-12-08 21:44 UTC, srosset81 commented on sources/SolidMiddleware/packages/LDP/index.js
> +      console.log(result);
Merci de ne pas laisser de console.log. sauf lorsque c'est vraiment pertinent.
Si on commence à en laisser partout, ça rendra la console pratiquement inutilisable (de mon expérience).
(Il y en a plusieurs autres qui doivent être nettoyés)

2019-12-08 21:44 UTC, srosset81 commented on sources/SolidMiddleware/packages/adminFuseki/index.js
> +  actions: {
Les `settings` utilisés par le service devraient être listés ici (sparqlEndpoint, jenaUser, jenaPassword)

2019-12-08 21:44 UTC, srosset81 commented on sources/SolidMiddleware/packages/adminFuseki/index.js
> +              Authorization: 'Basic ' + Buffer.from(`${this.settings.jenaUser}:${this.settings.jenaPassword}`).toString('base64')
Le code pour la génération du header `Authorization` est dupliqué, on peut sans doute éviter ça ;-)
Sinon passer ça en settings comme je l'ai fait pour le service triplestore ?

2019-12-08 21:44 UTC, srosset81 commented on sources/SolidMiddleware/packages/adminFuseki/index.js
> +        if (response.status==404){
Cela devrait être une triple = (je pense que Prettier aurait corrigé ça automatiquement, mais pas sûr)

2019-12-08 21:44 UTC, srosset81 commented on sources/SolidMiddleware/boilerplate/runner/index.js
> +  });
Pourquoi créer deux API différents ? Dans la majorité des cas, l'API ActivityPub sera sur le même serveur que l'API LDP.
Il suffit de merger les routes : `routes: [ldp.routes, ActivityPubRoutes]`

2019-12-08 21:44 UTC, srosset81 commented on sources/SolidMiddleware/Dockerfile
> +CMD [ "pm2-runtime", "./boilerplate/runner/index.js", "--name" ,"SemappSolid"]
Ce serait bien (peut-être pas maintenant) que `./boilerplate/runner/index.js` puisse être passé en variable d'environnement au container, afin qu'on puisse lancer d'autres boilerplates lorsqu'il y en aura.

2019-12-08 21:44 UTC, srosset81 commented on sources/SolidMiddleware/package.json
> +    "dev" : "nodemon ./boilerplate/runner/index.js",
Personnellement, je pense pas qu'il faut mettre ce type de commandes au niveau de SolidMiddleware. Cela ne concerne que le boilerplate "runner".
Si on garde ça (temporairement), la commande nodemon n'est pas suffisante. Il faut ajouter un `--watch ./packages` pour qu'il surveille aussi les modifications faites au niveau du dossier packages.

2019-12-08 21:44 UTC, srosset81 commented on sources/SolidMiddleware/packages/LDP/index.js
> +  routes: {
Il manque les `settings` là aussi.

2019-12-08 21:44 UTC, srosset81 commented on sources/SolidMiddleware/boilerplate/runner/index.js
> +    settings: config
En terme de clareté, je trouve moyen de passer tout le fichier de config.
Si les services sont bien séparés, on ne devrait pas avoir 10 config à passer à chaque service.

2019-12-09 09:30 UTC, nikoPLP approved these changes

2019-12-09 09:30 UTC, nikoPLP commented on sources/SolidMiddleware/boilerplate/runner/index.js
> +  });
ok

2019-12-09 09:30 UTC, nikoPLP commented on sources/SolidMiddleware/package.json
> +    "dev" : "nodemon ./boilerplate/runner/index.js",
donc tu veux bouger ca dans boilerplate/runner/package.json ?

2019-12-09 09:30 UTC, nikoPLP commented on sources/SolidMiddleware/packages/LDP/index.js
> +      console.log(result);
ok

2019-12-09 09:30 UTC, nikoPLP commented on sources/SolidMiddleware/packages/LDP/index.js
> +    }
Pourquoi besoin de return new Promise ?
Je propose plutot l'ecriture concise:
```
    async getTriples(query) {
      let response = await fetch(this.settings.sparqlEndpoint + this.settings.mainDataset+'/query', {
        method: 'POST',
        body: query,
        headers: {
          'Content-Type': 'application/sparql-query'
        }
      })
      return response.text();
    }
```

les exception de fetch seront propagées a getTriples, tout comme le faisait le catch / reject

2019-12-09 15:10 UTC, srosset81 commented on sources/SolidMiddleware/package.json
> +    "dev" : "nodemon ./boilerplate/runner/index.js",
Ca y est déjà en fait :-)

2019-12-10 07:54 UTC, simonLouvet commented on sources/SolidMiddleware/packages/LDP/index.js
> +      let result =  await this.getTriples(`
pas de soucis, je voulais juste pousser qqc d’opérationnel à améliorer par itération

2019-12-10 07:54 UTC, simonLouvet commented on sources/SolidMiddleware/packages/LDP/index.js
> +  routes: {
Je pense qu'il est inutile de les préciser car ils sont fournis par le runner

2019-12-10 07:54 UTC, simonLouvet commented on sources/SolidMiddleware/boilerplate/runner/index.js
> +    settings: config
De mon côté je cherche un runner le plus concis possible pour pouvoir facilement migrer vers un runner par configuration plutôt que plusieurs boilerplate différents. plus on mettra de code dans le runner et plus il sera difficile de faire un déploiement par configuration plutôt qu'un déploiement par code. Un service qui a des paramètres des settings en trop cela ne me semble pas grave ni consommateur de ressource.

2019-12-10 07:54 UTC, simonLouvet commented on sources/SolidMiddleware/boilerplate/runner/index.js
> +  });
Ok sur le principe mais cela me semble dangereux. imaginons que il existe objets dont la classe est "outbox" dans le dataset principale et que pour nous choisissions un pattern LDP 'http://domaine/myclasse' pour obtenir tous les sujets dont la classe est 'myclasse' soit  'http://domaine/outbox' pour obtenir tous les sujets dont la classe est 'outbox' . Cela rentre en conflit avec l’interface ActivityPub si il n'existe qu'un serveur avec un seul port.

2019-12-10 07:54 UTC, simonLouvet commented on sources/SolidMiddleware/package.json
> +    "dev" : "nodemon ./boilerplate/runner/index.js",
Je les ai mis ici pour que les developpeurs/testeurs n'ai pas besoin d'aller dans le repetroire boilerplate/runner/ pour lancer le projet. Je suis d'accord que ce n'est pas "traditionnel" et que faire le npm start dans le bon répertoire est plus rigoureux mais je vise l'attractivité du projet pour inclure des nouveaux. Etant donné que nous devrions lancer le projet par docker-compose (make start) plutôt que par npm directement (notamment pour des raisons de configuration réseau) je ne ferai pas objection à migrer ces scripts dans boilerplate/runner/. conclusions?

2019-12-10 07:54 UTC, simonLouvet commented on sources/SolidMiddleware/packages/LDP/index.js
> +      console.log(result);
++

2019-12-10 07:54 UTC, simonLouvet commented on sources/SolidMiddleware/packages/LDP/index.js
> +    }
++

2019-12-10 07:54 UTC, simonLouvet commented on sources/SolidMiddleware/packages/adminFuseki/index.js
> +  actions: {
Je pense qu'il est inutile de les préciser car ils sont fournis par le runner

2019-12-10 07:54 UTC, simonLouvet commented on sources/SolidMiddleware/packages/adminFuseki/index.js
> +        if (response.status==404){
dsl, j'ai zappé le prettier sur les dernières modifs

2019-12-10 07:54 UTC, simonLouvet commented on sources/SolidMiddleware/packages/adminFuseki/index.js
> +              Authorization: 'Basic ' + Buffer.from(`${this.settings.jenaUser}:${this.settings.jenaPassword}`).toString('base64')
De mon côté je cherche un runner le plus concis possible pour pouvoir facilement migrer vers un runner par configuration plutôt que plusieurs boilerplate différents. plus on mettra de code dans le runner et plus il sera difficile de faire un déploiement par configuration plutôt qu'un déploiement par code. Un service qui a des paramètres des settings en trop cela ne me semble pas grave ni consommateur de ressource. Je pense donc qu'il est préférable de transmettre la config depuis le reunner et que ce soit le service qui fasse le calcul du Autorization.

2019-12-10 07:54 UTC, simonLouvet commented on sources/SolidMiddleware/Dockerfile
> +CMD [ "pm2-runtime", "./boilerplate/runner/index.js", "--name" ,"SemappSolid"]
Intéressant comme approche. Actuellement la commande est surchargé dans le docker compose. PM2 ne serait lancé que pour la production. A discuter/améliorer mais je merge en l'état pour pas coincer.

2019-12-10 07:54 UTC, simonLouvet commented on sources/SolidMiddleware/package.json
> +    "dev" : "nodemon ./boilerplate/runner/index.js",
@srosset81 pas compris ta conclusion. je sais bien que ca  y est déjà.

2019-12-10 08:11 UTC, srosset81 commented on sources/SolidMiddleware/packages/adminFuseki/index.js
> +  actions: {
Je ne suis pas d'accord. Si on lit juste le fichier du service, on doit comprendre quels settings sont passés. Si on est obligé d'aller regarder du côté du "runner", cela rend la lecture plus compliquée.

2019-12-10 08:16 UTC, srosset81 commented on sources/SolidMiddleware/packages/LDP/index.js
> +      let result =  await this.getTriples(`
Dans ce cas je proposerai une PR dès que ce sera mergé, car cela n'est pas propre. Autant utiliser les services tels qu'ils sont censés être utilisés.

2019-12-10 08:25 UTC, srosset81 commented on sources/SolidMiddleware/boilerplate/runner/index.js
> +    settings: config
Créer un "runner par configuration" est un problème auquel on s'atellera dans le futur. C'est ton idée, je pense qu'elle est intéressante mais je ne pense pas qu'elle doit s'imposer dès le départ (en tout cas on a rien décidé dans ce sens).
J'ai déjà dit qu'il y a plein de cas où ce ne sera pas possible de passer par ce biais (par exemple si on a besoin de routes express custom) et donc il faut partir de l'idée qu'on devra permettre de créer un service normalement.
Passer toute la config n'est pas grave en terme de performance, mais ça n'aide pas à comprendre ce dont le service a besoin. Et pour moi cette lisibilité est importante, surtout quand on aura des dizaines de services.

2019-12-10 08:28 UTC, srosset81 commented on sources/SolidMiddleware/package.json
> +    "dev" : "nodemon ./boilerplate/runner/index.js",
Je répondais à @nikoPLP (ton commentaire n'était pas visible)
D'accord avec ta conclusion. Comme on privilégie le lancement par docker-compose, proposer un `npm start` à cet endroit n'a pas d'intérêt en particulier. Depuis le docker on peut donc appeler directement le `npm start` (ou `npm run dev`) qui se trouve dans le dossier boilerplate/runner.

2019-12-10 08:29 UTC, srosset81 commented on sources/SolidMiddleware/packages/adminFuseki/index.js
> +              Authorization: 'Basic ' + Buffer.from(`${this.settings.jenaUser}:${this.settings.jenaPassword}`).toString('base64')
Voir mon autre commentaire sur les "runner par configuration".
Pas d'objection à ce que `Autorization` soit calculé ici dans ce service, par contre ça aurait du sens de le calculer une seule fois.

2019-12-10 08:39 UTC, srosset81 commented on sources/SolidMiddleware/boilerplate/runner/index.js
> +  });
Effectivement il pourrait y avoir ce problème, mais je pense que pour ce boilerplate, il faut partir avec une configuration simple. Dans la plupart des cas, les utilisateurs ne vont pas utiliser deux serveurs, car cela nécessiterait de passer soit par deux ports, soit par deux domaines.
Si c'est plus facile à gérer pour toi avec le serveur LDP, on peut, par défaut, tout mettre dans un dossier `/activitypub`. cela se fait très facilement avec `moleculer-web`, il suffit d'utiliser le paramètre `path`: https://moleculer.services/docs/0.13/moleculer-web.html#Multiple-routes. Et si un utilisateur veut mettre les path activitypub à la racine, il lui suffira de changer cette configuration par défaut.

2019-12-10 08:46 UTC, simonLouvet commented on sources/SolidMiddleware/packages/adminFuseki/index.js
> +              Authorization: 'Basic ' + Buffer.from(`${this.settings.jenaUser}:${this.settings.jenaPassword}`).toString('base64')
une seul fois par service ou une seul fois pour l'application?

2019-12-10 08:46 UTC, simonLouvet commented on sources/SolidMiddleware/packages/adminFuseki/index.js
> +  actions: {
je consent mais dans ce cas, des paramètres par défaut dans le service me paraissent dangereux, contreproductif et rendent les services difficilement réutilisable.
est ce que un truc comme cela conviendrait?
{
 setting1: undefined,
 setting1 : undefined
}

2019-12-10 08:46 UTC, simonLouvet commented on sources/SolidMiddleware/boilerplate/runner/index.js
> +    settings: config
je consent

2019-12-10 08:46 UTC, simonLouvet commented on sources/SolidMiddleware/packages/LDP/index.js
> +  routes: {
je consent mais dans ce cas, des paramètres par défaut dans le service me paraissent dangereux, contreproductif et rendent les services difficilement réutilisables.
est ce que un truc comme cela conviendrait?
{
 setting1: undefined,
 setting1 : undefined
}

2019-12-10 08:53 UTC, simonLouvet commented on sources/SolidMiddleware/boilerplate/runner/index.js
> +  });
Si j'ai bien compris, tu veut faire 2 path. 1 pour activitypub et 1 pour LDP afin d'éviter le conflit l'url. Cela fonctionne. En quoi c'est plus simple/facile que de déclarer 2 service d'API sur 2 ports. Ma préférence va pour 2 ports sur le model de rabbitMQ par ex dans lequel chaque technologie à son port (interface HTML, AMQP, WebSocket...).

2019-12-10 09:25 UTC, srosset81 commented on sources/SolidMiddleware/packages/adminFuseki/index.js
> +  actions: {
Le mieux dans ce cas c'est de les mettre à `null` (ou `[]` si c'est sensé être un array)

2019-12-10 09:26 UTC, srosset81 commented on sources/SolidMiddleware/packages/adminFuseki/index.js
> +  actions: {
Les paramètres par défaut peuvent avoir du sens dans certains cas, mais c'est vrai qu'il ne faut pas en abuser.

2019-12-10 09:29 UTC, srosset81 commented on sources/SolidMiddleware/packages/adminFuseki/index.js
> +              Authorization: 'Basic ' + Buffer.from(`${this.settings.jenaUser}:${this.settings.jenaPassword}`).toString('base64')
Pour le service. Je pense qu'une méthode `getAuthorization` aurait du sens, ou sinon définir une variable `const authorization = ...`

2019-12-10 09:32 UTC, srosset81 commented on sources/SolidMiddleware/boilerplate/runner/index.js
> +  });
Le service LDP pourrait être à la racine, tant qu'il n'y a pas d'objet qui se nomme "activitypub" (ce qui ne devrait pas être le cas !), cela ne posera pas de problème.
Utiliser un path `/activitypub` pour les routes ActivityPub est plus facile car cela ne nécessite pas de créer et gérer deux ApiGateway services !
Je suis d'accord pour que chaque technologie ait son port, mais là on est sur la même technologie: c'est l'ApiGateway.

2019-12-10 09:33 UTC, srosset81 commented on sources/SolidMiddleware/packages/LDP/index.js
> +  routes: {
Voir mon autre commentaire.

2019-12-10 09:35 UTC, srosset81 commented on sources/SolidMiddleware/boilerplate/runner/package.json
> +    "dev" : "nodemon",
Il manque `--watch ../..`, nodemon ne rechargera pas le serveur après modification des packages.

2019-12-10 11:59 UTC, simonLouvet commented on sources/SolidMiddleware/packages/adminFuseki/index.js
> +  actions: {
pourquoi null plutôt que undefined?

2019-12-10 12:02 UTC, simonLouvet commented on sources/SolidMiddleware/boilerplate/runner/index.js
> +  });
Je consent pour avancer mais je ne suis pas vraiment d'accord pour cette solution. A rediscuter.

2019-12-10 14:37 UTC, srosset81 commented on sources/SolidMiddleware/packages/adminFuseki/index.js
> +  actions: {
D'après ma connaissance un objet avec une propriété `undefined`, c'est comme si cette propriété n'existait pas. Avec `null` on sait qu'elle est là, même si elle est vide.

2019-12-10 14:37 UTC, srosset81 commented on sources/SolidMiddleware/boilerplate/runner/index.js
> +  });
Oui on peut en discuter jeudi !

2019-12-10 15:00 UTC, simonLouvet commented on sources/SolidMiddleware/packages/adminFuseki/index.js
> +  actions: {
exact, on peut plus facilement identifier que la propriété et celle par défaut et non celle surchargé par initialisation du service.

2019-12-10 15:29 UTC, simonLouvet commented on sources/SolidMiddleware/packages/adminFuseki/index.js
> +              Authorization: 'Basic ' + Buffer.from(`${this.settings.jenaUser}:${this.settings.jenaPassword}`).toString('base64')
je l'ai initialisé à la méthode started.

2019-12-10 16:50 UTC, srosset81 approved these changes

2019-12-10 16:51 UTC, merged