simplification et amélioration de GroupedArrayField et FilteredArrayField
assemblee-virtuelle/semapps pull request #723
Opened 2021-04-29 22:59 UTC by simonLouvet

Problématique
resolve #666 et #667

coller plus à la philosophie react-admin en simplifiant au maximum les composants tout en permettant un maximum de possibilité d'ergonomie

Composants concernés
GroupedArrayField
FilteredArrayField
DataProvider

2021-04-30 08:49 UTC, srosset81 requested changes
Merci !
Le code est en effet plus concis, par contre il y a un problème de bonne pratique avec RightLabel.

2021-04-30 08:49 UTC, srosset81 commented on src/frontend/packages/semantic-data-provider/src/fields/FilteredArrayField.js
> +  console.log('FilteredArrayField');
console.log ...

2021-04-30 08:49 UTC, srosset81 commented on src/frontend/packages/semantic-data-provider/src/dataProvider.js
> +      const clone = JSON.parse(JSON.stringify(resources));
Enlever commentaire ligne au-dessus.
+ JSON.parse et JSON.stringify sont des opérations très coûteuse.
Tu peux pas juste faire `const clone = { ...resources };` ?

2021-04-30 08:49 UTC, srosset81 commented on src/frontend/packages/semantic-data-provider/src/buildSparqlQuery.js
> -  `;
C'est pour le futur, j'imagine ? Parce que le code pour la pagination est commenté.
J'enleverai le commentaire car ça ne concerne pas que GroupedArrayField, mais tous les appels fait sans préciser la pagination.

2021-04-30 08:49 UTC, srosset81 commented on src/frontend/boilerplates/archipelago/src/resources/Agent/Actor/Organization/OrganizationShow.js
> +              <ArrayField source="pair:organizationOfMembership">
Mettre RightLabel au dessus d'un Field n'est pas une bonne pratique de react-admin. Ca ne ressemble à rien d'existant. C'est le composant SideList (ou MainList ou d'autres composants de react-admin) qui gère l'ajout, ou non, des labels.

2021-04-30 09:26 UTC, simonLouvet commented on src/frontend/packages/semantic-data-provider/src/buildSparqlQuery.js
> -  `;
oui de code bloquait l’exécution si la pagination n’était pas présentes en entrée. ++ pour changer le commentaire

2021-04-30 10:09 UTC, simonLouvet commented on src/frontend/boilerplates/archipelago/src/resources/Agent/Actor/Organization/OrganizationShow.js
> +              <ArrayField source="pair:organizationOfMembership">
Le probleme c'est que mes fields ne sont pas directement enfant de SideList ou Column ou MainList  et il faut donc forcer le label.
Dans SideList ou Column tu encapsule bien les fields dans des rightLabel.
```
<RightLabel
  {field}
</RightLabel>
```
Si je n'utilise pas RightLabel, il faudra que je fasse ma propre balise ou le faire manuellement.

2021-04-30 10:57 UTC, simonLouvet commented
> Merci !
> Le code est en effet plus concis, par contre il y a un problème de bonne pratique avec RightLabel.

J'ai nettoyé et commenté (marqué not ready avant). C'est prêt pour moi. reste à affiner la question du RightLabel @srosset81

2021-04-30 12:47 UTC, srosset81 commented on src/frontend/boilerplates/archipelago/src/resources/Agent/Actor/Organization/OrganizationShow.js
> +              <ArrayField source="pair:organizationOfMembership">
Il faut que GroupedArrayField génère le label comme le fait <SimpleShowLayout>, <MainList>, <SideList>...

2021-04-30 12:53 UTC, srosset81 commented on src/frontend/boilerplates/archipelago/src/resources/Agent/Actor/Organization/OrganizationShow.js
> +              <ArrayField source="pair:organizationOfMembership">
Je trouve que c'était bien quand tu avais une prop `groupComponent`. C'était plus proche de ce qui se fait dans React-Admin. 
Pour Colibris, j'ai fait un composant `GroupedList` qui utilise aussi une props de ce genre, sauf que je l'ai appelé "header": https://github.com/reconnexion/colibris-local-groups/blob/master/src/resources/Agent/Activity/Project/ProjectList.js. Cela donne ça: https://payscreillois.colibris-groupeslocaux.org/Project

2021-04-30 13:59 UTC, srosset81 requested changes
Voir mon commentaire ci-dessus

2021-05-05 12:32 UTC, simonLouvet commented on src/frontend/boilerplates/archipelago/src/resources/Agent/Actor/Organization/OrganizationShow.js
> +              <ArrayField source="pair:organizationOfMembership">
Explications dans le 3eme example documenté : https://github.com/assemblee-virtuelle/semapps/blob/727/src/frontend/packages/semantic-data-provider/src/dataHandling/GroupedReferenceHandler.js
@srosset81

2021-05-11 12:29 UTC, merged