[dev #770] no overlap between title and actions and add title on mobi…
assemblee-virtuelle/semapps pull request #775
Opened 2021-05-22 17:43 UTC by VincentFarcy

…le mode

J'ai créé un nouveau composant TopToolbar pour y inclure le titre.

2021-05-26 13:55 UTC, srosset81 requested changes
L'implémentation est propre, bravo !

Il y a un petit problème de marges différentes pour le titre entre les pages List et les pages Show:

![Capture d’écran de 2021-05-26 15-54-00](https://user-images.githubusercontent.com/17931931/119672109-9c06bd00-be3a-11eb-9711-0a3643dd7df9.png)

![Capture d’écran de 2021-05-26 15-51-50](https://user-images.githubusercontent.com/17931931/119672182-ade86000-be3a-11eb-9087-3f5a49fb405a.png)

Par ailleurs le bouton "Créer" qui s'affichait en bas à droite sur mobile a disparu, voilà ce que ça donne sur la version en prod:

![Capture d’écran de 2021-05-26 15-54-51](https://user-images.githubusercontent.com/17931931/119672326-cfe1e280-be3a-11eb-90c2-ae5840342c70.png)

2021-05-26 13:55 UTC, srosset81 commented on src/frontend/packages/archipelago-layout/src/layout/DefaultLayout/TopToolbar.js
> +      display: props.currentView === 'list' ? 'none' : 'block'
Dommage qu'il faille passer currentView jusque là. C'est pour quoi au juste ?

2021-05-26 16:02 UTC, VincentFarcy commented
Ca m'a l'air mieux.
J'utilise currentView pour remplacer le code qui était présent dans [theme.js](https://github.com/assemblee-virtuelle/semapps/commit/c74f844a58f604e8e2b04e811d7eb68e69a50a65#diff-f46f5d3fe8756149ff02162c495cf3d5cf36a98b1202241c6a06b29dcc9628b7) pour masquer les boutons lorsque currentView = list.
Comme j'ai intégré le titre à la topToolbar, je ne peux plus la masquer entièrement comme c'était fait avant.

2021-05-26 17:24 UTC, srosset81 approved these changes
Nickel, merci !

2021-05-26 17:43 UTC, VincentFarcy commented
@srosset81 
J'ai un conflit à résoudre.
De ce que je vois, je dois juste dégager le refreshButton de ListAction.
Je suppose qu'il n'y a pas besoin de se préoccuper des fichiers index.cjs et index.es.
Ils seront regénérés de toute façon ?

2021-05-27 08:11 UTC, srosset81 commented
> @srosset81
> J'ai un conflit à résoudre.
> De ce que je vois, je dois juste dégager le refreshButton de ListAction.
> Je suppose qu'il n'y a pas besoin de se préoccuper des fichiers index.cjs et index.es.
> Ils seront regénérés de toute façon ?

Non ces fichiers ne sont malheureusement pas régénérés automatiquement (il faudrait le faire au niveau d'une Github action...).
Tu devrais accepter l'une ou l'autre version des fichiers, puis lancer `npm run build` depuis le dossier /src/frontend, ou `npm run pre-publish` depuis le package archipelago-layout.

2021-05-27 09:42 UTC, VincentFarcy commented
@srosset81 

Je pense que c'est ok mais je ne suis pas contre un dernier coup d'oeil avant de merge la pull request ;)

Voici ce que j'ai fait :
résolution des confilts (en mode web)
git pull
npm run pre-publish dans le dossier qui va bien
git add .
git commit -m "[dev #770] npm run pre-publish on package archipelago-layout"
git push

2021-05-27 10:22 UTC, srosset81 commented
Bizarre j'ai fait un `npm run build` et les fichiers .map ont encore été mis à jour. J'ai pushé. En tout cas c'est bon là. Je merge !

2021-05-27 10:22 UTC, merged