implement deletemany
assemblee-virtuelle/semapps pull request #857
Opened 2021-10-04 09:12 UTC by BastienSig

Voici la pull request pour le ticket 838 Delete many

2021-10-04 10:01 UTC, srosset81 requested changes

2021-10-04 10:01 UTC, srosset81 commented on src/frontend/packages/semantic-data-provider/src/dataProvider.js
> +      console.log('-------------------------------');
Enlever console.log

2021-10-04 10:01 UTC, srosset81 commented on src/frontend/packages/semantic-data-provider/src/dataProvider.js
> +        });
Ce serait bien d'utiliser un try/catch comme pour la méthode `getMany`.
Sinon s'il y a un problème (p.ex. une erreur de permission), une erreur globale va être retournée et on ne saura pas vraiment ce qui est effacé ou pas.
Il ne faudrait retourner que les IDs des ressources qui ont pu être effacée (voir getMany au-dessus).

2021-10-04 10:01 UTC, srosset81 commented on src/frontend/packages/semantic-data-provider/src/dataProvider.js
> +      return { data: [params.ids] };
Il ne faut pas mettre les ids dans une array car c'est déjà un array (Enlever [])
https://marmelab.com/react-admin/DataProviders.html#response-format

2021-10-06 15:10 UTC, BastienSig commented on src/frontend/packages/semantic-data-provider/src/dataProvider.js
> +      return { data: [params.ids] };
C'est fait

2021-10-06 15:19 UTC, BastienSig commented on src/frontend/packages/semantic-data-provider/src/dataProvider.js
> +        });
J'ai essayé de corriger dis moi ce que tu en pense

2021-10-06 15:20 UTC, BastienSig commented on src/frontend/packages/semantic-data-provider/src/dataProvider.js
> +      console.log('-------------------------------');
C'est fait

2021-10-07 09:37 UTC, srosset81 requested changes

2021-10-07 09:37 UTC, srosset81 commented on src/frontend/boilerplates/archipelago/package.json
> +    "@semapps/semantic-data-provider": "^0.3.7",
Pourquoi cette mise à jour de packages ?
Il faut pas rajouter de ^ devant les packages @semapps, sinon ça risque de mettre à jour le package sans qu'on le veuille (les packages ne sont pas assez stables pour que ce soit désirable).

2021-10-07 09:37 UTC, srosset81 commented on src/frontend/boilerplates/archipelago/package.json
> +    "@semapps/semantic-data-provider": "^0.3.7",
Perso j'annulerai toute ces mise à jour, car on peut avoir des surprises. Peut-être que tu as fait un `npm update` ?

2021-10-07 09:37 UTC, srosset81 commented on src/frontend/boilerplates/archipelago/src/resources/Agent/Actor/Organization/OrganizationList.js
> +            </Datagrid>
Faut pas commiter ça..... merci de regarder la PR que tu soumets avant de la mettre à review.

2021-10-07 09:37 UTC, srosset81 commented on src/frontend/boilerplates/dms/src/resources/persons.js
> +    <Datagrid >
...

2021-10-07 09:37 UTC, srosset81 commented on src/frontend/packages/semantic-data-provider/src/dataProvider.js
> +          if (returnFailedResources) {
Cette variable a du sens pour getMany. Là ça ne sert à rien. En plus returnData n'est pas utilisé.

2021-10-25 12:58 UTC, closed without merging