892 implementer la condition where de sparqljs comme filtre
assemblee-virtuelle/semapps pull request #938
Opened 2022-01-21 10:42 UTC by VincentFarcy

Voici la version du dataProvider avec sparql.js pour la v0.4
Je vais avoir besoin d'une nouvelle version alpha pour le petr.

2022-01-21 14:06 UTC, srosset81 requested changes
Je n'ai pas testé en local, mais ça m'a l'air bien, le code va être plus clean !
Quand même quelques corrections, surtout pour la lisibilité.
Si jamais tu arrives à intégrer quelques commentaires pour bien aider à comprendre ce qui se fait, je pense que ton futur toi et mon futur moi te remercieront ;-)

2022-01-21 14:06 UTC, srosset81 commented on src/frontend/packages/semantic-data-provider/src/dataProvider/utils/buildDereferenceQuery.js
> +import DataFactory from '@rdfjs/data-model';
Je pense que ça améliorerait la lisibilité du code d'importer directement les functions que tu utilises.
```js
import { variable, namedNode, ... } from '@rdfjs/data-model';
```

2022-01-21 14:06 UTC, srosset81 commented on src/frontend/packages/semantic-data-provider/src/dataProvider/utils/buildDereferenceQuery.js
> +const buildOptionalqueryForSparqljs = (queries, parentNode = false) =>
query devrait être en majuscule -> Query

2022-01-21 14:06 UTC, srosset81 commented on src/frontend/packages/semantic-data-provider/src/dataProvider/utils/buildDereferenceQuery.js
> +        },
Ca améliorerait la clareté du code et réduirait le risque d'erreur d'utiliser les `quad` exportés par @rdfjs/data-model.
La signature de la fonction est: `quad(subject, predicate, object)` (le graph, qui est le 4ème argument, est optionnel)

2022-01-21 14:06 UTC, srosset81 commented on src/frontend/packages/semantic-data-provider/src/dataProvider/utils/buildDereferenceQuery.js
>  import crypto from 'crypto';
Pourrais-tu en profiter pour remplacer cette librairie (qui normalement ne fonctionne pas côté frontend) par https://github.com/brix/crypto-js ? Cela génère des warnings au moment du build.

2022-01-21 14:06 UTC, srosset81 commented on src/frontend/packages/semantic-data-provider/src/dataProvider/utils/buildSparqlQuery.js
> +});
Les `var` ne doivent plus être utilisés.

2022-01-21 14:06 UTC, srosset81 commented on src/frontend/packages/semantic-data-provider/src/dataProvider/utils/buildSparqlQuery.js
> +          let filterOntologie = null;
filterOntologie -> filterOntology

2022-01-21 14:06 UTC, srosset81 commented on src/frontend/packages/semantic-data-provider/src/dataProvider/utils/buildSparqlQuery.js
> +import sparqljs from 'sparqljs';
sparqljs et getRdfPrefixes ne sont pas utilisés dans ce fichier.

2022-01-21 14:06 UTC, srosset81 commented on src/frontend/packages/semantic-data-provider/src/dataProvider/utils/buildDereferenceQuery.js
> +const buildDereferenceQueryStandard = predicates => {
Avons-nous vraiment besoin de garder l'ancienne version ? Je ne vois pas où c'est utilisé.

2022-01-21 14:06 UTC, srosset81 commented on src/frontend/packages/semantic-data-provider/src/dataProvider/utils/buildSparqlQuery.js
> +          }
Woah 20 lignes pour déterminer le prédicat et l'objet ! Il y aurait plein de moyen de simplifier ce code si tu veux essayer...

2022-01-21 15:05 UTC, srosset81 commented on src/frontend/packages/semantic-data-provider/src/dataProvider/utils/buildDereferenceQuery.js
>  import crypto from 'crypto';
Je l'ai fait sur ma PR #939
https://github.com/assemblee-virtuelle/semapps/pull/939/commits/40d3aa9abb7708dd789dd37a19474a440d5630d9
C'était un peu galère avec les config de rollup

2022-01-22 21:39 UTC, VincentFarcy commented on src/frontend/packages/semantic-data-provider/src/dataProvider/utils/buildDereferenceQuery.js
> +const buildDereferenceQueryStandard = predicates => {
buildDereferenceQuery est appelée ici : src/middleware/packages/ldp/utils.js
src/middleware/packages/ldp/services/container/actions/get.js
src/middleware/packages/ldp/services/resource/actions/get.js
et est exporté dans le package semantic data provider

2022-01-22 22:50 UTC, VincentFarcy commented on src/frontend/packages/semantic-data-provider/src/dataProvider/utils/buildDereferenceQuery.js
> +import DataFactory from '@rdfjs/data-model';
L'import des fonctions ne fonctionne pas directement depuis le package.
J'y suis parvenu comme ça :
```
import DataFactory from '@rdfjs/data-model';
const { literal, namedNode, quad, variable } = DataFactory;
```

2022-01-22 23:05 UTC, VincentFarcy commented on src/frontend/packages/semantic-data-provider/src/dataProvider/utils/buildDereferenceQuery.js
> +const buildOptionalqueryForSparqljs = (queries, parentNode = false) =>
c'est corrigé

2022-01-22 23:05 UTC, VincentFarcy commented on src/frontend/packages/semantic-data-provider/src/dataProvider/utils/buildDereferenceQuery.js
> +        },
c'est fait

2022-01-22 23:06 UTC, VincentFarcy commented on src/frontend/packages/semantic-data-provider/src/dataProvider/utils/buildSparqlQuery.js
> +});
c'est corrigé

2022-01-22 23:06 UTC, VincentFarcy commented on src/frontend/packages/semantic-data-provider/src/dataProvider/utils/buildSparqlQuery.js
> +          let filterOntologie = null;
c'est corrigé

2022-01-22 23:06 UTC, VincentFarcy commented on src/frontend/packages/semantic-data-provider/src/dataProvider/utils/buildSparqlQuery.js
> +import sparqljs from 'sparqljs';
c'est corrigé

2022-01-23 11:42 UTC, VincentFarcy commented on src/frontend/packages/semantic-data-provider/src/dataProvider/utils/buildSparqlQuery.js
> +          }
Je suis passé à 12 lignes ;)
Le problème est la gestion des filtres "a" par rapport aux autres filtres.
J'en ai profité pour corriger la condition d'entrée dans cette partie de code qui excluait à tort les requêtes avec un filtre q,
et j'ai ajouté des commentaires.
Dis moi si c'est ok.

2022-01-23 14:44 UTC, VincentFarcy commented on src/frontend/packages/semantic-data-provider/src/dataProvider/utils/buildDereferenceQuery.js
>  import crypto from 'crypto';
J'ai repris tes modifs.
Je pense que c'est ok.

2022-01-24 11:08 UTC, srosset81 commented on src/frontend/packages/semantic-data-provider/src/dataProvider/utils/buildDereferenceQuery.js
> +const buildDereferenceQueryStandard = predicates => {
C'est un autre buildDereferenceQuery, utilisé par le middleware (comme l'indiquent tes liens ;-))
Le fait qu'il soit exporté par le package n'est pas grave. C'est un breaking change mais je ne crois pas que ça impactera quiconque.

2022-01-24 11:12 UTC, srosset81 approved these changes
Super, le code est beaucoup plus clair !
Voir juste mon commentaire ci-dessus concernant "buildDereferenceQueryStandard", qui n'est effectivement pas utile de garder.

2022-01-24 18:00 UTC, VincentFarcy commented on src/frontend/packages/semantic-data-provider/src/dataProvider/utils/buildDereferenceQuery.js
> +const buildDereferenceQueryStandard = predicates => {
ok J'ai supprimé l'ancienne version :-)

2022-01-24 20:51 UTC, merged