Basic LDP API #84
assemblee-virtuelle/semapps pull request #94
Opened 2019-12-30 10:48 UTC by simonLouvet

2019-12-31 09:15 UTC, srosset81 commented
@simonLouvet J'ai trouvé le problème. En fait c'est pas un bug, la doc dit:
> When using multiple routes you should explicitly set the body parser(s) for each route.
https://moleculer.services/docs/0.13/moleculer-web.html#Multiple-routes

J'ai fait la correction directement sur la branche, ça marche bien.
Bizarre d'obliger de mettre un paramètre qui est par défaut lorsqu'on a qu'une seule route !

2019-12-31 10:07 UTC, simonLouvet commented
Top, merci

2020-01-07 11:10 UTC, srosset81 requested changes
Merci pour le travail !
Quelques remarques générales en plus des points ci-dessous:
- Je pense que ce serait beaucoup plus clair de parler de "ressource" (resource en anglais) que de "subject". C'est le terme utilisé dans les spécifications LDP.
- Si on fait un GET sur une ressource qui n'existe pas (http://localhost:3000/ldp/as:Note/unknown), on a un 200 en retour, alors qu'on devrait avoir un 404. Même chose pour DELETE.
- Il faudrait se mettre d'accord sur un header `Accept` par défaut, afin qu'on puisse notamment voir les ressources depuis un browser. Je crois que, pour les specs LDP, c'est le format turtle qui est privilégié.

2020-01-07 11:10 UTC, srosset81 commented on src/middleware/packages/ldp/index.js
> +      console.log(result);
console.log

2020-01-07 11:10 UTC, srosset81 commented on src/middleware/packages/ldp/index.js
> +      const contains = graph == undefined ? (Object.keys(other).length === 0 ? [] : [other]) : graph;
Cela peut être simplifié comme ça :
```suggestion
      const contains = graph || (Object.keys(other).length === 0 ? [] : [other]);
```

2020-01-07 11:10 UTC, srosset81 commented on src/middleware/packages/ldp/index.js
> +          	?suject rdf:type ${ctx.params.typeURL} ;
?suject -> ?subject (à plusieurs endroits)

2020-01-07 11:10 UTC, srosset81 commented on src/middleware/packages/ldp/index.js
> +      // body.type=typeURL;
Enlever le commentaire

2020-01-07 11:10 UTC, srosset81 commented on src/middleware/packages/triplestore/index.js
> +            { <${params.uri}> ?p ?v }
Tu peux simplifier la requête comme ça:
```
DELETE
WHERE
{ <${params.uri}> ?p ?v }
```

2020-01-07 11:10 UTC, srosset81 commented on src/middleware/packages/triplestore/index.js.orig
> +>>>>>>> c7889463d927255e16c9f8cac9c09c8dfb0a4487
STP effacer les deux fichiers index.js.orig (ou ne pas les commiter)

2020-01-07 11:10 UTC, srosset81 commented on src/middleware/packages/triplestore/index.js
> +        typeof params.resource === 'string' || params.resource instanceof String
Pourquoi ne plus se baser sur le `params.accept` ? Là je trouve que le code n'est pas clair.
Si on estime que le paramètre accept n'est pas nécessaire, alors il faut le retirer des appels à `triplestore.insert` et peut-être utiliser un boolean `isTriple` qui aidera à comprendre ce qui se passe dans cette fonction.

2020-01-07 11:10 UTC, srosset81 commented on src/middleware/packages/ldp/index.js
> +      return prefix;
Les bonnes pratiques JS recommandent de privilégier les méthodes Array plutôt que les boucles `for ... of` lorsque c'est possible. C'est plus court et généralement plus lisible :
```js
return this.settings.ontologies
           .map(ontology => `PREFIX ${ontology.prefix}: <${ontology.url}>`)
           .join('\n');
```

2020-01-07 11:10 UTC, srosset81 commented on src/middleware/packages/ldp/index.js
> +        const textStream = require('streamify-string')(JSON.stringify(jsonLdObject));
Tu as ajouté un `const streamifyString = require('streamify-string')` en haut du fichier, je pense que ce serait plus clair de l'utiliser.

2020-01-07 11:10 UTC, srosset81 commented on src/middleware/packages/ldp/index.js
> +    async serializeFromJsonldObject(jsonLdObject, outputContentType) {
Le `async` est inutile puisque tu utilises une promise.
Par ailleurs, ne serait-il pas plus clair de nommer cette fonction `jsonldToTriples` ? Le mot `serialize` peut dire beaucoup de choses.

2020-01-07 16:31 UTC, simonLouvet reviewed
@srosset81  J'ai pris en compte toutes tes review y compris les globales sauf celle-ci
https://github.com/assemblee-virtuelle/semapps/pull/94#discussion_r363691376

2020-01-07 16:31 UTC, simonLouvet commented on src/middleware/packages/ldp/index.js
> +          	?suject rdf:type ${ctx.params.typeURL} ;
exact

2020-01-07 16:31 UTC, simonLouvet commented on src/middleware/packages/ldp/index.js
> +      console.log(result);
:-(

2020-01-07 16:31 UTC, simonLouvet commented on src/middleware/packages/ldp/index.js
> +      // body.type=typeURL;
++

2020-01-07 16:31 UTC, simonLouvet commented on src/middleware/packages/ldp/index.js
> +      return prefix;
++

2020-01-07 16:31 UTC, simonLouvet commented on src/middleware/packages/ldp/index.js
> +    async serializeFromJsonldObject(jsonLdObject, outputContentType) {
++ mais c'est pas seulement vers des triples, ca supporte aussi turtle

2020-01-07 16:31 UTC, simonLouvet commented on src/middleware/packages/ldp/index.js
> +        const textStream = require('streamify-string')(JSON.stringify(jsonLdObject));
++ boulette

2020-01-07 16:31 UTC, simonLouvet commented on src/middleware/packages/triplestore/index.js
> +        typeof params.resource === 'string' || params.resource instanceof String
Le accept indique le type de retour et non le type d'entrée. Ca serrait comparable à un "content-type". Je voulais en parler avec vous mais la solution simple de tester si c'est un objet ou une string convient pour du court terme. Je pense qu'il faut passer le "content-type" en paramètre pour préciser la nature de la donnée entrante. Comme pour la lib rdf-Parse de  Ruben Taelman.

2020-01-07 16:31 UTC, simonLouvet commented on src/middleware/packages/triplestore/index.js.orig
> +>>>>>>> c7889463d927255e16c9f8cac9c09c8dfb0a4487
++, a ajouter dans le .gitignore

2020-01-07 17:40 UTC, srosset81 commented on src/middleware/packages/triplestore/index.js
> +        typeof params.resource === 'string' || params.resource instanceof String
Effectivement c'est différent ! Du coup effectivement un paramètre contentType serait cohérent. Et peut-être que `ACCEPT_TYPES` pourrait être renommé `FORMAT_TYPES`.

2020-01-07 17:40 UTC, srosset81 approved these changes
:+1:

2020-01-07 17:41 UTC, srosset81 commented on src/middleware/packages/triplestore/index.js
> +        typeof params.resource === 'string' || params.resource instanceof String
Effectivement c'est différent ! Du coup un paramètre contentType serait cohérent. Et peut-être que ACCEPT_TYPES pourrait être renommé FORMAT_TYPES.

2020-01-07 19:08 UTC, nikoPLP approved these changes

2020-01-07 20:11 UTC, merged