Change navbar with link to "cercles"
assemblee-virtuelle/semapps pull request #953
Opened 2022-02-20 12:33 UTC by fluidlog

Fusion des deux onglets "team" and "governance" avec un lien vers l'adresse https://cercles.assemblee-virtuelle.org/Circle

2022-02-20 12:35 UTC, fluidlog commented
C'est juste une première mise à jour rapide.
Ensuite, je vais gérer la traduction et supprimer les anciennes pages, mais j'y vais par petits pas.

2022-02-21 08:49 UTC, srosset81 requested changes
Je n'avais pas compris que tu voulais juste mettre un lien vers Cercle et supprimer complètement les autres pages. Pour moi il s'agissait de fusionner les pages Equipe et Gouvernance. Ce que tu proposes pourrait être une étape intermédiaire. Mais le problème c'est que l'instance "Cercles" est en français et le site web est en anglais, donc à moins de traduire OrganiGraph en anglais, cela me semble pas être une bonne solution.

2022-02-21 08:49 UTC, srosset81 commented on website/docusaurus.config.js
> +          href: 'https://cercles.assemblee-virtuelle.org/',
Il faudrait mettre un lien vers le cercle SemApps sinon les gens vont être perdus
https://cercles.assemblee-virtuelle.org/Circle/https%3A%2F%2Fdata.virtual-assembly.org%2Fprojects%2Fsemapps/show

2022-02-21 08:49 UTC, srosset81 commented on yarn.lock
> +
Fichier à supprimer, pas besoin d'avoir un yarn.lock à la racine

2022-02-22 08:40 UTC, fluidlog commented on website/docusaurus.config.js
> +          href: 'https://cercles.assemblee-virtuelle.org/',
OK, je comprends, je te propose un compromis pour avancer quand même vers une facilitation de la maintenance de ces pages (ne pas avoir du contenu erroné).
Je fusionne les deux pages en une "Governance & Team", dans laquelle je laisse en anglais (à traduire en français) les rôles explicités, et en bas, j'ajoute un lien vers les cercles dans Organigraph, ce qui évite d'avoir à maintenir en double, même si en effet, c'est en français, mais au moins, c'est dynamique.
Personnellement, ça ne me choque pas, vu qu'on entre dans l'opérationnel et qu'on est à 99% francophones...

2022-02-22 10:05 UTC, fluidlog commented on yarn.lock
> +
Bien vu, je ne sais pas pourquoi il est arriver là ! J'ai du faire une fausse manipulation en lançant un yarn à la racine au lien du répertoire /website...

2022-02-22 10:49 UTC, srosset81 commented on website/docusaurus.config.js
> +          href: 'https://cercles.assemblee-virtuelle.org/',
OK, mais tu as une idée claire sur comment fusionner les deux ? Valentine avait fait des essais qu'on retrouve sur https://github.com/assemblee-virtuelle/semapps/issues/406 mais c'était pas satisfaisant. Il faut faire quelque chose de simple et lisible, adapté à tous les écrans. Idéalement plutôt faire du React (comme la page principale) que du Markdown... A mon avis pas besoin de remettre toutes les redevabilités des rôles puisqu'elles sont sur Cercles. C'est sans doute mieux qu'on en parle par oral.

2022-02-22 10:49 UTC, srosset81 commented on yarn.lock
> +
Tu as fait un yarn install à la racine du repo oui

2022-02-22 15:08 UTC, fluidlog commented on website/docusaurus.config.js
> +          href: 'https://cercles.assemblee-virtuelle.org/',
J'ai l'idée de faire simple, de prioriser le fond plutôt que la forme, et surtout, de faire quelque chose, que nous pourrons ensuite améliorer, plutôt que d'attendre encore 6 mois qu'on se mette tous d'accord en laissant des données erronées sur le site.

2022-02-22 17:08 UTC, fluidlog commented on website/docusaurus.config.js
> +          href: 'https://cercles.assemblee-virtuelle.org/',
Suite à notre discussion, voici le PAD pour la page About, qui réunira les onglets About, Team et Governance
https://pad.lescommuns.org/Lq4zHk8hQZeel7SzlsZw_A

2022-02-24 08:36 UTC, fluidlog commented
Voilà, j'ai fait un git reset pour ne retenir que la substantifique moelle de ce que nous nous sommes dit.
Je n'ai conservé que les rôles principaux et j'ai traduit la page About en français.

2022-02-24 14:44 UTC, srosset81 commented
@fluidlog J'ai fait des corrections sur les fichiers.
Il y a encore des bugs sur les menus de guides / middleware / frontend.
https://website-git-websiteteamroles-semapps.vercel.app/docs/middleware/auth

2022-02-24 17:57 UTC, srosset81 approved these changes

2022-02-24 17:57 UTC, srosset81 commented
Parfait, merci !

2022-02-24 18:00 UTC, merged