gestion des blank nodes multiples
assemblee-virtuelle/semapps pull request #985
Opened 2022-06-03 13:47 UTC by simonLouvet

resolve https://github.com/assemblee-virtuelle/semapps/issues/862 and https://github.com/assemblee-virtuelle/semapps/issues/893

Ajout de la capacité d'affecter plusieurs blank nodes à un predicat en POST, PUT, PATCH
Refactoring de ldp create ressource en l'harmonisant avec patch et put
Ajout d'un discriminant dans les black nodes pour pouvoir gérer la suppression de plusieurs blank nodes sur le même prédicat. sans ce discriminant il est impossible de supprimer les triplets d'un black node sans affecter un autre qui possède les mêmes literaux et la surpression des ancien blank nodes lors d'un PUT échoue systématiquement car le delete (SPARQL) du premier blank node supprime également le second , provoque des triplets orphelins et fait planter la requete.
Ajout de test et debug des test ldp pour permettre leurs exécutions. les autres tests bugs toujours mais c'est hors du perimetre que je m'etais donné dsl.
Pour le PATCH, J'ai considéré un blank node comme un Literale. La présence d'un blank sur un prédicat en PATCH indique que le prédicat doit être complètement réévalué avec les black nodes passé dans la requête. Il serait possible de raisonné en considérant que les blanck node en patch se cumulent mais cela ne correspondait pas au tests existants.

2022-06-03 14:01 UTC, simonLouvet commented
3J

2022-06-09 08:29 UTC, simonLouvet commented
@srosset81 est ce que tu as pu regarder cette PR?

2022-06-21 15:23 UTC, srosset81 requested changes
Bon je ne suis pas fan de ce discriminant qui charge un code déjà très chargé, mais je conçois que ça peut être difficile de faire sans, surtout à cause des WebACL et du droit `acl:Append` qui empêche d'effacer tout puis de remplacer (pour le PUT).
Par contre le comportement de PATCH n'est pas bon, car il efface des données existantes. De plus il faut mettre des tests pour tous les cas de figure en PUT/PATCH, sinon on risque d'avoir des régressions très gênantes (avec tous les sites en production, on ne peut pas se le permettre)
Voir mes autres commentaires ci-dessous.

2022-06-21 15:23 UTC, srosset81 commented on src/middleware/tests/ldp/api.test.js
> -  broker.createService(FusekiAdminService, {
Tu peux virer les imports de tous ces services en haut du fichier

2022-06-21 15:23 UTC, srosset81 commented on src/middleware/tests/ldp/container.test.js
> +  });
Qu'est-ce qui ne marchait pas avec `broker = await initialize();` ? C'est ce qui est utilisé sur tous les autres fichiers de test et ça fait la même chose que ton code, en 1 ligne.

2022-06-21 15:23 UTC, srosset81 commented on src/middleware/tests/ldp/api.test.js
> +  apiGateway = await broker.getLocalService('api');
Ah je connaissais pas `getLocalService`, c'est pratique !
Cela dit, il faut un `const` avant apiGateway

2022-06-21 15:23 UTC, srosset81 commented on src/middleware/packages/ldp/services/resource/methods.js
> +    const disriminents = subjects.map(s => {
Il manque un "c" sur cette variable. Mais plus globalement, le mot s'écrit avec un "a" en anglais comme en français: "discriminant". A corriger partout ailleurs.

2022-06-21 15:23 UTC, srosset81 commented on src/middleware/packages/ldp/services/resource/actions/put.js
> -      const blankNodesVarsMap = this.mapBlankNodesOnVars([...oldTriples, ...newTriples]);
Si la méthode `mapBlankNodesOnVars` n'est plus nécessaire, tu peux la supprimer.

2022-06-21 15:23 UTC, srosset81 commented on src/middleware/tests/ldp/initialize.js
> +      }
Enlever les 3 lignes commentées

2022-06-21 15:23 UTC, srosset81 commented on src/middleware/tests/ldp/initialize.js
> +  // await broker.createService(ApiGatewayService);
Enlever cette ligne.

2022-06-21 15:23 UTC, srosset81 commented on src/middleware/tests/ldp/resource.test.js
> +        ]
Il faut plus de tests sur PATCH pour être sûr que ça ne casse rien de l'existant. Le PATCH ci-dessus pourrait ne contenir que `{ label: 'Nantes' }` pour hasLocation, et il devrait retourner le même résultat (Compiègne + Nantes). Il faut vérifier que PATCH n'efface jamais un blank node existant, même quand il a le même nom.

2022-06-21 15:23 UTC, srosset81 commented on src/middleware/tests/ldp/resource.test.js
> +        }
En réalité la méthode `ldp.resource.get` retourne aussi le discriminant pour chaque blank node. C'est pas conforme aux standards LDP, donc il faudrait les filtrer de GET (et vérifier dans les tests qu'ils ne sont plus là avec une ligne de type `expect(updatedProject['pair:hasLocation']['semapps:discriminant']).toBeUndefined();`).

2022-06-21 15:23 UTC, srosset81 commented on src/middleware/tests/ldp/resource.test.js
> +      },
Il faut plus de tests sur PUT pour être sûr que ça ne casse rien de l'existant. Par exemple si on enlève un élément (Nantes) ou si on en enlève 2 (Nantes et Compiègne). Ou si on ajoute un nouvel élément avec le même label.

2022-06-21 15:23 UTC, srosset81 commented on src/middleware/tests/ldp/resource.test.js
> +        ]
Après réflexion, le résultat de cette opération PATCH n'est pas bonne. Comme il y a déjà Compiègne, mais qu'on fait un PATCH avec Compiègne + Nantes, il devrait y avoir en résultat: Compiègne + Compiègne + Nantes (un PATCH ne va jamais effacer une donnée existante)
Dans la réalité, PATCH est difficile à utiliser. Pour le data provider, on utilise systématiquement PUT pour éviter ce type de problèmes.

2022-06-21 15:23 UTC, srosset81 commented on src/middleware/packages/ldp/services/resource/methods.js
> +        triple.object = variable(triple.object.value);
Ce changement de code crée des noms de variables bizarres type `?df_6_0` qui risquent d'entrer en conflits. Ne pourrait-on pas utiliser le discriminant comme nom de variable puisqu'il est maintenant associé à chaque blank node et qu'on est sûr qu'il est unique ?

2022-06-21 15:23 UTC, srosset81 commented on src/middleware/tests/ldp/resource.test.js
>      });
Comme c'est un PATCH et non un PUT, ça ne doit pas effacer "Paris, the place to be", mais retourner "Compiègnes, the place to be" + "Paris, the place to be".

2022-06-21 15:23 UTC, srosset81 commented on src/middleware/packages/ldp/services/resource/actions/put.js
> -        console.log('query', query);
OK pour supprimer ce console.log. Par contre je suggérerai d'utiliser `this.logger.debug('PUT query', query)`. Et faire de même pour POST et PATCH. Ca resterait cacher en mode normal, mais permettrait de facilement débugger les requêtes en mettant le logLevel de Moleculer à "debug". Qu'en penses-tu ?

2022-06-27 08:04 UTC, srosset81 commented on src/middleware/tests/ldp/resource.test.js
> +        ]
Nouvelle réflexion du weekend: en fait même la `pair:description` ne devrait pas être écrasée avec un PATCH. Si on a une `pair:description: "myProject"` et qu'on fait un patch avec `pair:description: "myProjectUpdated"`, le résultat devrait être : `pair:description: ["myProject", "myProjectUpdated"]`. Le premier triplet est préservé et on ajoute un deuxième triplet. Aucune donnée n'est écrasée. Encore une fois, ça rend PATCH très difficilement utilisable, sauf pour des opérations de type "Append" (et là encore, pour le semantic data provider, j'ai préféré utilisé PUT).
Sur des endpoints REST classiques, PATCH peut remplacer une valeur existante. Mais pour du LDP, je ne vois pas comment ça serait possible, car on ne sait pas si `pair:description` est supposé n'avoir qu'une seule valeur, ou si il peut y en avoir plusieurs (auxquels cas ça apparait comme un array en JSON-LD). Il faudrait qu'on s'appuie sur des formes SHACL ou SHEX pour le déterminer, mais ça rajoute une couche de dépendence.
J'ai regardé la spec LDP et ils parlent très peu de PATCH. Ils disent surtout que PATCH est optionnel: un serveur LDP n'est pas obligé de l'implémenter. Actuellement, le semantic data provider n'utilise jamais PATCH, mais toujours PUT. Peut-être qu'on pourrait envisager d'enlever l'implémentation ?

2022-06-27 08:33 UTC, nikoPLP commented on src/middleware/tests/ldp/resource.test.js
> +        ]
la Spec LDP dit en effet que c'est optionel, et dans les discussions chez Solid, il semble que la seule manière de faire un PATCH est en envoyant du sparql-update. C'est ce que j'ai fait pour le PATCH du container. Le content-type du body doit etre du "SPARQL UPDATE". Ca permet de bien différencier les INSERTs et les DELETEs. 
Si vous voulez quand meme offrir la possibilité d'envoyer du JSON-LD au PATCH d'une resource (ce que Inrupt ne fait pas), alors considérons que le contenu JSON-LD concerne des INSERTs. C'est donc bien ce que @srosset81 vient de dire : on ajoute les triples et c'est tout.
Si vous voulez implementer le contentType sparql-update pour les PATCH sur les resources, vous pouvez regarder ce que j'ai fait pour les containers.

2022-06-27 09:27 UTC, srosset81 commented on src/middleware/tests/ldp/resource.test.js
> +        ]
Après discussions privées avec @nikoPLP, je comprend que Solid a prévu de revoir les specs LDP en précisant qu'il faut utiliser du "SPARQL UPDATE" pour les opérations PATCH. Le code qu'on a actuellement va peut-être devenir obsolète. Cela me conforte dans l'idée de supprimer la méthode PATCH pour le moment, et de voir dans le futur si on implémente "SPARQL UPDATE" aussi pour les ressources.

2022-06-27 09:57 UTC, simonLouvet commented on src/middleware/tests/ldp/resource.test.js
> +        ]
@srosset81 Je suis assez d'accord pour l'enlever. Cette méthode mal spécifiée implique des interprétations qui déclenchent des débats interne dont nous pouvons nous passer. La supprimer ne changera rien à nos usages et  nous rajoute de la charge et des concertations inutiles.

2022-07-04 09:00 UTC, srosset81 commented
@simonLouvet Pour info, je pars en vacances le 13 juillet mais je compte finir de travailler cette semaine. Si tu veux que ce soit mergé avant mon retour (fin août), il faudrait faire les corrections prochainement.

2022-07-04 09:02 UTC, srosset81 commented on src/middleware/tests/ldp/resource.test.js
> +        }
J'ai réalisé ce weekend que peut-être si le discriminant est retourné, c'est parce qu'il est utilisé lors de l'opération PUT ? Je croyais que le discriminant était quelque chose qui était seulement utilisé en interne. Mais si c'est quelque chose qui ressort en GET et qu'on doit retourner en PUT pour que ça marche, alors je suis opposé à cette "solution", car on est complètement hors standard. Mais je me trompe peut-être...

2022-07-04 09:03 UTC, srosset81 commented
@simonLouvet Par ailleurs j'ai ajouté un commentaire important: [relayOutboxUri](https://github.com/assemblee-virtuelle/semapps/pull/985#discussion_r912787310)

2022-07-04 09:38 UTC, simonLouvet commented on src/middleware/tests/ldp/resource.test.js
> +        }
non, l'objectif est bien que ce soit une gestion interne. C'est d'autant plus vrai si on PATCH ne peut que ajouter des blanck node ou s'il est supprimé en attendant la spec. Par contre si nous voulons un jour permettre à un PATCH de modifier un blanck node, le client devra connaitre le discriminant : je ne voie aucune autre solution théorique/fondamentale.

2022-07-04 09:39 UTC, simonLouvet commented
> @simonLouvet Par ailleurs j'ai ajouté un commentaire important: [#985 (comment)](https://github.com/assemblee-virtuelle/semapps/pull/985#discussion_r912787310)

répondu dans le commentaire

2022-07-04 10:01 UTC, srosset81 commented on src/middleware/tests/ldp/resource.test.js
> +        }
On a décidé de supprimer la méthode PATCH pour le moment, donc je ne pense pas qu'il soit utile d'en parler ici. Qu'en est-il de la méthode PUT ? Faut-il passer le discriminant pour éviter qu'on supprime et rajoute la même donnée ?

2022-07-04 10:28 UTC, simonLouvet commented on src/middleware/tests/ldp/resource.test.js
> +        }
Si on continue de concevoir le PUT comme un totale remplacement de la ressource, il y a suppression de tous les blanck nodes et création des nouveaux donc pas besoin que le client connaisse le discriminant.
Je compte supprimer le PATCH dans cette PR.

2022-07-04 12:33 UTC, srosset81 commented on src/middleware/tests/ldp/resource.test.js
> +        }
Non PUT ne doit supprimer que les triplets qui ne sont pas dans la nouvelle ressource, et n'ajouter que ceux qui sont nouveaux. Ca permet de gérer le droit `acl:Append` proprement. Sinon on se serait pas embêté à faire tous ces calculs dans l'action PUT.

2022-07-04 12:36 UTC, srosset81 commented on src/middleware/tests/ldp/resource.test.js
> +        }
Ne pourrait-on pas générer le discriminant automatiquement en faisant un JSON.stringify du contenu du blank node ? Comme ça ça serait facile de voir si le blank node est nouveau ou s'il existe déjà.

2022-07-04 22:12 UTC, simonLouvet commented on src/middleware/tests/ldp/resource.test.js
> +        }
@srosset81 , je crois qu'il y a confusion avec PATCH car la recommandation pour PUT est très claire : 4.2.4.1 If a HTTP PUT is accepted on an existing resource, [LDP servers](https://www.w3.org/TR/ldp/#dfn-ldp-server) must replace the entire persistent state of the identified resource with the entity representation in the body of the request.

2022-07-04 22:16 UTC, simonLouvet commented on src/middleware/tests/ldp/resource.test.js
> +        }
> a ça serait facile de voir si le blank nod

Je vais expérimenter la normalisation/canonisation comme vu par chat pour résoudre le problème différemment que avec le discriminant. Générer un discriminant par du stringify ou un id ne change pas grand chose de mon point de vue. quel différence pour toi?

2022-07-05 05:46 UTC, srosset81 commented on src/middleware/tests/ldp/resource.test.js
> +        }
> @srosset81 , je crois qu'il y a confusion avec PATCH car la recommandation pour PUT est très claire : 4.2.4.1 If a HTTP PUT is accepted on an existing resource, [LDP servers](https://www.w3.org/TR/ldp/#dfn-ldp-server) must replace the entire persistent state of the identified resource with the entity representation in the body of the request.

Oui PUT remplace la donnée, mais nous avons besoin qu'il y ait un diff précis pour que le droit `acl:Append` fonctionne bien ! Pourquoi est-ce si compliqué à comprendre ?

2022-07-05 05:47 UTC, srosset81 commented on src/middleware/tests/ldp/resource.test.js
> +        }
> > a ça serait facile de voir si le blank nod
> 
> Je vais expérimenter la normalisation/canonisation comme vu par chat pour résoudre le problème différemment que avec le discriminant. Générer un discriminant par du stringify ou un id ne change pas grand chose de mon point de vue. quel différence pour toi?

Avec la canonisation, tu n'as plus besoin de générer manuellement un discriminant, puis la canonisation en fournit un. Mon commentaire concernant le stringify n'a donc plus de sens.

2022-07-05 07:32 UTC, simonLouvet commented on src/middleware/tests/ldp/resource.test.js
> +        }
> Oui PUT remplace entièrement la donnée, mais nous avons besoin qu'il y ait un diff précis pour que le droit `acl:Append` fonctionne bien au moment de l'insert dans le triple store ! Pourquoi est-ce si compliqué à comprendre ?

C'est par ce que je ne dois pas être assez intelligent. Effectivement nous ne supprimons pas les triplet qui n'ont pas changé ```const triplesToRemove = this.getTriplesDifference(oldTriples, newTriples);```. Je ne connais pas le rapport avec le ```acl:Append```.  Aurais tu 5 min ce mardi pour par visio/tel/chat pour expliciter stp. tu parles bien de ```acl:Append``` sur la ressource? Qu'est ce qui se passerait si on supprimait tous les triplet pour les réinsérer dans faire de diff?

2022-07-05 07:53 UTC, srosset81 commented on src/middleware/tests/ldp/resource.test.js
> +        }
Si un utilisateur n'a qu'un droit `acl:Append` mais pas `acl:Write`, il peut ajouter des triplets (INSERT) mais pas en supprimer (DELETE). Du coup avec un tel utilisateur tu demandes de tout supprimer les triplets existants, puis d'ajouter les nouveaux, il y aura **toujours** une erreur de permission. Alors que si tu fais un diff, et que de ce diff il ressort qu'il y a des triplets à ajouter (`triplesToAdd`) mais pas à supprimer (`triplesToRemove`), alors il n'y aura pas d'erreur de permission.

2022-07-05 08:05 UTC, simonLouvet commented on src/middleware/tests/ldp/resource.test.js
> +        }
@srosset81 ok je comprends mieux et je suis d'accord dans l’état actuel. J'ai pas contre un gros doute sur notre implémentation du PUT étant donnée la recommandation W3C. Elle mentionne explicitement un que le PUT droit remplacer l'entité entière et donc cela voudrait dire que un utilisateur qui n'a pas de droit de ```acl:write``` ne devrait pas pouvoir modifier cette ressource. Je garde ca en tête et je créé une issue pour en discuter si je trouve cela pertinent.

2022-07-05 08:17 UTC, srosset81 commented on src/middleware/tests/ldp/resource.test.js
> +        }
Au niveau du frontend, on utilise toujours PUT, jamais PATCH, à cause des problèmes dont on a déjà largement discuté. Et cela même quand on propose un simple ajout de relations comme avec la nouvelle modale. Si on ne permet pas une gestion fine du PUT, alors le droit `acl:Append` devient **INUTILISABLE**.

2022-10-20 15:46 UTC, simonLouvet commented
Seb : 
La librairie jsonld.js qu'on utilise déjà (dans le service jsonld) a une fonction canonize (qui s'appuie sur https://github.com/digitalbazaar/rdf-canonize)
https://github.com/digitalbazaar/jsonld.js
Sur le playground JSON-LD, on peut tester cette fonction (normalized):
https://json-ld.org/playground/
En entrant les données de https://data.virtual-assembly.org/users/alice.poggioli, j'obtiens ça:
[https://json-ld.org/playground/#startTab=tab-normalized&json-ld={"@context":"https://data.virtual-assembly.org/context.json","id":"https://data.virtual-assembly.org/users/alice.poggioli","type":["foaf:Person","pair:Person"],"og:leads":["https://data.virtual-assembly.org/groups/valorisation","https://data.virtual-assembly.org/groups/partenaires","https://data.virtual-assembly.org/groups/financement"],"pair:affiliatedBy":["https://data.virtual-assembly.org/organizations/assemblee_virtuelle","https://data.virtual-assembly.org/organizations/startin-blox1","https://data.virtual-assembly.org/groups/onboarding"],"pair:assigneeOf":"https://data.virtual-assembly.org/tasks/partager-la-campagne-de-don-de-l-av","pair:e-mail":"alice.poggioli@hotmail.fr","pair:firstName":"Alice","pair:hasLocation":{"type":"pair:Place","pair:hasPostalAddress":{"type":"pair:PostalAddress","pair:addressCountry":"France","pair:addressLocality":"Athis-Val de Rouvre"},"pair:label":"Athis-Val de Rouvre, Orne, France","pair:latitude":48.8106,"pair:longitude":-0.5005},"pair:hasTopic":["https://data.virtual-assembly.org/themes/mise_en_reseau","https://data.virtual-assembly.org/themes/apero"],"pair:involvedIn":"https://data.virtual-assembly.org/events/10-ans-de-l-assemblee-virtuelle-residence","pair:label":"Alice POGGIOLI","pair:lastName":"Poggioli","pair:offers":["https://data.virtual-assembly.org/skills/_web_semantique","https://data.virtual-assembly.org/skills/animation_de_communaute","https://data.virtual-assembly.org/skills/developpement_web"],"inbox":"https://data.virtual-assembly.org/users/alice.poggioli/inbox","foaf:email":"alice.poggioli@hotmail.fr","foaf:familyName":"Poggioli","foaf:name":"Alice","foaf:nick":"alice.poggioli","followers":"https://data.virtual-assembly.org/users/alice.poggioli/followers","following":"https://data.virtual-assembly.org/users/alice.poggioli/following","image":"https://data.virtual-assembly.org/files/alice-poggioli.jpeg","name":"Alice Poggioli","outbox":"https://data.virtual-assembly.org/users/alice.poggioli/outbox","preferredUsername":"alice.poggioli"}](https://json-ld.org/playground/#startTab=tab-normalized&json-ld=%7B%22%40context%22%3A%22https%3A%2F%2Fdata.virtual-assembly.org%2Fcontext.json%22%2C%22id%22%3A%22https%3A%2F%2Fdata.virtual-assembly.org%2Fusers%2Falice.poggioli%22%2C%22type%22%3A%5B%22foaf%3APerson%22%2C%22pair%3APerson%22%5D%2C%22og%3Aleads%22%3A%5B%22https%3A%2F%2Fdata.virtual-assembly.org%2Fgroups%2Fvalorisation%22%2C%22https%3A%2F%2Fdata.virtual-assembly.org%2Fgroups%2Fpartenaires%22%2C%22https%3A%2F%2Fdata.virtual-assembly.org%2Fgroups%2Ffinancement%22%5D%2C%22pair%3AaffiliatedBy%22%3A%5B%22https%3A%2F%2Fdata.virtual-assembly.org%2Forganizations%2Fassemblee_virtuelle%22%2C%22https%3A%2F%2Fdata.virtual-assembly.org%2Forganizations%2Fstartin-blox1%22%2C%22https%3A%2F%2Fdata.virtual-assembly.org%2Fgroups%2Fonboarding%22%5D%2C%22pair%3AassigneeOf%22%3A%22https%3A%2F%2Fdata.virtual-assembly.org%2Ftasks%2Fpartager-la-campagne-de-don-de-l-av%22%2C%22pair%3Ae-mail%22%3A%22alice.poggioli%40hotmail.fr%22%2C%22pair%3AfirstName%22%3A%22Alice%22%2C%22pair%3AhasLocation%22%3A%7B%22type%22%3A%22pair%3APlace%22%2C%22pair%3AhasPostalAddress%22%3A%7B%22type%22%3A%22pair%3APostalAddress%22%2C%22pair%3AaddressCountry%22%3A%22France%22%2C%22pair%3AaddressLocality%22%3A%22Athis-Val%20de%20Rouvre%22%7D%2C%22pair%3Alabel%22%3A%22Athis-Val%20de%20Rouvre%2C%20Orne%2C%20France%22%2C%22pair%3Alatitude%22%3A48.8106%2C%22pair%3Alongitude%22%3A-0.5005%7D%2C%22pair%3AhasTopic%22%3A%5B%22https%3A%2F%2Fdata.virtual-assembly.org%2Fthemes%2Fmise_en_reseau%22%2C%22https%3A%2F%2Fdata.virtual-assembly.org%2Fthemes%2Fapero%22%5D%2C%22pair%3AinvolvedIn%22%3A%22https%3A%2F%2Fdata.virtual-assembly.org%2Fevents%2F10-ans-de-l-assemblee-virtuelle-residence%22%2C%22pair%3Alabel%22%3A%22Alice%20POGGIOLI%22%2C%22pair%3AlastName%22%3A%22Poggioli%22%2C%22pair%3Aoffers%22%3A%5B%22https%3A%2F%2Fdata.virtual-assembly.org%2Fskills%2F_web_semantique%22%2C%22https%3A%2F%2Fdata.virtual-assembly.org%2Fskills%2Fanimation_de_communaute%22%2C%22https%3A%2F%2Fdata.virtual-assembly.org%2Fskills%2Fdeveloppement_web%22%5D%2C%22inbox%22%3A%22https%3A%2F%2Fdata.virtual-assembly.org%2Fusers%2Falice.poggioli%2Finbox%22%2C%22foaf%3Aemail%22%3A%22alice.poggioli%40hotmail.fr%22%2C%22foaf%3AfamilyName%22%3A%22Poggioli%22%2C%22foaf%3Aname%22%3A%22Alice%22%2C%22foaf%3Anick%22%3A%22alice.poggioli%22%2C%22followers%22%3A%22https%3A%2F%2Fdata.virtual-assembly.org%2Fusers%2Falice.poggioli%2Ffollowers%22%2C%22following%22%3A%22https%3A%2F%2Fdata.virtual-assembly.org%2Fusers%2Falice.poggioli%2Ffollowing%22%2C%22image%22%3A%22https%3A%2F%2Fdata.virtual-assembly.org%2Ffiles%2Falice-poggioli.jpeg%22%2C%22name%22%3A%22Alice%20Poggioli%22%2C%22outbox%22%3A%22https%3A%2F%2Fdata.virtual-assembly.org%2Fusers%2Falice.poggioli%2Foutbox%22%2C%22preferredUsername%22%3A%22alice.poggioli%22%7D)
A voir si ça peut convenir pour le diff des blank nodes...

2022-10-20 17:12 UTC, srosset81 commented
> With jsonld.js (https://github.com/digitalbazaar/jsonld.js), a normalize API call is available that will convert a JSON-LD document to normalized N-Quads using the RDF Graph Normalization Algorithm (http://json-ld.org/spec/latest/rdf-graph-normalization/). The result can be diffed using a standard text-based diffing tool.
> Note that these tools can also convert N-Triples or N-Quads into JSON-LD, which can then be converted to normalized N-Quads. It is also important to note that the RDF Graph Normalization Algorithm will canonically name all blank nodes.

https://www.w3.org/2001/sw/wiki/How_to_diff_RDF

2022-10-25 01:19 UTC, simonLouvet commented on src/middleware/packages/ldp/services/resource/methods.js
> +        triple.object = variable(triple.object.value);
je n'ai pas trouvé la preuve que rdf-parse produit de identifiants unique de blanck node mais c'est fortement probable. ok pour utiliser les identifiant de blanck node de la canonisation

2022-10-26 05:41 UTC, simonLouvet commented
replaced by #1068

2022-10-26 05:41 UTC, closed without merging