698 ldp patch import resource one by one
assemblee-virtuelle/semapps pull request #987
Opened 2022-06-05 23:07 UTC by nikoPLP

Le service de mirroir fonctionne. vous voulez le tester?
merci de lire la doc ici avant de tester:
website/docs/middleware/mirror.md

this PR implements/fixes #517 #849 #850 #698

2022-06-13 16:32 UTC, simonLouvet commented on src/middleware/packages/ldp/services/resource/actions/create.js
> +      resource: contentType === MIME_TYPES.JSON ? resource : resource.body,
ce n'est pas censé être nécessaire. Un middleware devrait exister pour que la ressource soit dans l'objet resource et non resource.body.

2022-06-13 16:32 UTC, simonLouvet commented on src/middleware/packages/ldp/services/resource/actions/patch.js
> +      let newTriples = await this.bodyToTriples(body || resource, contentType);
je prefereai que ce soit unifié

2022-06-13 16:32 UTC, simonLouvet commented on src/middleware/packages/middlewares/index.js
> +    req.$params.body = await getRawBody(req);
je préfererai que ce soit dans  $params.resource

2022-06-20 16:07 UTC, srosset81 requested changes
Merci !!  Pas mal de commentaire ci-dessous, désolé pour la longueur mais la PR est conséquente ! :-P
J'ai testé l'endpoint VOID, le miroir en local, ainsi que l'import des données uniques via PATCH.
Sinon problème de migration comme dit en privé.
Fait un `git pull` car j'ai dû harmoniser les versions des packages SemApps afin que le yarn link fonctionne correctement.

2022-06-20 16:07 UTC, srosset81 commented on src/middleware/packages/ldp/services/container/actions/get.js
> +              //console.error('Error requesting resource: ', resourceUri, e);
Ce serait mieux de garder cette ligne, elle est utile pour du debugging.

2022-06-20 16:07 UTC, srosset81 commented on src/middleware/packages/ldp/services/container/actions/patch.js
> +      //const { controlledActions } = await ctx.call('ldp.registry.getByUri', { containerUri });
Si on ne permet pas à PATCH d'être une action controllée (ce qui ne semble pas nécessaire), on peut supprimer cette ligne.

2022-06-20 16:07 UTC, srosset81 commented on src/middleware/packages/ldp/services/container/actions/patch.js
> +        //Link: '<http://www.w3.org/ns/ldp#Resource>; rel="type"',
Supprimer commentaire

2022-06-20 16:07 UTC, srosset81 commented on src/middleware/packages/ldp/services/container/actions/patch.js
> +                    // fail silently
Un `this.logger.warn` serait utile pour le debugging

2022-06-20 16:07 UTC, srosset81 commented on src/middleware/packages/ldp/services/registry/index.js
> +        await this.actions.register(container);
Le commentaire au-dessus peut être supprimé puisqu'on await

2022-06-20 16:07 UTC, srosset81 commented on src/middleware/packages/ldp/services/registry/index.js
> +            parentContainerUri = urlJoin(parentContainerUri, '/');
Est-ce que tu as testé ça ? Je suis pas sûr que urlJoin garde le slash final dans ce cas.
Voir par exemple https://github.com/jfromaniello/url-join/issues/10
Sinon mieux vaut garder le code existant, qui fonctionnait bien (après plusieurs problèmes)

2022-06-20 16:07 UTC, srosset81 commented on src/middleware/packages/ldp/services/resource/index.js
> +      rule: '0 * * * * *',
Comme il y a 6 champs, le premier est pour les secondes (https://www.npmjs.com/package/node-schedule). Ca me semble excessif de faire une mise à jour toutes les minutes, sachant qu'il peut y avoir des centaines, voire des milliers de ressources à vérifier. Toutes les heures serait mieux.

2022-06-20 16:07 UTC, srosset81 commented on src/middleware/packages/ldp/services/resource/methods.js
> +          { resource: { id: resourceUri }, body: newResource, webId: 'system', contentType: MIME_TYPES.TURTLE },
Normalement on devrait passer `newResource` via le paramètre `resource`. Si tu as besoin de garder l'URI, peut-être ajouter un paramètre explicite genre `forceUri` ? Ou sinon peut-être que l'URI peut être trouvé à partir du triplet orphanMirroredResource ?

2022-06-20 16:07 UTC, srosset81 commented on src/middleware/packages/ldp/services/void/index.js
> +          services.filter(s => s.name == 'sparqlEndpoint').length > 0
Ah c'est un bon moyen de tester si un service est configuré ! Je l'avais jamais utilisé.

2022-06-20 16:07 UTC, srosset81 commented on src/middleware/packages/mirror/index.js
> +    await this.broker.waitForServices(['ldp.container', 'ldp.registry', 'auth.account', 'activitypub.follow']);
Comme tu les as mis comme dependencies, ce n'est pas nécessaire (started ne sera pas appelé avant que ces services soient lancés)

2022-06-20 16:07 UTC, srosset81 commented on src/middleware/packages/mirror/index.js
> +    const uri = urlJoin(this.settings.baseUrl, '/users', actorSettings.username);
Le container n'est pas forcément `/users`. Il faudrait soit avoir un setting `usersContainer` pour ce service, soit trouver le container via le service ldp.registry en matchant `acceptedType === "Application"`

2022-06-20 16:07 UTC, srosset81 commented on src/middleware/packages/mirror/index.js
> +    } while (!this.relayOutboxUri);
Il y a une action `activitypub.actor.awaitCreateComplete` qui gère ça tout seul et retourne l'acteur complet.

2022-06-20 16:07 UTC, srosset81 commented on src/middleware/packages/mirror/index.js
> +        // A will only mirror what is proper to B, not the mirrored data of C
C'est le fonctionnement attendu en effet :+1:

2022-06-20 16:07 UTC, srosset81 commented on src/middleware/packages/mirror/index.js
> +      // the container update will retrieve the new resource anyway
Je comprends que ça fonctionne comme ça, mais pour moi c'est quand même un problème, parce qu'en terme ontologique, une activité `Create` est différente d'une activité `Update`. Dans le futur, l'acteur Relay sera peut-être utilisé pour d'autres choses (d'ailleurs il faudra peut-être l'extraire du service miror) et il sera important qu'on puisse différencier les deux activités. Donc je garderai les deux et tant pis pour la redondance (bizarre que l'attachement au container génère une activité Update tout de même ?)

2022-06-20 16:07 UTC, srosset81 commented on src/middleware/packages/mirror/index.js
> +        to: await this.getFollowers()
Tu peux juste mettre `urlJoin(this.relayActorUri, 'followers')` et le service ActivityPub saura qu'il dispatcher à tous les followers. Cela permettra aussi d'avoir une activité plus compacte.

2022-06-20 16:07 UTC, srosset81 commented on src/middleware/packages/mirror/package.json
> +    "@semapps/auth": "0.4.0-alpha.30",
Il ne faut mettre en dépendence que les packages que tu importes vraiment avec `require`. Les dépendences via Moleculer n'ont pas besoin d'être mises ici.

2022-06-20 16:07 UTC, srosset81 commented on src/middleware/packages/webacl/services/resource/actions/setRights.js
> +          defaultRemovePublicRead
Est-ce que `defaultAddPublicRead` et `defaultRemovePublicRead` prennent en compte le fait qu'il peut y avoir plusieurs sous-containers, et que le droit par défaut peut être donné au root container p.ex. ?

2022-06-20 16:07 UTC, srosset81 commented on src/middleware/packages/webacl/services/resource/actions/setRights.js
> +          defaultRemovePublicRead
Je trouve le nom des 4 nouveaux params envoyés pas clair, et je suis pas sûr qu'on va comprendre pourquoi il faut envoyer tout ça avec l'event. Ne pourrais-tu juste pas juste appeler `webacl.resource.getRights` à réception de l'event pour obtenir ces informations ? Cela me semblerait être plus cohérent avec la philosophie des microservices, où chaque service s'occupe d'obtenir les informations dont il a besoin.

2022-06-20 16:07 UTC, srosset81 commented on website/docs/middleware/ldp/container.md
> +| `contentType` | `String` | **optional** | must be `application/sparql-update`) |
Je suis pas vraiment fan de ce format SPARQL UPDATE (qui me semble être une abérration), mais j'imagine qu'il y a aucun autre moyen de gérer ça de manière standard... Tant pis ! :-)

2022-06-20 16:07 UTC, srosset81 commented on website/docs/middleware/mirror.md
> +---
Il faut que tu ajoutes ce fichier dans `/website/sidebars.js` sinon il n'apparaîtra nulle part.

2022-06-20 16:07 UTC, srosset81 commented on src/middleware/packages/mirror/index.js
> +    } while (!this.relayOutboxUri);
Même chose pour le code juste en dessous de celui-ci.

2022-06-20 16:07 UTC, srosset81 commented on src/middleware/packages/mirror/index.js
> +        to: await this.getFollowers()
Je recommande aussi de mettre `https://www.w3.org/ns/activitystreams#Public` (tu peux l'importer en tant que constante PUBLIC_URI du package @semapps/activitypub) dans le `to`, afin que n'importe qui puisse voir les mises à jour dans l'inbox (si les WebACL sont activés, seuls les activités publiques ont un droit Read anonyme)

2022-06-20 16:07 UTC, srosset81 commented on src/middleware/packages/ldp/services/void/index.js
> +  name: 'ldp.void',
Il faut que le service VOID soit dans un package indépendant, comme prévu initialement. Le fait qu'il ait une forte dépendence au service LDP n'est pas un problème, la plupart des services ont de fortes dépendences à d'autres services. VOID est un service que pas tous les serveurs SemApps voudront utiliser et donc ça n'a pas de sens de l'activer systématiquement. Par exemple pour ActivityPods, j'utilise le service LDP mais le service VOID n'a aucun sens car ce sont des données avant tout privées. D'ailleurs je ne pense pas qu'il fonctionnerait avec une configuration de type PODs.

2022-06-20 16:07 UTC, srosset81 commented on src/middleware/packages/ldp/bots/resources-watcher.js
> +    create(resourceUri, newData) {
J'utiliserai plutôt `resourceCreated` si `created` n'est pas utilisable. `create` est incorrect car cette méthode est appelée *après* que la ressource ait été créées. Même chose pour update/delete.

2022-06-20 16:07 UTC, srosset81 commented on website/docs/middleware/mirror.md
> +You can retrieve the mirrored data with `LDP GET` and you can also link to this data inside your containers, with `LDP PATCH`.
Comment on fait pour récupérer les données miroir avec un LDP GET ? Je pensais que ça serait seulement disponible via une requête SPARQL (ou en appelant `ldp.resource.get` depuis un autre service Moleculer)

2022-06-20 16:07 UTC, srosset81 commented on src/middleware/packages/ldp/services/void/index.js
> +        throw new MoleculerError('Accept not supported : ' + accept, 400, 'ACCEPT_NOT_SUPPORTED');
Pour les endpoints LDP, si on accède à l'endpoint avec le navigateur (accept: `text/html,application/xhtml+xml...`), il bascule par défaut sur du JSON-LD. Je crois que ça se fait grâce au middleware `negotiateAccept`. Ce serait bien si ça pouvait être reproduit parce que c'est quand même pratique de pouvoir voir un endpoint avec un navigateur.

2022-06-20 16:07 UTC, srosset81 commented on src/middleware/packages/ldp/services/void/index.js
> +      return res.filter(c => c['http://rdfs.org/ns/void#entities']);
Il faut retourner aussi les containers vides, car le frontend va se baser sur l'endpoint VOID pour déterminer les containers disponibles. Donc enlever le filtre.

2022-06-20 16:07 UTC, srosset81 commented on src/middleware/packages/ldp/services/void/index.js
> +              'http://rdfs.org/ns/void#class': c.acceptedTypes
Il se peut que `acceptedTypes` soit une string et non un array (tout comme en JSON-LD un array d'un seul élément s'affiche sous forme de string). A ce moment le code lance une erreur 500. Ce serait bien de forcer un array (`Array.isArray(c.acceptedTypes) ? c.acceptedTypes : [c.acceptedTypes]`) pour réduire les erreurs lors de la migration.

2022-06-20 16:07 UTC, srosset81 commented on src/middleware/packages/ldp/services/void/index.js
> +  },
Il y a des contextes qui manquent et rendent le résultat de l'endpoint moins lisibles:

```
void:entities: { @type: "xsd:integer" },
void:class: { @type: "@id" },
```

2022-06-20 16:07 UTC, srosset81 commented on src/middleware/packages/mirror/index.js
> +      // the container update will retrieve the new resource anyway
Autre problème: lorsque je POSTe une ressource sur un serveur A, le serveur miroir B reçoit une activité `Update`, mais avec l'URI du container et non de la ressource. Ce n'est pas clair comme comportement. Pour que ça soit utilisable et clair, il faut des activités Create/Update/Delete avec à chaque fois l'URI de la *ressource* concernée. Au service miroir de déduire ensuite s'il faut mettre à jour le container.

2022-06-20 16:07 UTC, srosset81 commented on src/middleware/packages/ldp/services/container/actions/patch.js
> +                    turtleToSparql += `<${insUri}> <http://semapps.org/ns/core#orphanMirroredResource> <${
Est-ce que ça a du sens de parler d'orphelins ? Ces ressources ne sont pas orphelines puisqu'elles sont liées à une ressource miroir. Peut-être parler de `singleMirroredResource` aurait plus de sens ? (C'est ouvert à discussion)

2022-06-23 13:04 UTC, nikoPLP commented on src/middleware/packages/ldp/services/resource/actions/create.js
> +      resource: contentType === MIME_TYPES.JSON ? resource : resource.body,
quand j'ai pris le code en l''etat dans next, il n'y avait aucun middleware qui s'en chargeait pour du contenu de type turtle, ou sparql. j'ai donc rajouté deux middlewares : `parseSparql` et `parseTurtle` qui mette le contenu du body dans `resource.body`. pourquoi? car `resource` est un object javascript. qui doit au moins contenir un id. j'y rajoute donc le body qui est du texte (pas parsable. ce n'est pas du JSON).
je ne vois vraiment pas comment je pourrais mettre du texte dans `resource` d'une autre maniere.

2022-06-23 13:05 UTC, nikoPLP commented on src/middleware/packages/ldp/services/resource/actions/patch.js
> +      let newTriples = await this.bodyToTriples(body || resource, contentType);
cf ma reponse precedente

2022-06-23 13:05 UTC, nikoPLP commented on src/middleware/packages/middlewares/index.js
> +    req.$params.body = await getRawBody(req);
cf ma reponse precedente

2022-06-23 14:13 UTC, srosset81 commented on src/middleware/packages/ldp/services/resource/actions/create.js
> +      resource: contentType === MIME_TYPES.JSON ? resource : resource.body,
Il y a un moment où on pouvait faire du POST/PUT/PATCH en Turtle, et à ce moment les données Turtle était directement dans le param `resource`. Mais en regardant le code, j'ai l'impression que ça a été perdu à un moment, certainement dû au fait qu'on n'utilise jamais le format Turtle. :-/ Et du coup on utilise effectivement `resource.id` pour obtenir l'URI de la ressource.

2022-06-23 14:15 UTC, srosset81 commented on src/middleware/packages/ldp/services/resource/actions/create.js
> +      resource: contentType === MIME_TYPES.JSON ? resource : resource.body,
On a aucun test d'intégration avec du Turtle en tout cas, sauf pour du GET. Ceci explique cela.

2022-06-23 14:29 UTC, nikoPLP commented on src/middleware/packages/ldp/services/registry/index.js
> +            parentContainerUri = urlJoin(parentContainerUri, '/');
le nouveau code fonctionne bien. le probleme de l'issue 10 de url-join est lié au queryString. nous n'en avons pas dans les Uri de container. 
il me semble important d'utiliser le nouveau code, car l'ancien code pouvait générer des bugs.
is parentContainerUri est le container root, alors faire `+ '/'` dessus va donner un double slash a la fin. 
pareil pour baseUrl, aucune garantie dans notre code que le baseUrl entré dans les settings contienne deja un trailing slash.
Je laisse le nouveau code, si ca va pour vous.

2022-06-23 14:30 UTC, nikoPLP commented on src/middleware/packages/ldp/services/resource/index.js
> +      rule: '0 * * * * *',
oui en effet, je me suis trompé, je voulais faire toutes les heures. je le change

2022-06-23 14:36 UTC, nikoPLP commented on src/middleware/packages/ldp/services/resource/methods.js
> +          { resource: { id: resourceUri }, body: newResource, webId: 'system', contentType: MIME_TYPES.TURTLE },
C'est un PUT en turtle. donc comme indiqué ci dessus en reponse aux comentaires de Simon, le parametre resource ne peut pas etre utilisé pour passer du `plain text`.

2022-06-23 14:41 UTC, simonLouvet commented on src/middleware/packages/ldp/services/resource/actions/create.js
> +      resource: contentType === MIME_TYPES.JSON ? resource : resource.body,
La philosophie qui était appliquée dans toute la conception des services LDP c'est que la ressource était fournie aux service dans sa forme d'origine. C’était au service de traiter correctement la ressource en fonction du content-type également fournie à ces services. La ressource n’était donc pas seulement du json mais pouvait être du ttl ou xml ou autre chose.

2022-06-23 15:08 UTC, nikoPLP commented on src/middleware/packages/mirror/index.js
> +    const uri = urlJoin(this.settings.baseUrl, '/users', actorSettings.username);
j'ai choisi la deuxieme option : trouver le container via le service ldp.registry en matchant acceptedType === "Application"

je mets a jour la doc en consequent.

2022-06-23 15:26 UTC, srosset81 commented on src/middleware/packages/ldp/services/resource/actions/create.js
> +      resource: contentType === MIME_TYPES.JSON ? resource : resource.body,
Oui on est d'accord, mais la réalité actuelle c'est que le format Turtle ne marche plus en PUT/PATCH/POST ! Il faudrait réécrire ces méthodes et ajouter des tests. Cela ne rentre pas dans le cadre de cette PR.

2022-06-23 15:27 UTC, srosset81 commented on src/middleware/packages/ldp/services/resource/methods.js
> +          { resource: { id: resourceUri }, body: newResource, webId: 'system', contentType: MIME_TYPES.TURTLE },
Voir mes réponses ci-dessus. Normalement `resource` devait pouvoir contenir du texte Turtle. C'est cassé et il faudra revoir ça dans une autre PR.

2022-06-23 15:29 UTC, simonLouvet commented on src/middleware/packages/ldp/services/resource/actions/create.js
> +      resource: contentType === MIME_TYPES.JSON ? resource : resource.body,
Est ce que on sait depuis quand ils ne fonctionnent plus? Je les ai toujours vu fonctionner mais si il n'y avait pas de test automatisé pour éviter la regression...

2022-06-23 15:29 UTC, srosset81 commented on src/middleware/packages/ldp/services/registry/index.js
> +            parentContainerUri = urlJoin(parentContainerUri, '/');
Si `urlJoin(parentContainerUri, '/')` ajoute bien un slash à la fin, ça me va ! C'est plus propre.

2022-06-23 16:08 UTC, nikoPLP commented on src/middleware/packages/mirror/index.js
> +      // the container update will retrieve the new resource anyway
C'est implementé comme ça pour eviter de surcharger les serveurs et le réseau en cas de modification lourde d'un container (beaucoup d'ajout ou de remove), et notamment, lorsque les permissions ACL "default" sont modifiées, ce qui génère beaucoup de changement.
J'essaie au maximum de limiter le nombre d'ANNOUNCE envoyés.
La logique que j'ai implémentée fait sens pour maintenir les mirroirs synchrones tout en gardant le nombre d'activités envoyées au strict minimum. 
Ce que tu propose est peut etre plus élégant sématiquement, mais beaucoup plus lourd au niveau du réseau et des messages ActivityPub échangés. Il faut garder a l'esprit aussi que tous ces messages restent enregistrés des deux cotés (dans les outbox et inbox)... bref il me semble qu'il faut rester concis. 
Ce n''etait pas dans l'idée originale (et pas indiqué dans les specs) que ce servir de mirroir pourrait ete utilisé pour autre chose que la synchronisation des mirroirs.
Ce qui m'importait en implémentant pour moi, c'était que ca fonctionne bien et que ca ne soit pas trop gourmants en resources et que les performances soient bonnes.
J'ai peur que d'envoyer deux messages pour chaque resource qui est ajoutée a un container (le CREATE puis le UPDATE du container) soit plus gourmant en resources, surtout lors que les droits "default" sont modifiés.
Pour le moment je souhaiterai laisser l'implémentation telle qu'elle est.
Voir si ca fonctionne bien.
Changer ce fonctionnement implique pas mal de code a changer...

2022-06-23 16:14 UTC, nikoPLP commented on src/middleware/packages/webacl/services/resource/actions/setRights.js
> +          defaultRemovePublicRead
> Est-ce que `defaultAddPublicRead` et `defaultRemovePublicRead` prennent en compte le fait qu'il peut y avoir plusieurs sous-containers, et que le droit par défaut peut être donné au root container p.ex. ?

oui. listAllResourcesInSubContainer est recursif.

2022-06-23 16:19 UTC, nikoPLP commented on src/middleware/packages/webacl/services/resource/actions/setRights.js
> +          defaultRemovePublicRead
> Je trouve le nom des 4 nouveaux params envoyés pas clair, et je suis pas sûr qu'on va comprendre pourquoi il faut envoyer tout ça avec l'event. Ne pourrais-tu juste pas juste appeler `webacl.resource.getRights` à réception de l'event pour obtenir ces informations ? Cela me semblerait être plus cohérent avec la philosophie des microservices, où chaque service s'occupe d'obtenir les informations dont il a besoin.

ces parametres sont utlisés seulement par le service mirroir et sont envoyés par le service webacl. aucun developeur ne sera ammené a les fournir si il émet l'event en question `webacl.resource.updated`. (qui n ést pas émit en dehors du code du service webacl, de toute facon).

J'ai besoin de connaitre le diff des permissions default. C'est a dire de savoir si des permissions default ont été ajoutées ou enlevées. Et ce n ést pas possible d'obtenir cette information après coup, une fois que l'event est envoyé. donc c'est bien a l'emetteur de l'event de me donner cette information, qui n ést disponible qu'a ce moment.

les noms sont peut etre un peu bizarre. et il faudrait renommer defaultAddPublicRead en addDefaultPublicRead et pareil pour Remove.

2022-06-23 16:21 UTC, nikoPLP commented on website/docs/middleware/ldp/container.md
> +| `contentType` | `String` | **optional** | must be `application/sparql-update`) |
C'est spécifié dans la doc de Solid LDP. Inrupt utilise ce format pour les updates donc j'ai fait pareil.

2022-06-23 16:52 UTC, srosset81 commented on src/middleware/packages/ldp/services/resource/actions/create.js
> +      resource: contentType === MIME_TYPES.JSON ? resource : resource.body,
Aucune idée !

2022-06-23 17:27 UTC, nikoPLP commented on website/docs/middleware/mirror.md
> +You can retrieve the mirrored data with `LDP GET` and you can also link to this data inside your containers, with `LDP PATCH`.
je voulais dire `ldp.resource.get` c'est corrigé dans la doc.

2022-06-23 18:29 UTC, nikoPLP commented
j'ai essayé de répondre a toutes vos questions et de modifier ce qui était modifiable.
Le code mis a jour est dipo dans la branche !
La prochaine etape serait de tester l'integration avec le frontend ?

2022-06-24 08:54 UTC, srosset81 commented on src/middleware/packages/mirror/index.js
> +      // the container update will retrieve the new resource anyway
C'est dommage on aurait dû en parler avant, mais c'est vrai que j'étais malade. Je trouve que l'issue https://github.com/assemblee-virtuelle/semapps/issues/850 était tout de même assez claire.
Le service ActivityPub n'a pas de soucis à gérer un grand nombre d'activités. Ca génère beaucoup de triplets dans le triplestore, mais tu disais toi-même que c'était pas un problème. La seule chose qui peut peut-être poser problème, c'est le POST vers les autres serveurs fédérés: s'il y a beaucoup de données à POSTer, il faudrait peut-être mettre un delay. Mais ce serait une amélioration bénéfique.
Pour moi, c'est bien qu'ActivityPub soit utilisé pour décrire précisément les activités qui sont effectuées. En l'occurence, une activité Update sur un container n'indique pas qu'une (ou plusieurs) ressource est créée.
Et c'est vrai que dans ma tête, cet acteur Relay aurait pu avoir d'autres usages que du mirroir, tout comme les acteurs Relay de Peertube ou Mobilizon permettent à n'importe quelle application de savoir ce qui se passe sur une instance.
Mais OK pour laisser comme tel pour le moment.

2022-06-24 08:57 UTC, srosset81 commented on src/middleware/packages/webacl/services/resource/actions/setRights.js
> +          defaultRemovePublicRead
OK je comprend, merci pour les explications.
`addDefaultPublicRead` et `defaultRemovePublicRead` serait en effet beaucoup plus clair !

2022-06-24 09:02 UTC, srosset81 commented
Merci @nikoPLP !
J'ai répondu à tes commentaires. Lundi je teste tes modifications en vue de merger ! :-)
Concernant le frontend, oui il y a encore pas mal de boulot ! Surtout dans l'interprétation de l'endpoint VOID et la modifications des requêtes SPARQL afin qu'elles prennent en compte les données miroirs. J'ai ajouté la gestion du PATCH sur container dans la PR https://github.com/assemblee-virtuelle/semapps/pull/992.

2022-06-24 10:00 UTC, nikoPLP commented on src/middleware/packages/mirror/index.js
> +      // the container update will retrieve the new resource anyway
Ok ! on peut laisser comme ca pour les prochaines semaines. Et je veux bien changer le code assez rapidemment si besoin. Je comprends ta demande légitime. Par contre ca va etre un peu casse-tete a realiser, car il faudra s'assurer que les activité CREATE des resources sont bien envoyées avant les UPDATE des containers. Et synchroniser des events dans moleculer... je ne sais pas comment faire.

2022-06-24 10:01 UTC, nikoPLP commented on src/middleware/packages/webacl/services/resource/actions/setRights.js
> +          defaultRemovePublicRead
C'est renommé

2022-06-24 10:04 UTC, nikoPLP commented
> modifications des requêtes SPARQL afin qu'elles prennent en compte les données miroirs

Si tu veux parler des actions `ldp.resource.get` et `ldp.container.get`, j ái deja fait le code. Elles retournent bien les resources en mirroir.

Si tu veux parler de requete Sparql autres, qui sont lancées depuis le client, alors en effet, il faut rajouter un `UNION` avec le graph mirroir.

2022-06-24 10:05 UTC, nikoPLP commented
Je viens d'implementer ce matin la derniere tache qui m'incombe, a savoir https://github.com/assemblee-virtuelle/semapps/issues/771 

Je l ái mis dans la meme branche car ca fait partie du meme projet pour moi, et je voudrais bien que ce soit validé et merger en meme temps.

Encore un peu plus de code a reviewer et tester pour toi, @srosset81

2022-06-24 10:08 UTC, nikoPLP commented on src/middleware/packages/mirror/index.js
> +      // the container update will retrieve the new resource anyway
Et oi, j'avais bien compris la tache #850, et j'ai essayé au début de l'implémenter avec une activité CREATE (il y ades traces de ca dans le code). Mais ca c'est avéré plus compliqué que prévu et j ái du faire les changements qui ont conduit a une sématique moins bonne, en effet, j'en suis conscient.

2022-06-24 13:01 UTC, srosset81 commented
> Si tu veux parler de requete Sparql autres, qui sont lancées depuis le client, alors en effet, il faut rajouter un `UNION` avec le graph mirroir.

Oui je parle de ça.

2022-06-27 08:46 UTC, srosset81 requested changes

2022-06-27 08:46 UTC, srosset81 commented on src/middleware/packages/ldp/services/container/actions/patch.js
> +                    this.logger.warn('ERROR while IMPORTING ' + insUri + ' : ' + e);
Je pense que tu dois mettre `e.message` car `e` est un objet et n'apparaîtra pas.

2022-06-27 08:46 UTC, srosset81 commented on src/middleware/packages/mirror/index.js
> +        if (c.acceptedTypes && !actorContainer && defaultToArray(c.acceptedTypes).includes('Application')) actorContainer = c.path;
Faudrait plutôt utilisé un `.forEach` puisque tu ne t'occupes pas des valeurs de retour.

2022-06-27 08:46 UTC, srosset81 commented on src/middleware/packages/mirror/index.js
> +      return [this.relayFollowersUri, PUBLIC_URI] //result ? defaultToArray(result.items) : [];
Enlever commentaire. La fonction getFollowers est-elle toujours nécessaire ?

2022-06-27 08:46 UTC, srosset81 commented on src/middleware/packages/void/index.js
> +const { getPrefixJSON, createFragmentURL, regexProtocolAndHostAndPort } = require('@semapps/ldp/utils');
Tu peux importer ces utils directement de `@semapps/ldp`

2022-06-27 08:46 UTC, srosset81 commented on src/middleware/packages/void/index.js
> +};
Tu peux importer defaultToArray de `@semapps/ldp` aussi.

2022-06-27 08:46 UTC, srosset81 commented on src/middleware/packages/void/README.md
> +[Documentation](https://semapps.org/docs/middleware/mirror/index)
Faudrait une documentation indépendante de mirror, car on peut utiliser VOID sans le package mirror. Mais bon, on pourra voir ça plus tard...

2022-06-27 08:46 UTC, srosset81 commented on src/middleware/packages/ldp/services/resource/actions/get.js
> +          const redirect = await this.settings.preferredViewForResource(resourceUri, preferredView);
Ta solution est bien pensée, merci ! Je me demande quand même si on pourrait pas passer toute l'objet de config du container (ce qui est retourné par `ldp.registry.getByUri` plus haut) à `preferredViewForResource`, ce qui donnerait plus de liberté au développeur pour utiliser ce dont il a besoin ? (il pourrait utiliser `preferredView` ou d'autres configs)

2022-06-27 08:46 UTC, srosset81 commented on website/docs/middleware/ldp/index.md
> +    }
Il est peut-être important de préciser que `preferredViewForResource` est une fonction async (on l'appelle avec un `await`), ce qui peut permettre de faire plus de choses ?

2022-06-27 08:49 UTC, srosset81 commented on src/middleware/packages/ldp/services/resource/actions/get.js
> +          const redirect = await this.settings.preferredViewForResource(resourceUri, preferredView);
Je ne suis pas sûr que ce soit mieux, je suis donc preneur de ton avis ! ;-)

2022-06-27 09:59 UTC, nikoPLP commented on src/middleware/packages/ldp/services/resource/actions/get.js
> +          const redirect = await this.settings.preferredViewForResource(resourceUri, preferredView);
il peut mettre ce qu'il veut dans preferredView (des options compliquées). et il peut appeler `ldp.registry.getByUri` ou toute autre action si besoin... mais je pense que ca va etre rare.

2022-06-27 10:00 UTC, nikoPLP commented on website/docs/middleware/ldp/index.md
> +    }
oui c'est appelé avec await ce qui permet en effet de faire des appels async a l'interieur (pour appeler des actions ou autre). je le mets dans la doc

2022-06-27 10:37 UTC, srosset81 commented on src/middleware/packages/ldp/services/resource/actions/get.js
> +          const redirect = await this.settings.preferredViewForResource(resourceUri, preferredView);
Hmm non on ne peut pas appeler `ldp.registry.getByUri` car on n'a pas accès au `ctx`, ni à `this.broker`. Sauf si tu fais un bind ? La syntaxe serait `await this.settings.preferredViewForResource.bind(this)(resourceUri, preferredView)`. Je pense que c'est une bonne idée. Je le fais pour le ActivitiesHandlerMixin (et les importers) et ça marche bien.

2022-06-27 14:11 UTC, srosset81 approved these changes

2022-06-27 14:12 UTC, merged