Add multiUrlField and MultiLinesInput in frontend components
assemblee-virtuelle/semapps pull request #994
Opened 2022-06-22 15:44 UTC by fluidlog

Come from Organigraph components

2022-06-22 15:49 UTC, fluidlog commented
Une fois cette PR validée, il faudra que je publie les packages NPM...

2022-06-22 16:23 UTC, fluidlog commented
Voir documentation ici : https://pad.lescommuns.org/Archipelago-Corrections-website

2022-06-23 12:35 UTC, srosset81 requested changes

2022-06-23 12:35 UTC, srosset81 commented on src/frontend/packages/field-components/src/MultiUrlField.js
> +    const chip = { label: parseUrlString, icon: <LanguageIcon />, color: '#ea', contrastText: 'black' };
Pourquoi ne pas avoir gardé le `domainMapping` utilisé par OrganiGraph ? On pourrait mettre des valeurs par défaut pour des domaines standard (genre Github) et donner la possibilité d'ajouter d'autres domaines plus spécifique (p.ex. forums.assemblee-virtuelle.org) via une props. 
Ca fait un résultat beaucoup plus joli. En plus là en mettant le lien complet dans le label, ça va fait des `Chip` super longs, ce qui n'est pas adapté à mon avis.

2022-06-23 12:37 UTC, srosset81 commented on src/frontend/packages/field-components/src/MultiUrlField.js
> +    const chip = { label: parseUrlString, icon: <LanguageIcon />, color: '#ea', contrastText: 'black' };
Si tu veux absolument montrer les liens complets pour tes sites, il faudrait au moins donner la possibilité de choisir entre un affichage court et un affichage long (URL complet). L'idée c'est quand même que ce composant puisse être utilisé aussi par OrganiGraph, afin de ne pas multiplier les composants.

2022-06-23 21:42 UTC, fluidlog commented on src/frontend/packages/field-components/src/MultiUrlField.js
> +    const chip = { label: parseUrlString, icon: <LanguageIcon />, color: '#ea', contrastText: 'black' };
Tout à fait, je suis d'accord pour améliorer ça, je pensais bien que j'allais itérer en plusieurs fois :)
Je vais regarder l'histoire du domaine mapping... et en effet, il faudrait au moins qu'Organigraph puisse facilement l'utiliser... Je regarde ça demain ou la semaine prochaine.

2022-06-24 08:40 UTC, srosset81 commented on src/frontend/packages/field-components/src/MultiUrlField.js
> +    const chip = { label: parseUrlString, icon: <LanguageIcon />, color: '#ea', contrastText: 'black' };
L'autre problème avec une URL très longue, c'est que sous mobile ça peut faire sortir de l'espace disponible et casser toute la page. Pour les CDLT, on a utilisé `maxWidth: "-webkit-fill-available",` pour éviter ça (cf https://github.com/chemins-de-la-transition/semapps/pull/429) J'ai pas testé sur navigateur cela dit.

2022-06-29 10:37 UTC, fluidlog commented
Voilà, j'ai remis en place le domain mapping.
On peut en effet faire mieux en ajoutant des props, mais j'ai envie de publier mes NPM comme ça, histoire d'aller jusqu'au bout de mon correctif (il me reste encore à pointer Archipelago dessus et à publier sur mes serveurs...).
Comme ça, on peut simplement faire pointer Organigraph dessus sans changer la logique, et on améliorera plus tard si besoin.
Ca te va ?

2022-06-29 10:43 UTC, srosset81 commented
On ne peut pas garder des mappings de type peertube.assemblee-virtuelle.org ou forums.assemblee-virtuelle.org pour un composant qui a pour vocation d'être utilisable partout, ça ne fait pas sérieux.

Ajouter une prop optionelle `domainMapping` et la merger avec le domainMapping par défaut (`defaultDomainMapping`) ne demande qu'une ligne de code.

2022-06-29 10:46 UTC, srosset81 commented
D'ailleurs l'image utilisée `src="/lescommuns.jpg"` n'est valable que si on la inclus sur son propre site.

2022-06-29 11:14 UTC, fluidlog commented
OK, je suis d'accord avec ça, c'est la raison pour laquelle au début je l'avais retiré, car je ne trouvais pas ça assez générique...
Donc ok si tu pense que c'est simple, je vais essayer d'ajouter les props. Je te tiens au jus demain normalement (j'ai autre chose de prévu cet aprem).

2022-06-30 13:34 UTC, fluidlog commented
Voilà, j'ai poussé en intégrant le domainMapping dans les props.
Je n'ai pas réussi à limiter les warnings dûs au keys manquantes...

2022-06-30 13:45 UTC, srosset81 requested changes

2022-06-30 13:45 UTC, srosset81 commented on src/frontend/packages/field-components/src/MultiUrlField.js
> +    icon: <Avatar src="https://opencollective.com/static/images/opencollective-icon.svg" />,
Tu n'as pas importé le composant Avatar ;-(

2022-06-30 13:58 UTC, fluidlog commented on src/frontend/packages/field-components/src/MultiUrlField.js
> +    icon: <Avatar src="https://opencollective.com/static/images/opencollective-icon.svg" />,
Ah oui, vu que j'ai testé avec d'autres données, je ne l'ai pas vu... merci

2022-06-30 14:29 UTC, srosset81 approved these changes

2022-06-30 14:47 UTC, merged